### ISSUE TITLE
Where a settings stored? Export+reimport on another computer

### ISSUE THREAD

**Issue by bsto** [MathewSachin/Captura#100]
Where are the settings pf Captura stored?

I prefer a storage into an *.ini file in the installation folder. This way I could keep all related files together and run Capture from USB flash drive.

Furthermore I could copy this *.ini file onto another computer into another Capture installation

Could you let users at least export (+import) settings

**Comment by MathewSachin** [comment]
The settings are stored in Captura folder in the AppData folder.
More specifically: `%AppData%/Captura/`.
You can copy this folder to another computer.

Storing the settings in app directory might be problematic since directory access may not always be available.
e.g. Let's suppose Captura is installed in `Program Files`. Creating a settings file there would require Administrator permission.

Export/Import seems worth implementing. Would surely try to implement.

**Comment by bsto** [comment]
I am NOT only talking about storing in the app directory but on an arbitrary directory like

D:\tools\cap\
...or on an USB flash drive.

At least Captura should give the users an option to store it somewhere else.
If there are Adminstrator permissions prohibiting the writing then ok - bad luck.
However in 99% of the cases writing is allowed.

**Comment by MathewSachin** [comment]
Custom Settings directory seems good, will implement.

**Comment by MathewSachin** [comment]
I'm facing a problem here. I'll have to store the path to the settings directory somewhere.
I cannot store that in Settings.
Let me know your thoughts.

**Comment by bsto** [comment]
Store it in an *.ini file in installation directory (if possible).
If it is not possible use the current AppData

Another idea: Offer a cmdline parameter:

Caputure.UI.exe -settings="D:\tools\cap\"

or simpler (mind the blank after*.exe):

Caputure.UI.exe "D:\tools\cap\"

**Comment by MathewSachin** [comment]
`Captura.UI.exe -settings="D:\tools\cap\"` seems good.

This way if you keep Captura in a portable directory with Settings in Settings folder under the same directory, you can have a batch file; `Captura.bat` containing: `Captura.UI -settings="Settings"` to simplify opening.

Will implement soon.

**Comment by MathewSachin** [comment]
Merged into master
