### ISSUE TITLE
Let users select installation folder + offer a portable version

### ISSUE THREAD

**Issue by bsto** [MathewSachin/Captura#101]
As I found out the user has no choice where to install Capture.

He is forced to install it into 

C:\Users\<username>\AppData\Local\Captura\

Why not letting the user select a different folder e.g.

D:\tools\screenrec\Captura\
?
Furthermore I would appreciate if you could offer another separate portable package of Capture
which needs only to be extracted to run.

Thanks

**Comment by MathewSachin** [comment]
Portable builds are available. Go to the [Releases](https://github.com/MathewSachin/Captura/releases) page, and download `Captura-Release.zip`.

Custom installation folder might be implemented in the future.

**Comment by MathewSachin** [comment]
I've tried migrating to Inno Setup and it seems to be working fine.
Here's an EXE for testing purposes: https://ci.appveyor.com/api/buildjobs/o4g0ddyxdffc3r0h/artifacts/Output%2FCaptura-Setup.exe

The only problem I feel is that the previous installations need to be uninstalled separately.

**Comment by MathewSachin** [comment]
I'm trying to use Inno Setup. See https://github.com/MathewSachin/Captura/pull/102

**Comment by MathewSachin** [comment]
Done
