### ISSUE TITLE
Multiple screens bug

### ISSUE THREAD

**Issue by limacezzz** [MathewSachin/Captura#106]
When i try to capture DISPLAY1 only it captures DISPLAY1 and a black screen at the position of DISPLAY2, so the result is, on the left of the screen, my video and on the right, a black square.

**Comment by limacezzz** [comment]
I just found out that enabling desktop duplication api forces captura to capture one screen and an empty black square.

**Comment by MathewSachin** [comment]
I don't have multiple monitors. So, never had an option to check that.

Desktop Duplication can indeed capture only one Screen at a time.
May I know whar happens when you select `DISPLAY2` and record with Desktop Duplication?

**Comment by limacezzz** [comment]
i get something like this : (same as if i choose display1)
![image](https://user-images.githubusercontent.com/11949357/30784290-cf8b764c-a152-11e7-929c-f2578ce3d58e.png)

**Comment by MathewSachin** [comment]
Please test this build: https://ci.appveyor.com/api/buildjobs/jn9gtygmgtke9uit/artifacts/Captura-Portable.zip

**Comment by limacezzz** [comment]
When i select display1, recording is perfect. With display2, captura don't record anything but a black screen.

**Comment by MathewSachin** [comment]
Did another fix, please test: https://ci.appveyor.com/api/buildjobs/4rb9i2ta91psiwj8/artifacts/Captura-Portable.zip

**Comment by limacezzz** [comment]
Well done, now each screen is recorded correctly.
