### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Captura#108]
Add translations for more languages.

See the [Translation Guide](https://github.com/MathewSachin/Captura/wiki/Translation)

Happy [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

### Already done:
- *Arabic*
- *Czech*
- *Danish*
- *Dutch*
- English
- *Finnish*
- *French*
- *German*
- *Hebrew*
- *Icelandic*
- *Indonesian*
- *Italian*
- Malayalam
- *Norwegian*
- *Polish*
- Portuguese
- *Romanian*
- Russian
- Spanish
- *Swedish*
- *Thai*
- *Turkish*
- *Ukrainian*

Thank you to all the contributors. 🎉

**Comment by flxn** [comment]
Hi,
I'm working on a german translation.
Will submit a PR soon.

**Comment by MathewSachin** [comment]
@flxn Great! I'll be happy to merge,

**Comment by vitorfhc** [comment]
Did you mean to write portuguese? And anyone already working on portuguese translation?

**Comment by MathewSachin** [comment]
I'm sorry Portugese is already done.

**Comment by simocosimo** [comment]
Working on the Italian translation!

**Comment by TheFaR8** [comment]
Hi
I'll work on an Indonesian translation

**Comment by j4nw** [comment]
Working on a Polish translation.

**Comment by Marusyk** [comment]
Working on a  Russian translation.

**Comment by MathewSachin** [comment]
@Marusyk we already have a Russian translation.
Thank you for your desire to help.

**Comment by Marusyk** [comment]
Working on a Ukrainian translation.

**Comment by PimMeulensteen** [comment]
I'm working on a Dutch translation.

**Comment by mohi-othman** [comment]
Arabic translation added

**Comment by baptistecolin** [comment]
Working on a French translation

**Comment by Mknsri** [comment]
Hey, I added a translation in Finnish #123

**Comment by Martin4ndersen** [comment]
Added Danish translation https://github.com/MathewSachin/Captura/pull/124

**Comment by theomessin** [comment]
Happy Hacktoberfest indeed! Working on Greek translation :heart:

**Comment by kerlos** [comment]
Added Thai translation #128

**Comment by LShun** [comment]
I'll start working on Simplified Chinese translation

**Comment by AndreeaEne** [comment]
Starting on Romanian 🥇

**Comment by sgbasaraner** [comment]
Happy Hacktoberfest!
#138

**Comment by MathewSachin** [comment]
Will be waiting for the next Hacktoberfest!

Thank you to all the awesome contributors 👍

**Comment by jmroyb** [comment]
Hi folks,

I send catalan translation for v8.0.0
[ca-ES.zip](https://github.com/MathewSachin/Captura/files/3720827/ca-ES.zip)

Regards

**Comment by MathewSachin** [comment]
@jmroyb Thank you for the translation!

BTW, we now have a better workflow for translation using CrowdIn.
I've uploaded the translations there.
Be sure to use CrowdIn for further translations.
Here's the link to the CrowdIn project: https://crowdin.com/project/captura.
Send a request to join the project and I'll make sure to accept it.

**Comment by jmroyb** [comment]
Thanks Mathew. Done. It's my first contribution in Crowdin. I hope to have done it correctly

Please take on mind, in https://crowdin.com/project/captura when you say Catalan you are referring to generic Catalan language (only in Catalunya or Catalonia in English Region). 

Foreign developers do not know there are several Catalan regions and every region speaks its own Catalan. It causes estrange translations, specially ca-ES and ca-ES-valencia.

Wikipedia is an example: I'm tired to overwrite translations.

https://dotnetfiddle.net/e1BX7M

ca          			ca-ES       		Catalan
ca-AD       		ca-AD       		Catalan (Andorra)
ca-ES       		ca-ES       		Catalan (Catalan)
ca-ES-valencia	ca-ES-valencia	Valencian (Spain)
ca-FR       		ca-FR       		Catalan (France)
ca-IT       			ca-IT       			Catalan (Italy)

Regards

**Comment by MathewSachin** [comment]
@jmroyb I'd prefer to keep generic Catalan only.
Maintaining all the different variations would be pretty tough.
