### ISSUE TITLE
suggestion or help

### ISSUE THREAD

**Issue by Jhovany200** [MathewSachin/Captura#136]
as suggestion or help in the "latest version" of "Inno Setup" does not show (WizardImageFile) and shows the license agreement directly, and if you need to put the image ftontal works in version 5.5.6. "And not in later versions".

**Comment by MathewSachin** [comment]
We currently use `WizardImageFile` and also don't show license agreement.

**Comment by Jhovany200** [comment]
you did not understand me, the version of Inno Setup 5.5.6 shows (WizardImageFile).
And the other later versions no longer show (WizardImageFile).
example: 5.5.7 - 5.5.8 - 5.5.9 is not displayed (WizardImageFile).

conclusion: 
if you want to place (WizardImageFile) use version 5.5.6.
if you do not want to use (WizardImageFile) use version 5.5.7 - 5.5.8 - 5.5.9.

**Comment by MathewSachin** [comment]
ok. Got it
