### ISSUE TITLE
Advice by experience of use.

### ISSUE THREAD

**Issue by Jhovany200** [MathewSachin/Captura#137]
You did not understand me, the version of Inno Setup 5.5.6 shows (WizardImageFile).

And the other later versions no longer show (WizardImageFile).
example: 5.5.7 - 5.5.8 - 5.5.9 is not displayed (WizardImageFile).

conclusion: 
if you want to place (WizardImageFile) use version 5.5.6.
if you do not want to use (WizardImageFile) use version 5.5.7 - 5.5.8 - 5.5.9.

**Comment by MathewSachin** [comment]
Got it
