### ISSUE TITLE
Is it possible to use Captura's DLLs for making screenshots into shared memory

### ISSUE THREAD

**Issue by PavelValentov** [MathewSachin/Captura#140]
It needs to make screenshots and execute them.
One sulution is to make screenshot into shared memory, and execute it in a target application.
Is there an Captura's API which can do a part of this.

**Comment by MathewSachin** [comment]
I'm sorry. I think I didn't understand the question correctly.

Based on what I understand:
If you want recorded images to be written to shared memory, you can use Screna.dll with a custom implementation of IVideoFileWriter.
