### ISSUE TITLE
Screen recording crashes after +15min running

### ISSUE THREAD

**Issue by vil0es** [MathewSachin/Captura#141]
When using screen recording to MP4 (x264 | AAC) recording stops after 15-20min. running.
No webcam or audio, just screen #1 with default options. Tested on v6.0 under W10.

![image](https://user-images.githubusercontent.com/6391112/32438701-c31f5422-c2eb-11e7-9ca6-2adece4258ce.png)

PS.
Beautiful code. Congratulations.

**Comment by MathewSachin** [comment]
I need to know a few more things:
- FPS
- Screen Size

Also, is there high CPU or Memory usage before recording stops.

**Comment by vil0es** [comment]
Tested on 2 different screens: 1920x1080 and 1680x1050.
FPS as default (10).
Not high CPU usage observed. Memory consumption goes up and down during whole test, with max. around 3.2GB.

**Comment by MathewSachin** [comment]
So, memory consumption should be the problem.
Since, Capture is built in `Prefer32bit` mode, the maximum memory available to it is 4GB.

I will try to reproduce this issue on my systems.

**Comment by MathewSachin** [comment]
Fine, I have confirmed the issue.
It's happening when **not** using Desktop Duplication.

Will try to fix and do a new release ASAP.

**Comment by vil0es** [comment]
Thank you!

**Comment by MathewSachin** [comment]
v6.0.1 released

**Comment by IDmedia** [comment]
> Fine, I have confirmed the issue.
> It's happening when **not** using Desktop Duplication.
> 
> Will try to fix and do a new release ASAP.

I'm also having this issue. Unfortunately "Desktop Duplication" isn't available as I'm running the video recorder in a virtual machine in Azure. Is there any other way to fix this for GDI as well? :)
