### ISSUE TITLE
[Suggestion] Adding webm option to video encoding

### ISSUE THREAD

**Issue by NeoTU** [MathewSachin/Captura#142]
![webm](https://user-images.githubusercontent.com/11801357/32474915-e2996444-c3ba-11e7-909d-339bb0a13b95.jpg)

Since Captura has FFMpeg support already would it be possible to add webm (VP8) exporting?
While one could use another software to convert mp4 files made in Captura to webm it would be easier if one didn't have to do an extra step like that, all modern browsers support direct webm playback.
I still use WebMCam by thetarkus since Captura doesn't have the option, which I wish it did because besides this I'm very much liking Captura overall, though I'm not sure why the frame rate is limited to 30.

**Comment by MathewSachin** [comment]
WebM encoding using FFMpeg was not implemented because of being very slow.
It resulted in heavy memory usage.

And, the frame rate is limited to 30 fps because the current algorithm cannot handle more.

**Comment by MathewSachin** [comment]
I checked the WebMCam project. It first saves images as png and after recording is completed converts them to webm.

But, the main focus of Captura is to encode simultaneously while recording for which webm is not fast enough.

**Comment by MathewSachin** [comment]
WebM added as Post-encoding encoder.
Select `FFMpeg` | `WebM (Vp8 | AAC) (Post Processing)`

Please test dev build: https://ci.appveyor.com/api/buildjobs/1r98xcblg1wjt1xm/artifacts/temp%2FCaptura-Portable.zip

**Comment by ffMathy** [comment]
How do we use this @MathewSachin? Can you link to the relevant code, or some documentation?
