### ISSUE TITLE
Option to show time elapsed

### ISSUE THREAD

**Issue by szegi** [MathewSachin/Captura#147]
It would great to have an option
to add overlay with time elapsed
something like in [Licecap](https://www.cockos.com/licecap/)
![test](https://user-images.githubusercontent.com/12111506/33100641-63a0a812-cf15-11e7-8621-8c52e89d2a3f.gif)
maybe even with some configuration
like time elapsed/time till end/total time

it would be useful in gif recordings

**Comment by MathewSachin** [comment]
Sure, will implement a time elapsed overlay.
But, total time cannot be determined during recording in the way Captura operates.

**Comment by MathewSachin** [comment]
Feature added to master branch.
Will be available in next release.

**Comment by MathewSachin** [comment]
Here's a [portable build](https://ci.appveyor.com/api/buildjobs/ay6xyfrwg0i6gu5b/artifacts/temp%2FCaptura-Portable.zip) for testing.

**Comment by szegi** [comment]
after quick tests it works great:)
maybe an option with predefined corners will make it simpler to align
because now i have to set right coordinates which is great that i can
but there are most common 4 or 5 positions if we include center
![obraz](https://user-images.githubusercontent.com/12111506/33115175-5e3bef9e-cf60-11e7-894e-069e9ea30ebf.png)

**Comment by MathewSachin** [comment]
Sorry, I didn't understand that.

But, if you are looking for customizing the positioning, go to `Config > Overlays > Time Elapsed`

**Comment by szegi** [comment]
ok i understand now
when i run app for the first time there were some values in X and Y
![obraz](https://user-images.githubusercontent.com/12111506/33120322-00911786-cf72-11e7-8ebd-629545b1aa4c.png)
it would be better if default values were set to 0,0
because first time i saw this option i thought that i have to manually to position this layer every recording
now i will set it to 0,0
and change only left center ..
maybe it would be good idea for diffrent control to this
something like
![obraz](https://user-images.githubusercontent.com/12111506/33121108-2c9a6376-cf74-11e7-9e7b-33cc72cb5acc.png)
but only with one dot
