### ISSUE TITLE
Viruses in Portable Version?

### ISSUE THREAD

**Issue by Syenta** [MathewSachin/Captura#148]
Hi,

I've just downloaded the latest portable version and scanned the files using VirusTotal which found the following issues:

Comodo | Heur.Packed.Unknown | 20171125
Cylance | Unsafe | 20171125
Cyren | W32/GenBl.3EAA0B13!Olympus | 20171125
TrendMicro-HouseCall | Suspicious_GEN.F47V1117 | 20171125

Captura looks great and I would love to install it but having just cleaned my system yesterday from a troublesome infection I am double checking everything prior to installing it.

I have attached the file so you can have a look at it.

[Captura-Portable.zip](https://github.com/MathewSachin/Captura/files/1503092/Captura-Portable.zip)

Hope this helps

**Comment by MathewSachin** [comment]
I scanned both the Setup and Portable versions myself and verified that problems are showing up only with the Portable version.

The problems are being reported in `bassmix.dll`. It's the library we use for audio mixing (microphone input and speaker output).
I'm quite confident that it is virus free.

If you are very much concerned about security, you can `delete bassmix.dll`. Captura will still work but audio support will not be available.

![screenshot 4](https://user-images.githubusercontent.com/10654537/33231047-51226f8e-d214-11e7-91e5-9e2dce771b48.png)

**Comment by MathewSachin** [comment]
Closing since this is not an issue with Captura itself bus BASSmix.
