### ISSUE TITLE
Error FFMpeg + HEVC

### ISSUE THREAD

**Issue by ioscars** [MathewSachin/Captura#149]
![error](https://user-images.githubusercontent.com/19891523/33238831-4416b9fa-d2b7-11e7-8fb7-c7b64ded179c.PNG)

**Comment by MathewSachin** [comment]
It will only work on Intel 6 gen CPUs and later.

Also, please provide FFMpeg log by going to Config / FFMpeg / FFMpeg log

**Comment by ioscars** [comment]
> ffmpeg version N-87353-g183fd30 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 76.100 / 55. 76.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.101 / 57. 82.101
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, rawvideo, from '\\.\pipe\captura-a0660040-9292-40ea-9403-41053b40ca9a':
  Duration: N/A, start: 0.000000, bitrate: 419430 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1024x1280, 419430 kb/s, 10 tbr, 10 tbn, 10 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
[hevc_qsv @ 0000000002ee3960] No device available for encoder (device type qsv for codec hevc_qsv).
[hevc_qsv @ 0000000002ee3960] Error initializing an internal MFX session: unsupported (-3)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by ioscars** [comment]
It will be great if HEVC will work.

**Comment by MathewSachin** [comment]
It appears that Intel QSV isn't supported on your system.

May I know your CPU specifications?

**Comment by ioscars** [comment]
Intel(R) Core(TM) i5-2450M

**Comment by MathewSachin** [comment]
I'm sorry. Your cpu is generation 2 whereas only generation 6 and above support Intel QSV.

We use Intel QSV instead of normal HEVC encoding because the latter is slow.
We are working on a post processing feature where you can convert to required format after recording.

For eg. you will record in H264, and it will be converted after recording to HEVC.
Please be patient till this feature is implemented.

**Comment by ioscars** [comment]
Thanks for the quick response.

**Comment by TheNetStriker** [comment]
I'am getting the same error with my Intel(R) Core(TM) i5-6500 which should have QSV: [Link](https://ark.intel.com/de/products/88184/Intel-Core-i5-6500-Processor-6M-Cache-up-to-3_60-GHz)

Here is the log:

```
ffmpeg version N-89881-g1948b76a1b Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  5.101 / 58.  5.101
  libavdevice    58.  0.101 / 58.  0.101
  libavfilter     7. 11.101 /  7. 11.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, rawvideo, from '\\.\pipe\captura-f23f0405-381b-449b-88e6-8a5b0d206e1b':
  Duration: N/A, start: 0.000000, bitrate: 614400 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1600x1200, 614400 kb/s, 10 tbr, 10 tbn, 10 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
[hevc_qsv @ 000002237d321940] Error initializing an internal MFX session: unsupported (-3)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```
What else could be the problem? Is this maybe a feature that has to be activated somehow?
