### ISSUE TITLE
[Suggestion] Adding text overlays

### ISSUE THREAD

**Issue by szegi** [MathewSachin/Captura#151]
Sometimes i want to add to captured video
some title or info about recording

it would be great if i could set some text overlays in config
and then use them in video

best with options like for keystrokes - font border background
great if i could create few text overlays and just enable disable them
even greater if i could use some defined variables like %date%, %time%, %dayname%

as always this is just a suggestion:)

**Comment by MathewSachin** [comment]
Good suggestion.
I have the option for custom text overlays working in #153.
Still have to add the option for the variable replacements.

One question though, each user might like to have a different format for %date% and %time%.
Any thoughts on how that could be handled?

**Comment by szegi** [comment]
maybe something like this
![image](https://user-images.githubusercontent.com/12111506/33617741-d6438c2e-d9e0-11e7-992b-9b803b8858f4.png)

**Comment by MathewSachin** [comment]
Since there were lots of formats for date and time, currently I have only only implemented replacement for the time elapsed: `%elapsed%`.
This feature is now in `master` branch.

CI build for testing: https://ci.appveyor.com/api/buildjobs/yj7qhex5qlt9oyh7/artifacts/temp%2FCaptura-Portable.zip

**Comment by szegi** [comment]
thanks for me its ok i think
but when you add few overlays it looks little  weird but it works and its what i wanted:)

**Comment by MathewSachin** [comment]
Any suggestions for improving the UI for the custom overlay settings?

**Comment by szegi** [comment]
maybe something like folding properties
so in default you will see only part of text overlay
because now after adding 2 you have to scroll
or overlay list
when you click on one of the overlays
properties will show next to selected layer

**Comment by MathewSachin** [comment]
Did a slight redesign

https://ci.appveyor.com/api/buildjobs/faquld06cjtk465x/artifacts/temp%2FCaptura-Portable.zip

**Comment by szegi** [comment]
its easier to use i think
but every added overlay is named "Overlay"
maybe adding only numbers 1,2,3,4 would be better

thanks for your time and adding this feature:)
