### ISSUE TITLE
console ffmpeg capture file has size 0

### ISSUE THREAD

**Issue by ebloemsma** [MathewSachin/Captura#156]
I used "captura start" and then used "q" to quit the recording after about 10secs. It says a video file was saved. But it has size 0. I tried setting a filename in another directory. All other params where omiited so default. ffmpeg is available in path. The ui captura works fine. 
[capturalist.txt](https://github.com/MathewSachin/Captura/files/1556420/capturalist.txt)

**Comment by MathewSachin** [comment]
Sorry, I am unable to reproduce the issue. If possible provide more details.
`captura start` works fine on my system.

**Comment by ebloemsma** [comment]
Is there a way to give you more Information? Is there a log option?



Von meinem iPhone gesendet

**Comment by ebloemsma** [comment]
I ran the console record in the studio debugger. I found..

1) _syncContex is null, therefore other errors and exceptions are not shown.
![captura error2](https://user-images.githubusercontent.com/34517901/34320226-133e9cbe-e7f5-11e7-8761-5cfe085ab6a8.jpg)

2) recorder is null. Maybe therefore the file is not saved when "q" is entered
![captura error](https://user-images.githubusercontent.com/34517901/34320227-1360a4bc-e7f5-11e7-8d61-d846ea9c064d.jpg)

I don not yet know whats the reason for that.

**Comment by ebloemsma** [comment]
I think I found the cause.

An IndexoutOfBoundsException when checking webcams available.
![captura error3](https://user-images.githubusercontent.com/34517901/34320547-f4bb016c-e7fc-11e7-9396-7b97acfc4514.jpg)
 
The fix is this line.
![captura error4](https://user-images.githubusercontent.com/34517901/34320555-10ac38d2-e7fd-11e7-9c04-39dac7010c99.jpg)

why this not happens with the UI version, i do not know.

**Comment by MathewSachin** [comment]
Nice Job. 👍 
So, webcam capture does not work from command line.
That's because the way it is done here, a preview is drawn on a window, while in console mode there is no such window to draw on so it fails.

Will add that line ASAP.
