### ISSUE TITLE
Screen capture / Video Capture only black

### ISSUE THREAD

**Issue by iSparq** [MathewSachin/Captura#161]
Downloaded the compiled app first and it ran great.  I downloaded the code and ran in Visual Studio 2017 and the screen capture and video captures are all black with no images.  Any ideas what the issue might be?

**Comment by MathewSachin** [comment]
I haven't encountered an issue like that.
Checked with the latest source code and it works fine.

Can you share your system specifications.

**Comment by iSparq** [comment]
Mathew thanks for the reply.
Specs are:
* Windows 10 Home
* Intel i7-8550U CPU, 4 cores, 8 logical processors
* 16G RAM
* Video NVIDIA GeForce MX150

The black screen occurs on all video types (MPEG, AVI, etc.) and Screen Captures (PNG, BMP, etc.)

**Comment by iSparq** [comment]
Solution found and issue resolved.  It appears that Webroot SecureAnywhere sees this as a threat to Identity Protection and blocks the screen capture.  This is resolved (for anyone else with this issue) by allowing Captura in the Identify Protection settings

**Comment by MathewSachin** [comment]
Closing since solved
