### ISSUE TITLE
Add hotkeys to toggle mouse and keyboard overlay while recording

### ISSUE THREAD

**Issue by jtiai** [MathewSachin/Captura#163]
Add options to toggle mouse and keyboard overlay while recording. Specially keyboard toggle would be useful to trace special keys which can't be screen (like shortcuts in applications).

**Comment by MathewSachin** [comment]
Done! Will be available in next release.

**Comment by MathewSachin** [comment]
Mouse click and keyboard overlays can be toggled from the buttons on the interface.

I did not get that you wanted hotkeys for that.

I think there might be a problem though. The hotkey might show up in the video when you will be turning off keyboard overlay.

**Comment by jtiai** [comment]
I think that hotkey for keyboard overlay toggle should be silently ignored. This is just matter of documentation and in my opinion would be at least surprise. Just like all other hotkeys defined in Captura I don't expect them to be seen in keyboard overlay (like stop recording).

Main problem is that when trying to record a tutorial for a program which has both - hotkeys and writable text (source code for example) I would like to avoid tracking source code writing in my video since it doesn't make much of a sense at that point.

For a video it would look a bit strange if I move mouse out of screen to toggle those. Or even worse there is need to popup Captura window to toggle overlays.

**Comment by MathewSachin** [comment]
Ok. I'm working on it.

BTW, I would like to know your preferences on the default hotkeys for mouse and keyboard overlay toggling.

**Comment by jtiai** [comment]
Maybe to be inline with current defaults Alt+F10 and Alt+F11 (Or Shift+F10) and I think they could be off by default.

**Comment by MathewSachin** [comment]
It's still not perfect but please test the latest dev build

https://ci.appveyor.com/api/buildjobs/h01by8fobd5603cu/artifacts/temp%2FCaptura-Portable.zip

**Comment by jtiai** [comment]
Otherwise works perfectly except that when enabling keyboard/mouse modifier keys (ctrl/alt/shift) are recorded upon release.

**Comment by MathewSachin** [comment]
After several trials, it seems that it is not possible to prevent the modifier keys from being recorded due to Captura writing the video in real time.
