### ISSUE TITLE
Cannot record mp4 with multiple screens and width not dividable by 2

### ISSUE THREAD

**Issue by Roemer** [MathewSachin/Captura#165]
Hello
Thanks for your project, I took some inspiration for my own recorder :)
While working on that I found out that ffmpeg/mp4 fails when the screen resolution is not dividable by 2. This can happen if you have multiple screens where one is lower than the other.
To fix this, I use scaling for the videou out like this:
`-vf "scale={img.Width}:-2"`
With that line, it uses the regular width (which is usually dividable by 2) and makes the height dividable by 2 but keeping the aspect ratio. Maybe there should be some more calculation in case that the width is also not dividable by 2.

**Comment by MathewSachin** [comment]
Please try adding this line:
`Region = Region.Even();` 

as the first line of RegionProvider constructor:
https://github.com/MathewSachin/Captura/blob/8f43ed2a932ea7051fc72661cccbe80b5da78fd8/src/Screna/ImageProviders/RegionProvider.cs#L19

Please let me know if it works this way.

**Comment by Roemer** [comment]
That should help.
In my solution, I changed that only ffmpeg will make the width/height even (so that ScreenShots still use the full width/height):
```csharp
var videoOutArgs = $"-vcodec libx264 -crf {_quality} -pix_fmt yuv420p -preset ultrafast -r {_frameRate} -vf \"scale={img.Width.Even()}:{img.Height.Even()}\"";
```
