### ISSUE TITLE
Lagarith codec and region selector suggestion

### ISSUE THREAD

**Issue by pcunite** [MathewSachin/Captura#166]
Excellent video capture program! I use it to make tutorials/info videos using virtual machines. Being able to record the VM guest from the host is important to me. Thank you.

**I have a couple of suggestions:**

- Query the locally installed codecs and allow their use. (I need _Lagarith_ support for example).
- I use the "Region" option to record things. When the recording starts, it would be beneficial to hide the _region selector_ during this time.

How can I donate to you? Your PayPal link does not work. I would like to use PayPal or CC card.

**Comment by MathewSachin** [comment]
- I'll add the region selector hiding feature ASAP.
- As for the locally installed codecs, I think I need to investigate.

Oh, And thank you for your generosity, I've fixed the [PayPal](https://www.paypal.me/MathewSachin) link

**Comment by MathewSachin** [comment]
Option to hide region selector during recording has been implemented.

It will be available in next release.

**Comment by pcunite** [comment]
> As for the locally installed codecs, I think I need to investigate.

Yeah, hopefully not too hard. This [topic](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/codec-query) might help as far as getting them. Don't what you'll need to do to actually use it.

**Comment by MathewSachin** [comment]
Implemented Lagarith codec support for Avi files.

Here are the steps to test it:

1. Download [Test Build](https://ci.appveyor.com/api/buildjobs/iqfvopwa5haptgpo/artifacts/temp%2FCaptura-Portable.zip)
2. Extract Zip and run `Captura.UI.exe`.
3. For video encoder, select `SharpAvi` then `Lagarith`.
4. Start Recording

**Comment by pcunite** [comment]
Hello,
Strange crash on my main system. When I test under a VM, it works very well. See [video](https://vimeo.com/256212763). Let me know how I can help you debug the issue.

Thank you.

**Comment by MathewSachin** [comment]
I'm not sure about the error maybe updating the graphic card drive might help.
I'll further investigate.

**Comment by pcunite** [comment]
Looks like a clue [here](https://github.com/baSSiLL/SharpAvi/wiki/Using-Video-Encoders#creating-video-encoder).

**Comment by pcunite** [comment]
Update:
I found the issue. When I set RGBA (as shown [here](https://upload.wikimedia.org/wikipedia/commons/d/de/Lagarith_config.png)) then [Mpeg4VideoEncoderVcm](https://github.com/baSSiLL/SharpAvi/blob/master/SharpAvi/Codecs/Mpeg4VideoEncoderVcm.cs) will cause an exception.

The reason it worked as Admin was because that was a different user profile and I had not changed the Lagarith defaults.

**Comment by MathewSachin** [comment]
That must be the problem since Captura uses RGB for all purposes.
So, it requires the encoders to expect the same as input.

**Comment by pcunite** [comment]
Okay, I'll test and see if I truly need RGBA (which means RGB32 with active alpha, I [think](https://forum.videohelp.com/threads/370025-Lagarith-s-RGB32-RGBA-Difference))

**Comment by pcunite** [comment]
Another issue: Captura will not record a _playable_ AVI if Lagarith option _Enable Null Frames_ is set.

**Comment by pcunite** [comment]
Testing is going good. I can say that working with the Lagarith codec appears to works well. I don't seem to have a need for _Enable Null Frames_ or _RGBA_ at this time. Doesn't seem to change the look of my output probably because I'm just recording VMware Workstation guests.

**Comment by pcunite** [comment]
I think you can mark this thread as solved. My suggestion would be to read this registry key and verify the settings as shown. If not set, show a dialog box asking the user to change them (or do it for them ~smile)

**HKEY_CURRENT_USER\Software\Lagarith:**
- Mode = RGB
- NullFrames= 2294784

**Comment by MathewSachin** [comment]
I'm not planning of accessing the registry.

I think adding the information to document will be sufficient.
