### ISSUE TITLE
Region Selector will not size itself to 1024x768 pixel windows

### ISSUE THREAD

**Issue by pcunite** [MathewSachin/Captura#167]
Hello,

The _Region Selector_ will **not** size itself to an object with 1024x768 pixels. To illustrate this, I created a program that simulates a Virtual Machine Guest window (what I use Captura for). The _Region Selector_ works great with sizes of 800x600, 1280x720, and so on. But it will **not** conform to 1024x768 resolution.

Watch [video](https://vimeo.com/256259255) for a demonstration of this bug.

**Comment by MathewSachin** [comment]
I'm sorry. I'm unable to reproduce the issue on my system.

May I know you screen size and DPI.

**Comment by pcunite** [comment]
My screen [resolution](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings) is 1920x1200. Under Windows 10, Settings / System / Display / [Custom scaling](https://winaero.com/blog/set-display-custom-scaling-windows-10/), I have it set to 125.

**Comment by MathewSachin** [comment]
I've figured out the problem. It is related to DPI. Would do a fix ASAP.

**Comment by MathewSachin** [comment]
Have done a fix. Please test.

Dev build: https://ci.appveyor.com/api/buildjobs/bgmg3mapn6wh2rs8/artifacts/temp%2FCaptura-Portable.zip

**Comment by pcunite** [comment]
It works!
