### ISSUE TITLE
Command line cannot save video 

### ISSUE THREAD

**Issue by andrewang** [MathewSachin/Captura#171]
Using V6.0 version, through command line captura start --length 10 --cursor --keys --speaker=0, the countdown ends the command line tool to stop, no video output. The start and end buttons in UI can be recorded and saved, and the win10 I use

**Comment by MathewSachin** [comment]
It seems to work fine for the latest development build.

Please test: https://ci.appveyor.com/api/buildjobs/7nccbxne9yhc47c1/artifacts/temp%2FCaptura-Portable.zip

**Comment by MathewSachin** [comment]
Closing since unable to reproduce
