### ISSUE TITLE
Webcam Capture not working

### ISSUE THREAD

**Issue by StoneCut** [MathewSachin/Captura#172]
Webcam Capture is not working for me. Windows 10 64-Bit 1703. Chose "Integrated Camera" but preview windows remains black whereas a recording will show white noise. Other programs such as OneNote can use the webcam. 

This is a built-in device on my Lenovo T540p.
Device managers says it's a "**SunplusIT Integrated Camera**".

Device Path:
_USB\VID_5986&PID_026A&MI_00\6&7AE9AEF&0&0000_

Hardware-IDs:
_USB\VID_5986&PID_026A&REV_0003&MI_00
USB\VID_5986&PID_026A&MI_00__

Running Captura as Administrator makes no difference. Enabling Desktop Duplication API makes no difference.

How can I help debugging?

**Comment by MathewSachin** [comment]
The webcam capture functionality of Captura comes from [ScreenToGif](http://www.screentogif.com/).
Try capturing the webcam with ScreenToGif and let me know if it works.

**Comment by StoneCut** [comment]
Tested capturing with ScreenToGif: Also doesn't work :( Too bad.

Any way to use different method, maybe similar to https://github.com/cesarsouza/screencast-capture ?

**Comment by MathewSachin** [comment]
Cannot use https://github.com/cesarsouza/screencast-capture since it is licensed under GNU license while Captura is under MIT license.

**Comment by StoneCut** [comment]
I understand. Thank you for looking into it!

The only promising webcam C# source code with MIT license I could find was from a dead project on Google Code. Since I can't code nor compile (and the Binary download isn't available anymore) I have no idea if it works: https://code.google.com/archive/p/camcap/

So, I guess I'll have to live without this feature ;)

**Comment by atomal2** [comment]
... the cam-videocapture, in Captura7-6 also ScreenToGif, is available when you use the universal webcam driver installed from Microsoftautoupdate; - Device Manager, the dialogue about updating the driver->search on this PC->choose from the list available->USBvideodevices[information about driver file, in Properties: usbvideo.sys + ksthunk.sys, on my desktop]
- just in vers *Captura501Release* can be seen "live" image using the device manufacturer original drivers/utilities.

**Comment by StoneCut** [comment]
That works great, atomal2! Thank you very much. This should got into the documentation.

**Comment by MathewSachin** [comment]
Added about using the Device Manager to update driver in FAQ.

Thank you @atomal2 and @StoneCut 👍
