### ISSUE TITLE
Unable to resize Captura Region Area

### ISSUE THREAD

**Issue by issamgithub** [MathewSachin/Captura#173]
Hi, I am using Windows 10 and unable to resize the region capture size. And it also randomly move by itself sometimes.

**Comment by MathewSachin** [comment]
I've already done a fix for this.
Would release a new version soon.

Test this development build: https://ci.appveyor.com/api/buildjobs/9auee29pkjy9c018/artifacts/temp%2FCaptura-Portable.zip

**Comment by MathewSachin** [comment]
Please test with the latest v7.0.0

**Comment by MathewSachin** [comment]
Assuming that this issue is fixed in the latest release.
Closing due to no response.
