### ISSUE TITLE
FFmpeg 404s on Windows

### ISSUE THREAD

**Issue by danmindru** [MathewSachin/Captura#174]
Hi there, thanks for the awesome software!

I've just installed v7 & I couldn't download ffmpeg through the UI. It used to work on v6.
Anything I can do to help?

![ffmpeg](https://user-images.githubusercontent.com/1515742/37416926-5af0b6a6-27af-11e8-9755-37464f1cd4de.PNG)

**Comment by MathewSachin** [comment]
I tried with v6 and the same problem is happening.
Seems to be an issue with the FFMpeg server. I'll look into it.

For the time being, if you had already installed FFMpeg in v6, you can set the folder for it at `Configure > FFMpeg > FFMpeg Folder`.
If you relied on automatic download, the folder must most probably be your `My Documents` folder.

**Comment by danmindru** [comment]
Thanks! Got it to work by manually configuring the FFMpeg folder.

LMK if there’s something I can do to help debug.

**Comment by h4aLkon** [comment]
Hello, can confirm, I have the same issue on Windows 10. I just downloaded latest build of FFmpeg for Windows from https://ffmpeg.zeranoe.com/builds/.

**Comment by MathewSachin** [comment]
Did a fix.
Please test latest dev build: https://ci.appveyor.com/api/buildjobs/a8xkft0o4t2hytpu/artifacts/temp%2FCaptura-Portable.zip

**Comment by danmindru** [comment]
Awesome, works on my end.
![ffmpeg](https://user-images.githubusercontent.com/1515742/37645505-5a9684e8-2c27-11e8-964a-aca22390d2d4.png)
