### ISSUE TITLE
Captura gets stuck in less CPU systems

### ISSUE THREAD

**Issue by Sureshkumars** [MathewSachin/Captura#176]
Hi. Is there any minimum system requirement for using Captura ? I tried it in a 1.4 GHz Duo Core, 4GB RAM system. The system gets stuck everytime I do that. Also is there a way to make it run in this configuration ?

**Comment by MathewSachin** [comment]
I have not verified the exact minimum system requirements.

But, on my 2.3 GHz Intel i5 6-GEN, with 8GB DDR4 RAM system, recording 1920x1080 at 10 fps with FFMpeg consumes about 20% CPU and 200MB memory which is fine by me.

I admit that Captura is not optimized in terms of performance as stated in the FAQ.
Currently, there is no workaround for less CPU systems.

**Comment by MathewSachin** [comment]
Added Recommended System Requirements in README and FAQ
