### ISSUE TITLE
No reaction after click on Record/stop button

### ISSUE THREAD

**Issue by MatGermany** [MathewSachin/Captura#179]
Hi, there seems to be another problem: 
Sometimes when I click the record/stop button, Captura 7.01 (Windows 10) does not seem to react. 
Still, when I want to close the program "by force" via right click on the task in the Windows task bar, Captura asks me whether I really want to close the program - even though a recording is running. (I do not get any other signal that a recording is running, though.) 
And when I click on the record/stop button again, there is again no reaction - and no file is saved. 
Kind regards, Mat

**Comment by MathewSachin** [comment]
What are your system's CPU and RAM specifications?

**Comment by MatGermany** [comment]
Intel Pentium CPU N3710 @ 1.60 GHz, 
4GB RAM

**Comment by MathewSachin** [comment]
This problem is happening due to higher CPU requirement of Captura. I have not found the exact minimum but almost 2 GHz might be required.

**Comment by MatGermany** [comment]
Ok, thanks.

**Comment by MathewSachin** [comment]
Added Recommended System Requirements in README and FAQ
