### ISSUE TITLE
mouse cursor moves very slowly when I record with command-line

### ISSUE THREAD

**Issue by code5381** [MathewSachin/Captura#180]
Hi, 

First of all, Thank you for your fantastic project. :)

When I start with command-line, mouse cursor moves very slowly, but CPU and Memory are stable. 

I tested in 'Windows 10 Pro N' with 'Captura 6.0.0.0.' 

Is there something options what I missed? 

Thanks in advanced.

Kevin.

**Comment by MathewSachin** [comment]
Thank you for reporting the issue.
I have confirmed that it is happening.

I'm currently not sure of the cause, but will try to solve ASAP.

**Comment by andytheengineerguy** [comment]
Hi guys, I am also experiencing this issue. Have experimented with the following with no difference:
- Varying frame rates
- Varying video/audio quality settings
- 64bit-only builds
- including/excluding streams (video audio etc)
- all different encoders

I also tried implementing different ways to capture key presses post start command (on suspicion it was somehow blocking), but no difference either.

however, if I bring up the Task Manager while recording... the cursor returns to smooth motion. Strange indeed!

Perhaps an async/threading issue?

Anyway, hope that helps a bit.

**Comment by andytheengineerguy** [comment]
Hey guys, any progress on this? 

I notice the CLI version uses "StartRecording" function from MainViewModel class just like the working version

Perhaps this problem originates from Fake/Mocked module used (in Program.cs before call to StartRecording)? I'm pretty new to using services & dependency injection, but if you have any thoughts @MathewSachin I'd be happy to follow this up for you and try and solve it

**Comment by MathewSachin** [comment]
You may be right in that the problem might be with the Fakes.
I suppose it could be with `WebcamProvider` since it is called for every frame.

But, on testing by removing Webcam overlay from code, the problem still exists.

So, we are still not sure why this issue is happening, Any help would be appreciated. 👍

**Comment by MathewSachin** [comment]
Ran `git bisect`: https://github.com/MathewSachin/Captura/commit/7ae178099ab7f64c31f8be587661296e0950c9f6

This commit was where the problem began. Would look into it further.

**Comment by MathewSachin** [comment]
Finally found the problem, it is happening due to mouse clicks and keystroke capture.

In earlier builds enabling this feature will cause hanging of mouse pointer otherwise not.

**Comment by MathewSachin** [comment]
Did a fix, please test with the latest dev build.
