### ISSUE TITLE
Different mouse overlays for right and middle clicks

### ISSUE THREAD

**Issue by cloo** [MathewSachin/Captura#183]
Would be nice to have those for making video tutorials clearer.

**Comment by MathewSachin** [comment]
I can't think of a good design. Here's a build of what I've implemented: https://ci.appveyor.com/api/buildjobs/u1rw8blnlkm8vuxp/artifacts/temp%2FCaptura-Portable.zip

Suggestions are welcome

**Comment by cloo** [comment]
Nice approach! The visuals look somewhat weird, but in general I like it. 
In other apps it is usually solved either by depicting the mouse (a bit intrusive imho), 
either using two different colours: e.g. yellow for left click, blue for right. This would be my favourite, I guess.

**Comment by MathewSachin** [comment]
So, I guess we can go for the color approach. Would come up with it ASAP.

**Comment by MathewSachin** [comment]
Here's the build for testing: https://ci.appveyor.com/api/buildjobs/o5itknb73dgldibm/artifacts/temp%2FCaptura-Portable.zip

Colors can be changed in `Configure | Overlays | Mouse Clicks`

**Comment by MathewSachin** [comment]
#187 Merged. This feature is now in master branch.
Would be available in next release.
