### ISSUE TITLE
See mouse/keyboard overlays without recording

### ISSUE THREAD

**Issue by cloo** [MathewSachin/Captura#184]
Would be nice to tune their appearance without making test recordings. 
Also, if such function present, I'd probably use it as live presentation helper.

**Comment by MathewSachin** [comment]
As per my knowledge, mouse/keyboard overlays cannot be shown on screen without recording.
But, they can be shown in a preview window. I'm working on it. It is in Alpha stage though.

Here's the build for testing: https://ci.appveyor.com/api/buildjobs/v0aql09n24nducn3/artifacts/temp%2FCaptura-Portable.zip

You have to select `Preview` as video output type.

**Comment by MathewSachin** [comment]
Merged #186.
This feature is now in master branch and will be available in next release.
