### ISSUE TITLE
Recording Webcam via Command-line version

### ISSUE THREAD

**Issue by andytheengineerguy** [MathewSachin/Captura#191]
I noticed that in the fake module declaration for the CLI, "FakeWebCamProvider" is used in place of "WebCamProvider"

Unfortunately I'm new to using Windows services so am struggling to dive much further - any suggestions on how to include webcam recordings using the CLI version? or plans to include this in the Captura roadmap? Happy to spend some time on this if not

**Comment by MathewSachin** [comment]
The `WebcamProvider` requires a window handle to draw live preview, but the console version doesn't have one. Not sure, but, maybe creating a new Windows Form and using its handle along with WebcamProvider may work.

`new Form().Handle`

**Comment by MathewSachin** [comment]
Customizing all these options from command-line would lead to too many options.
I would try to implement using the settings file.
