### ISSUE TITLE
Use custom settings with Captura.Console

### ISSUE THREAD

**Issue by andytheengineerguy** [MathewSachin/Captura#193]
On my system, Captura saves settings in ...\AppData\Roaming\Captura. Any advice on how to provide this to Captura.Console? 

My goal is to customise settings using the Captura UI, then use in them in Captura.Console

In program.cs in Captura.Console, I've tried 

           ServiceProvider.SettingsDir = "C:/Users/razerblade/AppData/Roaming/Captura";
           var settings = ServiceProvider.Get<Settings>();
           settings.Load();

But I'm missing something as the Default settings are still used for the command-line recordings.

Any ideas? 

Cheers,
Andy

**Comment by MathewSachin** [comment]
I think the above code should work. You don't have to specify `SettingsDir` for the default directory.

Also, make sure that you call `ServiceProvider.Get<Settings>()` before `ServiceProvider.Get<MainViewModel>()`.

Do note that overlay settings have been explicity reset and the options specifiable through command-line parameters have been given default values.
e.g. regardless of what is specified in settings, mouse click capture will be off by default.

**Comment by andytheengineerguy** [comment]
Ahhh you're right, it is working!! I just didn't realise it was being overwritten by my lack of command line arguments.

i.e as soon as I included --webcam 0 and --keys, my custom settings were visible. 

Cheers Mathew :)

**Comment by MathewSachin** [comment]
@andytheengineerguy You might want to check the latest commit.

Overlay customizations from UI are now used in Console version.

https://github.com/MathewSachin/Captura/commit/cfaada5100cd2a4a2e71a9e7e5bc37a4a217f673

**Comment by andytheengineerguy** [comment]
awesome @MathewSachin! legend :) this is really great to prototype with now. thanks for being so active with developing this
