### ISSUE TITLE
Can't start recording

### ISSUE THREAD

**Issue by kalot** [MathewSachin/Captura#194]
I'm using windows. Captura worked in January. 

1. Here I updated Captura. I can't start recording, after pressing record, it just hangs, doesn't do anything. I checked in the task manager, there is a .Net optimization service running, but nothing happens after the service is done.

2. Tried it on a different windows pc, This machine has the version from January.  It freezes the whole system after 5 minutes of recording.

**Comment by MathewSachin** [comment]
Need more information.

Which version of Captura did you test?
Try with the latest v7.0.1. If it is not working, try deleting `%AppData%/Captura` folder.

If still not working, provide the following details:
- Windows OS Version
- .Net Framework Version
- RAM
- CPU
- Settings used like Frame Rate, Video Source, etc.

**Comment by MathewSachin** [comment]
Closing since no response
