### ISSUE TITLE
How do I add subtitles in the preview window?

### ISSUE THREAD

**Issue by DuenZeng** [MathewSachin/Captura#195]
How do I add subtitles in the preview window?

**Comment by MathewSachin** [comment]
Subtitles are not supported.

**Comment by DuenZeng** [comment]
Can it be done?

**Comment by MathewSachin** [comment]
I think this is outside the scope of Captura. It would be better to use a video editing program for this purpose.

**Comment by DuenZeng** [comment]
OK, Thanks
