### ISSUE TITLE
Request to introduce - "Minimize on Startup" for Captura.

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#196]
Hello!

Using the Latest version of your program on my Win 7 Ultimate notebook PC environment.
Isn't it possible to receive a 'tray-minimized' Captura on program access ?
At present, one has to click on the down arrows exclusively to make it minimized to the system tray !

Those who wish to configure the capture options every single time - can certainly do so by fiddling with the tray icon !

So why not introduce such an option for its interface?

Thank you.

**Comment by saurabhdua82** [comment]
Clicking 'X' also leaves the program EXIT altogether !
Please also introduce an option to >> Tray-minimize on clicking 'X' on its interface.

**Comment by MathewSachin** [comment]
Two new options have been added in `Configure | Options`.

Please test dev build: https://ci.appveyor.com/api/buildjobs/trg1895cv81oridm/artifacts/temp%2FCaptura-Portable.zip
