### ISSUE TITLE
Request towards 'Mouse pointer' overlay in Captura.

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#197]
Hello Sachin !

'Mouse click' overlay is all good ! ...but it would be even better to also introduce - "Mouse pointer" overlay to the Captura !

Let the yellow ellipse follow the mouse pointer every single time, & on each occasion !

The demonstrations would be far impressive by this approach & the end recipients would FOCUS better on the intended projection.

Thank you.

**Comment by MathewSachin** [comment]
Added Mouse Pointer Overlay section in `Configure | Overlays`.

Please test dev build: https://ci.appveyor.com/api/buildjobs/3orf52jt80sljbqa/artifacts/temp%2FCaptura-Portable.zip
