### ISSUE TITLE
captura not recording > error message

### ISSUE THREAD

**Issue by angypop** [MathewSachin/Captura#198]
hello, first time using captura, I` don`t know exactly what are the best settings. 
I did set my screen to DISPLAY1 
FFMpeg to Mp4 (h264 etc) 

Audio
my speakers

I downloaded the FFMpeg pack in my documents and selected the source in the Configure page. 
then I started recording, it seems to record but when I try to open the file, it tells me the video can`t re read because of some error. 

The one I get is the following: 

System.Exception:An Error Occurred with FFMpeg, Exit code: 1 at Captura.Models.FFMpegWriter.WriteFrame(IBitmapFrameFrame) at Screen.Recorder.DoWrite()

Any idea why it is doing this and how I can fix it? 

Thanks

**Comment by MathewSachin** [comment]
Please provide FFMpeg Log. Go to `Options | FFMpeg | FFMpeg Log`

**Comment by angypop** [comment]
Hello,

for the log file, I clic on the copy to clipboard button, but when I go
into the system32 folder looking for the clip.exe file to run it, it
appears and disapperas immediately so, I`m not sure how to visualize what
is in the log file and send it to you. any solutions for that?

**Comment by MathewSachin** [comment]
After clicking on Copy to Clipboard, Paste here in a Message with `Ctrl + V`.

**Comment by angypop** [comment]
Hi Mathew,

the crtl +V doesn`t work. It pastes nothing, nut I could grab a screenshot
of the error and clipboard which I`m sending here attached. Keep me posted
about a possible solution.

Thanks

**Comment by MathewSachin** [comment]
I could not find the attached image. Please check.

**Comment by angypop** [comment]
I m resending it here

**Comment by MathewSachin** [comment]
Still not received, instead of attaching in email, try attaching on this GitHub issue page.

**Comment by angypop** [comment]
![error_captura](https://user-images.githubusercontent.com/39278826/40050372-90e2f66c-5837-11e8-9d95-f16f4e9f262e.jpg)

**Comment by angypop** [comment]
just did it hope now it will work

**Comment by MathewSachin** [comment]
Received successfully,

It seems like you are using h264 NVENC encoder. It is in Alpha plase and may only work with high-end NVIDIA GPUs.

For normal purposes use the `MP4 (x264 | AAC)` encoder.

**Comment by MathewSachin** [comment]
Looking at your GPU model in the other thread, I suppose NVENC must be supported on your system.
Must be an issue with Captura.
I'll try some fixes.

**Comment by angypop** [comment]
ok thanks,.
I tested the mp4 x 264 aac, I have 2 monitors.

If I set screen display 2, it registers video and audio of the first
screen; if I set screen and display 2, it only registers the audio of the
youtube video I`m running on my second screen.
Is that normal?

**Comment by angypop** [comment]
and other weird thing: once I finish recording and hit the stop button, the
software seems not to respond anymore, if I want to close it I have to
force it from the task manager.

**Comment by angypop** [comment]
hello again Matt,

I was trying to capture a 1h video, but I got this error after 3 min. the
error message said insufficient system resources. What does that mean
exactly? Cause I have enough space on my disk...


ffmpeg version N-91024-g293a6e8332 Copyright (c) 2000-2018 the FFmpeg
developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2
--enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg
--enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr
--enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack
--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2
--enable-libzimg --enable-lzma --enable-zlib --enable-gmp
--enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc
--enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom
--enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid
--enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2
--enable-avisynth
  libavutil      56. 18.100 / 56. 18.100
  libavcodec     58. 19.101 / 58. 19.101
  libavformat    58. 13.102 / 58. 13.102
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 21.100 /  7. 21.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, rawvideo, from
'\\.\pipe\captura-e50d4cad-cc08-4290-bd6f-810c1125c199':
  Duration: N/A, start: 0.000000, bitrate: 7962624 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 3840x2160,
7962624 kb/s, 30 tbr, 30 tbn, 30 tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, s16le, from
'\\.\pipe\captura-fe6e70ec-a612-4393-94b5-753d8f612b82':
  Duration: N/A, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 000001133164e2c0] using cpu capabilities: MMX2 SSE2Fast SSSE3
SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000001133164e2c0] profile High 4:4:4 Predictive, level 5.1,
4:2:0 8-bit
[libx264 @ 000001133164e2c0] 264 - core 155 r2901 7d0ff22 - H.264/MPEG-4
AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html -
options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0
mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11
fast_pskip=0 chroma_qp_offset=0 threads=24 lookahead_threads=4
sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0
constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0
intra_refresh=0 rc=cqp mbtree=0 qp=0
[s16le @ 00000113315ff240] Thread message queue blocking; consider raising
the thread_queue_size option (current value: 8)
Output #0, mp4, to
'C:\Users\angypop\Documents\Captura\2018-05-16-18-11-06.mp4':
  Metadata:
    encoder         : Lavf58.13.102
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661),
yuv420p(progressive), 3840x2160, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.19.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo,
fltp, 512 kb/s
    Metadata:
      encoder         : Lavc58.19.101 aac
[rawvideo @ 00000113315eba00] Thread message queue blocking; consider
raising the thread_queue_size option (current value: 8)
video:231689kB audio:5294kB subtitle:0kB other streams:0kB global
headers:0kB muxing overhead: 0.065234%
[libx264 @ 000001133164e2c0] frame I:23    Avg QP: 0.00  size:475403
[libx264 @ 000001133164e2c0] frame P:5557  Avg QP: 0.00  size: 40726
[libx264 @ 000001133164e2c0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 000001133164e2c0] mb P  I16..4: 78.0%  0.0%  0.0%  P16..4:
0.2%  0.0%  0.0%  0.0%  0.0%    skip:21.8%
[libx264 @ 000001133164e2c0] coded y,uvDC,uvAC intra: 0.8% 2.5% 2.4% inter:
0.6% 0.9% 0.9%
[libx264 @ 000001133164e2c0] i16 v,h,dc,p: 100%  0%  0%  0%
[libx264 @ 000001133164e2c0] i8c dc,h,v,p: 94%  2%  5%  0%
[libx264 @ 000001133164e2c0] kb/s:10204.26
[aac @ 0000011331652fc0] Qavg: 65505.344
