### ISSUE TITLE
screenshot not working

### ISSUE THREAD

**Issue by angypop** [MathewSachin/Captura#199]
Also, I tried the screenshot feature and it grabs black screenshot and it inhibits the usual screengrab tools, which doesn`t allow me to use the classic crtl +V in Photoshop either. So the software doesn`t work and having it installed I can`t take any screenshot in any other way. 

Any solution?

**Comment by MathewSachin** [comment]
You can change the ScreenShot hotkey at `Configure | Hokeys`, then other programs will not be inhibited.

There's an option for ScreenShot Save Location. You can set it to Clipboard.

Regarding the black screenshots, which version of Windows do you have? Also, which of the following screenshots work:
- Full Screen
- Specific Screen
- Window
- Region

**Comment by angypop** [comment]
Hi,

thanks. now the photoshop option works again and when I hit screenshot
desktop (alt+2 the new shortcut) it grabs what I have on the desktop (the
whole thing on both screens).
The only othe option is screenshot  and it goes black every time, but I
don`t have all those other options in the save menu: I only have disk,
imgur and clipboard.

**Comment by angypop** [comment]
Hello,

for the log file, I clic on the copy to clipboard button, but when I go
into the system32 folder looking for the clip.exe file to run it, it
appears and disapperas immediately so, I`m not sure how to visualize what
is in the log file and send it to you. any solutions for that?

**Comment by MathewSachin** [comment]
I was not specifying Screenshot options.
The options: Screen, Region, etc. are video sources, first dropdown from top-left.

**Comment by angypop** [comment]
oh I see,
I gave it a try and:

screen > works OK
region > works OK
windows > it only grabs my toolbar is that normal?
Desktop duplication > goes black

**Comment by MathewSachin** [comment]
Window can be customized from the second dropdown.

Regarding Desktop Duplication, which version of Windows do you have and also do you have graphic cards, single or multiple?

**Comment by angypop** [comment]
ok, got it.
I`m using windows 10 with a single graphic card: MSI GeForce GTX 1080 SEA
HAWK X

**Comment by MathewSachin** [comment]
Please try both running Captura with and without GPU and try if Desktop Duplication works in any case.

**Comment by MathewSachin** [comment]
Desktop Duplication now captures ScreenShot in the same way as Screen, so this issue should not occur in future releases. While there is a known issue regarding capturing with Desktop Duplication failing on devices with hybrid graphics when Captura is run on the dedicated graphic card.
