### ISSUE TITLE
Help select the one appropriate for Desktop shortcut.

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#200]
Hello Sachin !

Thanks for heeding to my last two posts.
As per your suggestion, Iam now using the 'developer build' in its portable format.

Please refer to the enclosed pictorial description & help me choose amongst the two -the one appropriate for creating a desktop shortcut ?

Should I create a desktop shortcut out of plain - 'Captura' application OR "Captura.UI" ??

Inputs will be sincerely appreciated.

Thank you.

![image](https://user-images.githubusercontent.com/23373249/40037291-38280402-582a-11e8-8c44-be491341c29f.png)

**Comment by MathewSachin** [comment]
Make shortcut for `captura.ui`
