### ISSUE TITLE
Hotkeys not working in developer release

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#201]
Hello Sachin !

The developer release is configured for - 'minimize to system-tray' on application launch.
Alt+F9 isn't triggering a recording sequence for the same !?

Its only when you double-click on the system tray icon to access the interface, & then 'x' it to minimize to system-tray -  Alt+F9 start getting recognized at last !

Please probe further at your end & suggest further ?

Thanks for your patience.

**Comment by MathewSachin** [comment]
I've confirmed that none of the hotkeys work in this case, Will try to fix ASAP.

**Comment by saurabhdua82** [comment]
Hi Sachin !

Are there any 'updates' over the reported issue ?

Secondly, if I decide to 'do away' with the portable developer release for the time being & wish to install the stable version via regular installer (.exe) , what all cleaning is required at my end to ensure an error-free operation of your stable release ?

Is a clean-up tool available to scrub the profile entries of unstable developer release ??

Inputs will be appreciated.
Thanks.

**Comment by MathewSachin** [comment]
I've been unable to find a solution for this issue as of now.

No, there is currently no clean-up tool available.
If the stable version does not work, try deleting `%AppData%/Captura` folder.

**Comment by MathewSachin** [comment]
Fixed.

Please test dev build: https://ci.appveyor.com/api/buildjobs/6va4c1c95nj9uc9w/artifacts/temp%2FCaptura-Portable.zip
