### ISSUE TITLE
Request to introduce an OK button for FFMpeg download screen.

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#202]
Hi Sachin !

Please refer to the enclosed pictorial representation & mull over its implementation towards the ongoing development of Captura.

Thanks.

![image](https://user-images.githubusercontent.com/23373249/40472790-1332297c-5f58-11e8-825c-8422b9565e89.png)

**Comment by saurabhdua82** [comment]
People tend to realize only at a later stage that an 'X' needs to pressed to get rid of this window !
An OK button would suggest better over affirmative confirmation / completion.
You may introduce >> 'Next' to revert to the main window or make it minimized to system-tray !

End users mustn't keep staring 'blankly' on this screen & must be prompted to proceed ahead & Play with Captura ! :-)

Thanks.

**Comment by MathewSachin** [comment]
After download, the download button changes to `Finish`.
Also, progress is shown in the Taskbar.

Please test: https://ci.appveyor.com/api/buildjobs/yi10ah4nly5igvlb/artifacts/temp%2FCaptura-Portable.zip
