### ISSUE TITLE
Integrate Drawing Canvas with Screenshot

### ISSUE THREAD

**Issue by RandolfEbelt** [MathewSachin/Captura#203]
Hi!

I think it would be very useful to integrate the most recent screenshot with the drawing canvas, as the most common usecase is to annotate a screenshot.

**Comment by MathewSachin** [comment]
I'm sorry but the drawing canvas is still not ready for image annotation. Might consider this in the future.

**Comment by MathewSachin** [comment]
Working on #211

**Comment by MathewSachin** [comment]
Done!
