### ISSUE TITLE
no option to record audio from webcam

### ISSUE THREAD

**Issue by pj6** [MathewSachin/Captura#207]
My webcam records audio, but Captura doesn't see it as an audio recording device.

**Comment by MathewSachin** [comment]
Did you check both the Recording devices and Speakers list under Audio section on Main tab.

If your device doesn't show up, it might be that the BASS audio library doesn't support your device.

Also, try updating the drivers for your device and let me know of any softwares with which you can record from it.

**Comment by MathewSachin** [comment]
Sorry, closed by mistake. Reopening.

**Comment by pj6** [comment]
Actually I just discovered the issue. Captura checks for "bass.dll", "bassmix.dll", which are not available. I made a second project and installed the ManagedBass and ManagedBass.Mix nuget packages and discovered the same issue. Where are the dlls?

**Comment by MathewSachin** [comment]
Links for downloading bass.dll and bassmix.dll are given [here](https://mathewsachin.github.io/Captura/build).

Alternatively, you can use Cake build to restore it.

Open `powershell` in Captura folder and run:

```
./build.ps1
```

**Comment by pj6** [comment]
Yep that did it - sorry, guess this was a case of not reading the docs more thoroughly. NuGet's spoiled me into expecting everything just works out of the box. You can delete this issue, though I think it may be a good idea to build feedback into Captura to notify new users about building bass.dll/bass.mix.dll with a popup.

**Comment by MathewSachin** [comment]
Fine. Will add a message when bass or bassmix is not present.
