### ISSUE TITLE
Feature Request / Adding function buttons to Region Selector

### ISSUE THREAD

**Issue by Mush-r00m** [MathewSachin/Captura#215]
Hello, Would it be possible to add function buttons to the Region selector?  Screenshot, Start/stop, Pause & recording duration.  Would be useful when having the main program minimized.
Example photo:
https://imgur.com/wneyIZa

Thank you for this amazing open-source software :)

**Comment by MathewSachin** [comment]
Sure. Nice Idea. Will implement ASAP.

**Comment by MathewSachin** [comment]
Implemented! Please test: https://ci.appveyor.com/api/buildjobs/lm67wnmstellbyjy/artifacts/temp%2FCaptura-Portable.zip
