### ISSUE TITLE
Audio and video synchronization and real-time audio problems

### ISSUE THREAD

**Issue by DuenZeng** [MathewSachin/Captura#216]
I find that the audio and video are a little out of sync. Is there any way to play live audio?

**Comment by MathewSachin** [comment]
I'll try adjusting the buffer sizes but can't guarantee any improvement.

Pull requests are welcome if you are able to do some improvements.

**Comment by DuenZeng** [comment]
OK,Thanks.
Is there any way to play the real-time audio?

**Comment by MathewSachin** [comment]
I'm not sure what you mean by real-time audio. Do you mean speaker output of your system?

**Comment by DuenZeng** [comment]
Yes,The sound collected by the microphone is played in real time on the speaker.

**Comment by MathewSachin** [comment]
No, Captura does not support this and it seems outside the scope of this project.

**Comment by DuenZeng** [comment]
The project has actually implemented this, except that the code has set the volume to zero；
Bass.ChannelSetAttribute(_mixer, ChannelAttribute.Volume, 0);
