### ISSUE TITLE
System.IO.IOException: Insufficient system resources exist to complete the requested service.

### ISSUE THREAD

**Issue by badon** [MathewSachin/Captura#222]
Another user experienced this bug, and mentioned it in the context of a probably-unrelated bug report:

https://github.com/MathewSachin/Captura/issues/198#issuecomment-389592025

> hello again Matt,
> 
> I was trying to capture a 1h video, but I got this error after 3 min. the
> error message said insufficient system resources. What does that mean
> exactly? Cause I have enough space on my disk...

And the developer response:

https://github.com/MathewSachin/Captura/issues/198#issuecomment-389662858

> I suppose the problem might be with buffer size.
> I have tested with resolutions only upto 1920x1080.
> 
> I suppose the issue of Captura not responding or video being blank might be related to this.
> 
> Sorry, I currently don't have a Screen with such high resolutions, so might take almost a month before I could do anything regarding this.

I have a similar "Insufficient system resources" error in both portable versions of 7.0.1 and 8.0.0-beta1 when recording a very small Google Chrome window, so that hints the problem isn't screen size. The error appears to be triggered the first time I click a link in Google Chrome. If I let it sit idle, Captura doesn't give the error (tested for less than 1 minute). I have pasted a text version of the error window message below, after copying it with the help of Textify. It might be a good idea to make the error window messages selectable and so they can be copied and pasted in a bug report. Also, "Occurred" has 2 R's :)

    Insufficient system resources exist to complete the requested service.
    
    An Error Occured
    
    System.IO.IOException: Insufficient system resources exist to complete the requested service.
    
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
       at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
       at System.IO.Pipes.PipeStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
       at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
       at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
       at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
       at Captura.Models.FFMpegWriter.WriteFrame(IBitmapFrame Frame)
       at Screna.Recorder.DoWrite()

FFMPEG log from Configure --> FFMpeg (Note "FFMpeg" should be all-capitalized):

    ffmpeg version N-91314-gbd47cca6a7 Copyright (c) 2000-2018 the FFmpeg developers
      built with gcc 7.3.0 (GCC)
      configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
      libavutil      56. 18.102 / 56. 18.102
      libavcodec     58. 20.102 / 58. 20.102
      libavformat    58. 17.100 / 58. 17.100
      libavdevice    58.  4.101 / 58.  4.101
      libavfilter     7. 25.100 /  7. 25.100
      libswscale      5.  2.100 /  5.  2.100
      libswresample   3.  2.100 /  3.  2.100
      libpostproc    55.  2.100 / 55.  2.100
    Input #0, rawvideo, from '\\.\pipe\captura-64cade93-3694-4e89-a5a2-e758ac274b52':
      Duration: N/A, start: 0.000000, bitrate: 180403 kb/s
        Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 810x696, 180403 kb/s, 10 tbr, 10 tbn, 10 tbc
    Stream mapping:
      Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
    Press [q] to stop, [?] for help
    [libx264 @ 0076e380] using cpu capabilities: MMX2 SSE2 SSE3 Cache64
    [libx264 @ 0076e380] profile Constrained Baseline, level 3.1
    [libx264 @ 0076e380] 264 - core 155 r2901 7d0ff22 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=10 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=15.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
    Output #0, mp4, to 'X:\files2\Captura v7.0.1 Captura-Portable\2018-06-17-22-30-27.mp4':
      Metadata:
        encoder         : Lavf58.17.100
        Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 810x696, q=-1--1, 10 fps, 10240 tbn, 10 tbc
        Metadata:
          encoder         : Lavc58.20.102 libx264
        Side data:
          cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    video:861kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.207579%
    [libx264 @ 0076e380] frame I:2     Avg QP: 6.00  size:159724
    [libx264 @ 0076e380] frame P:250   Avg QP: 1.32  size:  2246
    [libx264 @ 0076e380] mb I  I16..4: 100.0%  0.0%  0.0%
    [libx264 @ 0076e380] mb P  I16..4:  0.2%  0.0%  0.0%  P16..4: 16.5%  0.0%  0.0%  0.0%  0.0%    skip:83.3%
    [libx264 @ 0076e380] coded y,uvDC,uvAC intra: 52.7% 42.3% 40.1% inter: 6.1% 1.1% 1.0%
    [libx264 @ 0076e380] i16 v,h,dc,p: 42% 43%  5% 11%
    [libx264 @ 0076e380] i8c dc,h,v,p: 52% 32% 13%  3%
    [libx264 @ 0076e380] kb/s:279.68

Tested on: 

* Windows 7 Ultimate
* Samsung Q1UP 
* Intel Core Solo 1.33 GHz 32 bit CPU 
*  2 GB RAM
* Intel 945 Express GMA 950 video
* 1280 x 1024 external display (1024 x 600 native display)

**Comment by MathewSachin** [comment]
- Corrected occurred spelling. Thank You! 👍 
- I found that `FFmpeg` is spelled with only the Fs capital from the website. Did that too.
- I have implemented an Exception Dialog which allows to copy exception information. Will be done till next release.

Recorded for atleast 20 min each in Screen, Window and Region modes and could not reproduce the issue on my system.

I suppose it is due to Captura requiring more system resources. Your system specifications are lower than those recommended in README. I'm sorry Captura is not very efficient in making the most out of system resources.

My system specifications:
- Windows 10
- Intel i5 2.4 GHz 64 bit CPU
- 8 GB RAM
- 1920 x 1080 display (no external display)
- AMD Radeon R5 M330 Hybrid graphics

**Comment by MathewSachin** [comment]
One more thing, please try using SharpAvi instead of FFmpeg from the drop-down and let me know if it works.

**Comment by badon** [comment]
There's no README file in the portable distributions I downloaded.

The page I loaded that resulted in the error starts with this one:

https://www.humblebundle.com/

And then I click through to this one:

https://www.humblebundle.com/games/daedalic-2018-bundle

That page pins my CPU at 100% load all by itself. SharpAVI worked! CPU was 100% as expected, and RAM was between 91% and 94%. With FFmpeg, RAM was only at 68% when it crashed. So, I think it's likely this is an actual bug, and not really a system resources issue. While writing this, I just tested clicking on different links that don't have high CPU load, and ALL of them cause Captura to crash. It doesn't matter what I click on, and it doesn't matter what site I'm on. At some point after a new page begins to load, Captura crashes. The video is recorded successfully until Captura crashes.

Incidentally, I'm trying to use Captura to demonstrate bugs in Humble Bundle's site. I do a lot of bug reporting:

https://www.mediawiki.org/wiki/User:Badon

**Comment by MathewSachin** [comment]
- The README file is here on GitHub, I will make sure to include it in future releases.
- SharpAvi requires lesser CPU power than FFmpeg. That may be why it worked on your system.

I still suppose yours is a system resource issue cause, opening the website: https://www.humblebundle.com/games/daedalic-2018-bundle in Chrome on my system has an overall CPU usage of only 20% which reduces to 10% after it is fully loaded.
SharpAvi working at 100% CPU usage is not a good sign and may result in similar crash at some point.

Recommended CPU for Captura is 2 GHz. You may use SharpAvi or switch to another software because I'm currently unable to improve the performance of Captura.

This site can help you find alternatives: https://alternativeto.net/software/captura/

**Comment by badon** [comment]
I tried increasing the CPU and IO priority of ffmpeg.exe to High, and CPU priority of Captura.UI.exe to Above Normal. That, and obvious things like closing unnecessary programs seems to have improved Captura's run time before crash with FFmpeg. I will use SharpAvi as a workaround, and I can convert to MPEG with another "offline" non-time-critical application.

Maybe it's possible to automatically raise the priority of ffmpeg.exe?

Thanks!
