### ISSUE TITLE
[Suggestion] Add feature for adding black bars to videos for censoring content

### ISSUE THREAD

**Issue by TheNetStriker** [MathewSachin/Captura#223]
It would be very nice to be able to define multiple regions before recording that are not recorded because of the new data protection act. Would such a feature be possible?

**Comment by MathewSachin** [comment]
I suppose this can be implemented as multiple overlays like the text and image overlays with options for background colour, size and position.

**Comment by MathewSachin** [comment]
Have you seen that Drawing support has been implemented in Region Selector.

You can select Pencil, increase size and draw over areas to hide.

Please test: https://ci.appveyor.com/api/buildjobs/aje588rk1bcox9g3/artifacts/temp%2FCaptura-Portable.zip

**Comment by TheNetStriker** [comment]
Thanks for the hint. I'm searching for something like that, but the problem is that the pencil drawing disappears when switching back to mouse mode. The best option would be that I could specify some areas that should not be recorded. These areas should then be visible to me while recording but should appear black on the video. Would something like this be possible?

**Comment by MathewSachin** [comment]
Then we'll have to go with overlays but positioning them in overlay window will not be intuitive.

**Comment by MathewSachin** [comment]
Implemented as Overlay. Working on #225.

Can be configured by going to `Config | Overlays | Censor`.

Please test dev build: https://ci.appveyor.com/api/buildjobs/sy1861ss6uap0s6i/artifacts/temp%2FCaptura-Portable.zip

**Comment by TheNetStriker** [comment]
Thanks for implementing this. Seams to work just fine.
