### ISSUE TITLE
On version 7.0.1 in region there is no record button no pencil why ? Source is version 6.0.0 ?

### ISSUE THREAD

**Issue by chocolade1972** [MathewSachin/Captura#244]
I went to this site: https://github.com/MathewSachin/Captura/releases/tag/v7.0.1

I downloaded both the zip and setup: Captura-Portable.zip and Captura-Setup.exe in both when running the program and selecting Region instead Screen there is no record button on the Region window and not pencil. Why is that ?

Another problem is I download from the same link above the source: Source code (zip) 
When running from visual studio the source same problem with the region but when I click on About I see version 6.0.0 maybe you forgot to change the version number ? In the both Captura-Portable.zip and Captura-Setup.exe it say version 7.0.1

Anyway the Region part is not working as before.

**Comment by MathewSachin** [comment]
v7.0.1 does not have the drawing tools in region selector because it is an older version.

The version in the source code is not changed manually.
The build script handles updation of version number before release. You might want to take a look at `build.ps1`.
