### ISSUE TITLE
Problem with languages

### ISSUE THREAD

**Issue by hjy1998** [MathewSachin/Captura#245]
Hello, sorry for disturbing. I'd found the Chinese language translator in the contribution section. But when I download the application, there is no any Chinese language for me to change. So, I would like to contribute to this project with Chinese language translating. I'm both good at English and Chinese translating. It is for my assignment too. Thank you for your time.

**Comment by MathewSachin** [comment]
I'm sorry the Chinese translation is done already but not released yet.

**Comment by MathewSachin** [comment]
Place this file in the languages folder of a build

https://github.com/MathewSachin/Captura/blob/master/src/Captura.Loc/Languages/zh-CN.json

**Comment by MathewSachin** [comment]
Thank you for your willingness to help.

**Comment by hjy1998** [comment]
Alright, thank you for reply. Much appreciate.
________________________________
