### ISSUE TITLE
You could change the name as a contributor to Jhovany200 to MS-PC2

### ISSUE THREAD

**Issue by MS-PC2** [MathewSachin/Captura#247]
It has nothing to do with the "Captura" project, but you could change the name as a contributor to Jhovany200 to MS-PC2
Thanks.

**Comment by MathewSachin** [comment]
I would be happy to accept if you send a pull request for this.

**Comment by MS-PC2** [comment]
I was asking for it because I can not find the names of the contributors' profiles, and so you can change it for me. Please thanks.
