### ISSUE TITLE
Drop down menues in JavaFX GUIs not beeing recorded

### ISSUE THREAD

**Issue by gergang** [MathewSachin/Captura#252]
ComboBox and Menu show drop down lists of items. Captura does not seem to capture them. Example program to reproduce problem (needs Java 8):

`public class TestDropDowns extends Application
{
    private BorderPane bp;
   public TestDropDowns() {
        super();
        this.bp = new BorderPane();
    }

    public static void main(final String[] args) {
        launch(args);
    }

    public void start(final Stage stage) {
        try {
            this.bp.setPrefHeight(100.0);
            final VBox vBox = new VBox();
            BorderPane.setAlignment((Node)vBox, Pos.CENTER);
            BorderPane.setMargin((Node)vBox, new Insets(5.0, 0.0, 5.0, 0.0));
            final ObservableList<String> options = (ObservableList<String>)FXCollections.observableArrayList(new String[] { "1", "2", "3" });
            final ComboBox<String> comboBox = (ComboBox<String>)new ComboBox((ObservableList)options);
            comboBox.setPrefWidth(100.0);
            comboBox.setPromptText("ComboBox");
            vBox.getChildren().addAll(comboBox);
            this.bp.setRight((Node)vBox);
            final MenuBar menuBar = new MenuBar();
            final Menu menu = new Menu("Menu");
            menu.getItems().add(new MenuItem("New"));
            menu.getItems().add(new MenuItem("Save"));
            menu.getItems().add(new SeparatorMenuItem());
            final MenuItem exit = new MenuItem("Exit");
            menu.getItems().add(exit);
            exit.setOnAction(e -> System.exit(0));
            menuBar.getMenus().add(menu);
            menuBar.prefWidthProperty().bind((ObservableValue)stage.widthProperty());
            this.bp.setTop((Node)menuBar);
            final Scene scene = new Scene((Parent)this.bp);
            stage.setTitle("Test");
            stage.setOnCloseRequest(e -> System.exit(0));
            stage.setScene(scene);
            stage.show();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}`

**Comment by MathewSachin** [comment]
Which OS are you on?
If Windows 7 or older, try with both Aero enabled and disabled.

**Comment by gergang** [comment]
Thank you.!!!
Windows 7 it is, and I had Aero disabled.
