### ISSUE TITLE
Upgrade Simplified Chinese language files

### ISSUE THREAD

**Issue by freesoft0000** [MathewSachin/Captura#254]
[zh-CN.zip](https://github.com/MathewSachin/Captura/files/2300507/zh-CN.zip)

**Comment by MathewSachin** [comment]
It would be better if you would open a pull-request, so we can review the changes.

**Comment by freesoft0000** [comment]
[zh-CN.zip](https://github.com/MathewSachin/Captura/files/2301228/zh-CN.zip)
Updated with no translations

**Comment by freesoft0000** [comment]
On the left is the new Simplified Chinese language file, The old Simplified Chinese language file is on the right
![1](https://user-images.githubusercontent.com/30435921/44322199-b31f5180-a43b-11e8-9b0b-269fd9ea1705.png)

**Comment by MathewSachin** [comment]
@Airborne76, Please review

**Comment by MathewSachin** [comment]
Will be merging now since original translator did not respond.

Oh, sorry I missed it, keymaps are for adjusting keystroke overlay according to keyboard layout.
