### ISSUE TITLE
you can add support pausing, continuing and stopping the recording of videos in the task bar of windows

### ISSUE THREAD

**Issue by Small-Develop** [MathewSachin/Captura#257]
First of all thank you for taking the time and developing this great software, it fulfills its function well, I have two suggestions

The first suggestion would be to add the functions of pausing, continuing and stopping the recording of videos in the task bar so as not to open the application while recording the screen. to not open the menu with right click or the application, and add the functions directly in the task bar, if possible.

The second one could save the settings of the main window ie to always record with the same area and change and save the area as required and not always selecting the area again. In addition to the configuration of the video and audio format selected to not configure it every time the application is opened. Thank you

greetings.

**Comment by MathewSachin** [comment]
Glad that you liked Captura.

I suppose for the first suggestion, Hotkeys will be better for your use case.
Default hotkey for Start/Stop recording is Alt + F9, for pausing is Shift + F9.

Saving of audio/video encoder, audio/video sources etc. has been implemented. Please check the latest pre-release version.

**Comment by Small-Develop** [comment]
Fantastic, the  pre-release version very well fulfills the requested functions, I appreciate the effort and dedication for the development of this great software.
Thanks.
