### ISSUE TITLE
Suggestion: Filename output setting

### ISSUE THREAD

**Issue by Prome88** [MathewSachin/Captura#259]
Use case:

Add setting to allow user to save the recording using standard Save as dialogue where he/she manually inputs the desired name for the file instead of the default YYYY-MM-DD-HH-mm-ss.extension .

**Comment by MathewSachin** [comment]
In that case the filename will be asked whenever the user starts a new recording. I think it would be a bit disturbing.

Captura immediately starts writing to the file so it needs to be named first.

How about an option to specify a custom file name format?

**Comment by MathewSachin** [comment]
I'm working on file name format option. Di you have any specific requirements for auto replacement values except date, time?

I'm thinking of formats like `Video %yyyy%-%mm%`

**Comment by Prome88** [comment]
Date/time should cover our use case.

**Comment by MathewSachin** [comment]
Implemented something.

Please test: https://ci.appveyor.com/api/buildjobs/mjcpecgevjy8g2of/artifacts/Captura-Portable.zip

Go to `Settings > Configure file naming`.
