### ISSUE TITLE
Feature request: Add a select region for snapshots.

### ISSUE THREAD

**Issue by Godly75** [MathewSachin/Captura#261]
Your software looks very promising and it's the first video recorder that works this well with decent functions ! 

I'm missing one thing to make it my daily app:
I love the feature in Greenshot where you can draw your region to take a snapshot/screenshot.
I have set it as my Prt Scrn button.
So I need to keep on using Greenshot for screenshots, instead of Captura.

Could this be implemented?

**PS:  Some bug: after restart the icons on the left got missing in action :)
https://i.imgur.com/rR1TT3h.png**

**Comment by MathewSachin** [comment]
Ability to draw region for screenshot is one of my priorities right now.
Will be doing it as soon as I have the time.

BTW, I have done a fix related to the icon missing error, but not released yet.
It happened for me after collapsing and then expanding the UI.

Here's a dev build to test: https://ci.appveyor.com/api/buildjobs/n9u0i6ys8bjgn9dh/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
Great ! Much better !!! :)

**Comment by MathewSachin** [comment]
I've implemented something. 🎉 

Please test dev build: https://ci.appveyor.com/api/buildjobs/ybc665w6s2hva0hk/artifacts/Captura-Portable.zip

A new option named `Screenshot (Region)` will be available in system tray menu.
A hotkey can be manually added (as of now) for this action.

#### Adding the hotkey

1. Go to `Settings / Hotkeys`.
2. Add new hotkey **OR** change task from dropdown of existing hotkey to `ScreenShot (Region)`.
3. If you add new, make sure to check it to make it active, select action from dropdown and set keys by clicking on button.

**Comment by Godly75** [comment]
So cool !!!!
Works, but not correct

- I have 3 screens and when I screenshot region, it takes the next screen.
Also the drawing box is on the right side drawn. So it's always the next
screen on the right (these are my 3 screens)[image: 2018-09-16-12-56-15.jpg]

- It would be handy to have a magnifier also like in greenshot. With pixel
size shown.

- imgr upload gives error

But looking promissing so far ! Thanks for the quick response !

Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op za 15 sep. 2018 om 13:07 schreef Mathew Sachin <notifications@github.com

**Comment by MathewSachin** [comment]
I'm testing this. Might take some time simce i have only one monitor and cannot verify the issue.

**Comment by MathewSachin** [comment]
I did not receive the image of your screens. Please upload them here on GitHub.

**Comment by MathewSachin** [comment]
Got hold of a second screen. Did a fix!

Please test dev build: https://ci.appveyor.com/api/buildjobs/l2yxjox2ml0ax0r4/artifacts/Captura-Portable.zip

Still working on Magnifier...

**Comment by MathewSachin** [comment]
Implemented Magnifier.

Please test: https://ci.appveyor.com/api/buildjobs/2wkxix8xkux4avcy/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
alright cool !
- how can I turn on the magnifier? It doesn't work?
- the imgr upload for screenshot doesnt work (did before) and I don't get
an url in the pasteboard either?

Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op ma 17 sep. 2018 om 16:01 schreef Mathew Sachin <notifications@github.com

**Comment by Godly75** [comment]
Ow sorry, wrong version !
It works great ! :)

just that imgr isn't ploading like before



Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op ma 17 sep. 2018 om 16:01 schreef Mathew Sachin <notifications@github.com

**Comment by Godly75** [comment]
- maybe it would be better if the magnifier was left top next where you
start?
- would be handy if you click the webcam thumbnail that it opens the big
preview?

Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op ma 17 sep. 2018 om 14:27 schreef Mathew Sachin <notifications@github.com

**Comment by Godly75** [comment]
A 3 2 1countdown before recording would be handy?

Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op ma 17 sep. 2018 om 14:27 schreef Mathew Sachin <notifications@github.com

**Comment by Godly75** [comment]
ow and cancel recording (or restart) is also handy :)


Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op ma 17 sep. 2018 om 14:27 schreef Mathew Sachin <notifications@github.com

**Comment by MathewSachin** [comment]
> just that imgr isn't ploading like before

This is working on my system. Are you behind a proxy, if so check your proxy settings in the app.

> maybe it would be better if the magnifier was left top next where you start?

I suppose not. Having the magnifier next to mouse cursor, similar to Greenshot seems more handy.

> would be handy if you click the webcam thumbnail that it opens the big preview?

This seems really handy, would do ASAP.

> A 3 2 1countdown before recording would be handy?

There is a `Start Delay` option on Settings tab.

> ow and cancel recording (or restart) is also handy :)

I think it's better to leave it as it is, i.e. stop and start again.

**Comment by Godly75** [comment]
Nice job! 
Dunno what's wrong with imgr, it worked before

**Comment by Godly75** [comment]
- About the Region video recording, would it be handier to have a frame region like ispring? Captura huge border is rather very intimidating on screen. You could add the functions to the lower bar like here: http://i.imgur.com/b4Nhe1O.jpg?2

- You can start multiple instances of the same program, should be only 1

- Copy output file path to clipboard => doesn't add the url to the copy paste function?

**Comment by MathewSachin** [comment]
- iSpring looks good, will give it a try.

- I'm allowing multiple instances for users who might want to run multiple captures (preferably low FPS ones) on multiple monitors.

- Url is copied to clipboard when image is now saved to file, in which case file path takes priority. It can be copied from the recent list.

**PS** I'm having some trouble making the webcam preview clickable. Will try my best still.

**Comment by Godly75** [comment]
You're a great dev Mathew ! Love it

**Comment by MathewSachin** [comment]
If you have username, password check proxy authentication & enter credentials.

**Comment by Godly75** [comment]
It's normal windows 10?

**Comment by MathewSachin** [comment]
I meant to input the credentials in the app's proxy settings

**Comment by Godly75** [comment]
yes I know but i don't have this, I only use Windows 10 so it should be no
problem with the imgr upload right?

>

**Comment by MathewSachin** [comment]
I think I figured it out.
Please test this build: https://ci.appveyor.com/api/buildjobs/xly2swx8ip6o75p8/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
yes yes yes :)
it works now, thx, this is a very handy feature, because I share allot of screenshots to social media!

**Comment by Godly75** [comment]
Now, regarding the webcam feature, why not just put the preview link/button on top of the app next to the small webcam thumb? If it doesn't work to overlay a blank button on top of the preview? :)

**Comment by Godly75** [comment]
Ow, the IMGR link is not copied to the clipboard :)

**Comment by Godly75** [comment]
I think the webcam stays active, even when the app is idle in the tray?

**Comment by Godly75** [comment]
> > Ow, the IMGUR link is not copied to the clipboard :)
> 
> Have you turned on the Copy output file path to clipboard setting? It works for me.
> 
yep it's on but I don't get the imgur url in the copy paste after screenshotting.
https://i.imgur.com/W4OdgoL.jpg
(If I click the messages tray with the url it does work.)

> I think the webcam stays active, even when the app is idle in the tray?
> 
> It currently takes about a second to initialize the webcam. It is left active so that capture can be started immediately.

IMO the webcam should not be on all the time except when using the app for recording. Maybe set it to idle after few minutes?

**Comment by MathewSachin** [comment]
There are 4 targets for screenshot saving (Disk, Clipboard, Imgur, Editor).
Is Clipboard active (disable this), if so Imgur link will not be put on clipboard

**Comment by Godly75** [comment]
It's active, but it doesn't copy the link from imgur, instead it copies the clipboard file from memory. So I think it's one or the other. That works when disabling one.
https://i.imgur.com/axdb7Tj.jpg
