### ISSUE TITLE
Dates aren't showing up correctly for captured videos.

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#269]
Hello Sachin,

Please refer to the attached pictorial description.

File-naming mechanism within Captura isn't working ok for the captured videos.

Its saving videos in format ::: yyyy-mm-d  instead of yyyy-mm-dd.

The last entry for instance in the following description is only showing up - 2 , whereas it were captured on 24th in real.

Please provide further inputs in this regard?

Thank you.

![image](https://user-images.githubusercontent.com/23373249/45939270-d87d1d80-bfee-11e8-93b1-27b6a166a4c2.png)

**Comment by MathewSachin** [comment]
The file names seem to be correct in your image. Please note that 4 of 24 is wrapped on the next line.

You can change the windows file explorer view to list to view the name on a single line.

**Comment by saurabhdua82** [comment]
Hi Sachin !

Do you mean to say that's a BUG with Win 10 perhaps as the lines are getting overlapped for 'large icons' view ??

Should I take up this one with Win 10 support Team then ?

Thanks.

**Comment by MathewSachin** [comment]
It's not a bug. It is the expected behaviour to wrap long text.

**Comment by prakharsr** [comment]
@saurabhdua82 i also get these problems in whindows too, i will report thess problems to whindows ceo. this is very very serious problems as it is bery bad.
