### ISSUE TITLE
The option of sound notification when the picture is taken \ start recording the video

### ISSUE THREAD

**Issue by AnonJump** [MathewSachin/Captura#271]
As an alternative, you can display FPS in games and programs, similar to Bandicam. Green numbers = no recording, red numbers = recording.

**Comment by MathewSachin** [comment]
I'll add options for sound notification.

Unfortunately, displaying fps on program like Bandicam won't be possible because Bandicam handles screen capture differently compared to Captura.

**Comment by MathewSachin** [comment]
@AnonJump, I've implemented the basic functionality for this.
Audio files are not included, you can set your own audio files from `Settings / Configure Sounds ...`.

Please test dev build: https://ci.appveyor.com/api/buildjobs/9uglmfm717qrbabi/artifacts/Captura-Portable.zip

**Comment by AnonJump** [comment]
It works, thanks!
I'm wondering if we should add a sound length check? For example, no more than 5 seconds... 
Also, you can make a simple audio editor, which will allow you to select the desired segment of music to play (but it's harder to implement).

**Comment by MathewSachin** [comment]
For now, I think I would leave it up to the user to decide the length of sound he wants.

There is a simple audio trimming tool for trimming recorded audio.
A variation on it might work as desired. But, yeah this would be a little hard.

Might take this up in future. Closing for now.
