### ISSUE TITLE
Region selector - impossible to select and record full screen width (or height)

### ISSUE THREAD

**Issue by r4p7or** [MathewSachin/Captura#272]
Hi, thanks for this great recording application.

It has one significant drawback though:

It is not possible to record the full width or the full height of a screen using the Region selector.
For example if you have 1280 x 1024 px screen you cannot resize the selector frame to 1280 x 900 px and record a video of this resolution. Or 800 x 1024 px etc.

If the vertical toolbar on the left (with the pencil, eraser, ...) could be hidden I reckon the selector frame could be resized to the full width of the screen. Because of the toolbar the recorded full-width video is always trimmed by 38 px in the X axis from the left.

**Comment by MathewSachin** [comment]
Region selector is not intended for full screen recording. There is a separate full screen recording mode for that.

**Comment by r4p7or** [comment]
Thanks for the answer. Yes, I am aware of the full screen mode but I don't want to record a full screen. I want to record just full width of the screen (but not full height). For example imagine you want to record just top half of your screen: 100 % width and 50 % height. You cannot do that with captura. 
Or another use case would be recording a full screen but without say 100px strip at the top and 200px strip at the bottom.

**Comment by MathewSachin** [comment]
@r4p7or There has been a change to region selector which has not been released yet.
The borders of Region selector have been made thinner.

Please test the dev build: https://ci.appveyor.com/api/buildjobs/2hku6oq29f9l30j5/artifacts/Captura-Portable.zip

**Comment by r4p7or** [comment]
Thanks for the dev build, Matthew. Great work. It is almost there. I can record full width but the semi-transparent toolbar is visible in the recorded video.

I am still not able to select full height (for example 80 % of the screen width x 100 % of the screen height). The floating UI elements get in the way. Although to be honest I might not need it anytime soon. 100% width x less than 100 height is more useful for me.

Here is my proposal:
[https://cubeupload.com/im/raptor/capturaproposal.png](url)

Thanks.

**Comment by MathewSachin** [comment]
@r4p7or I really liked your suggestion. Would try to implement and let you know ASAP.

**Comment by Small-Develop** [comment]
Considering the aggregation of the toolbar should appear below or allow the user in configuration, up to the right or in another position, besides adding hotkeys to configuration to select the tool and not go with the mouse to activate it or select it. Thank you for developing this excellent software.

**Comment by MathewSachin** [comment]
The region controls have been completely moved to the main window as of v9.0.0-beta4
