### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by Godly75** [MathewSachin/Captura#273]
Hi Mathew,

I downloaded the latest version from the website, it says version 7.0.1, so it's higher than the dev version from last week wich is v6.
Yet it is outdated.
Where can I download the latest version with all the new features?

**Comment by MathewSachin** [comment]
@Godly75 Development builds are versioned differently.
You can find latest pre-release on GitHub Releases: https://github.com/MathewSachin/Captura/releases

Or if you are looking for the latest dev build: https://ci.appveyor.com/api/buildjobs/h06022774qynjcr7/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
Mathew,
I was looking where to download the latest dev builds,
is there a page where I can see this?



Op ma 1 okt. 2018 om 13:17 schreef Mathew Sachin <notifications@github.com>:

**Comment by MathewSachin** [comment]
See the instructions for getting dev build on https://mathewsachin.github.io/Captura/ci

Make sure you get master branch builds.
