### ISSUE TITLE
Integrate translations with Crowdin

### ISSUE THREAD

**Issue by Prome88** [MathewSachin/Captura#288]
I've been working on some other open source projects which use Crowdin service for translations.
Would it be possible to try and open a Crowdin project for Captura?

Additional info is available at their website - https://crowdin.com/page/open-source-project-setup-request

> Crowdin is completely free of charge for Open Source projects. We love Open Source and ready to support community projects.

**Comment by MathewSachin** [comment]
I've set up a project on CrowdIn. I'm still trying to get used to it.
Looks Good so far.

**Comment by MathewSachin** [comment]
Here's the invitation link if someone else wants to join:

https://crowdin.com/project/captura/invite?d=6565l4h685i563e49333d393d483e3v2v4t253j443o453s29393s253u2j493e4l423v2f3o4d4f353u26383f473b3t2m453734353i4c34363s4t273r443p423s293t24343u2m4b3e4m4t273h3i4p4b3t2734303o4732373i4f5a39393k463b3
