### ISSUE TITLE
NullPointerException when try FFmpegService.StartFFmpeg from another thread

### ISSUE THREAD

**Issue by daniel55411** [MathewSachin/Captura#292]
Hello Mathew,

When I try execute `FFmpegService.StartFFmpeg` from another thread I have a `NullPointerException`. Exception are throwns from `FFmpegLog.CreateNew` by `_syncContext` variable. It's happening because `_syncContext` is null for all threads except main UI thread. 
For me, solution for this problem is starting ffmpeg process by `Dispatcher`

I have questions. Is it undefined behaviour? Or normal?
Can you explain for me why you use `SynchronizationContext` for inserting new log items?

**Comment by MathewSachin** [comment]
`ObservableCollection` is data-bound to view in UI thread and requires to be accessed from the UI thread.
So, we have to use `SynchronizationContext` or `Dispatcher`.

BTW, I've added a new commit to handle the case when `SynchronizationContext` is null.
