### ISSUE TITLE
Proposal: Add delete button to Notifications

### ISSUE THREAD

**Issue by Kaedin** [MathewSachin/Captura#295]
Hi Developer,

Could you consider adding a delete button (with trash bin icon?) to Notifications which opens e.g. after saving a recording?

![image](https://user-images.githubusercontent.com/26382655/47349125-91e91480-d6bb-11e8-9ec5-1f2687ccdfbc.png)

This would be beneficial for situation that you already know that you're not happy with the outcome of the capture or you have somehow failed to represent some details which you're trying to capture, and then you would like to instantly delete it.

Best regards,
Kaedin

**Comment by MathewSachin** [comment]
Ok. Should a confirmation dialog be shown before deletion?

**Comment by Kaedin** [comment]
I personally think that it's not necessary to add a confirmation if it's made sure that the deleted item is sent to Recycle Bin, where it can be recovered in case of unintentional deletion.

An indicator e.g. "Deleted" text could be added to the notification to replace the delete button, once user has used it to remove the file. This could help out with identifying deleted items as long as their notification(s) are shown/not cleared.

**Comment by MathewSachin** [comment]
I decided to ask for confirmation and delete permanently to be consistent with the rest of the app.

Here's a build to test: https://ci.appveyor.com/api/buildjobs/owk08fw9f6a999rq/artifacts/Captura-Portable.zip

**Comment by Kaedin** [comment]
Sure, I think too that the way you have implemented this is great! After
reconsideration, it's always good to have some when deleting something. 👍

Just some minor notice: if you have deleted the file manually via File
Browser, without using the Captura's delete button, the file still remains
on the notification popup list if it hasn't been cleared from it. I don't
know how likely this scenario is that user prefers still to remove the file
by other means but...
 -> Maybe Captura could go through the files before opening notifications
popup to check if the list is still accurate?
 -> Or at least when trying to delete a non-existing file using the
Captura's button, it could give a some kind of notice that the file has
already been removed and clear the entry?

Best regards,
Ilpo

**Comment by MathewSachin** [comment]
Ok, I've changed the code to remove from list when deleting an already deleted file.

I'll not be checking whether the list is accurate as of now. Pull requests are welcome though.
