### ISSUE TITLE
[Suggestion][Minor] Change window opening mechanic in System Tray

### ISSUE THREAD

**Issue by nabakin** [MathewSachin/Captura#299]
Hey Matthew!  Great project, just found it and will definitely be using it for all my video recording/screenshot taking needs.

When I started messing around with Captura's settings, I tested out the Minimize to System Tray on Startup option and it worked great, but it took me a little while to figure out how to open the window again.  Right now you have it set to open the window when it is double clicked, but I think that's very strange and unintuitive for a tray icon.  I'm used to right clicking on the tray icon for options and left clicking once to open up the window.  It might be different for others, but I don't think I've ever opened a window by double clicking the tray icon.  So, I suggest making it like other applications where a left click opens the window and a right click shows the options.

Thanks for all your work!  Feel free to disregard and close this issue if you disagree.

**Comment by MathewSachin** [comment]
In all the apps I've used, double clicking on the tray icon is the way to show the main window. I suppose I will leave it as it is.
How about a `Show Main Window` option in the context menu?

**Comment by nabakin** [comment]
Yeah I don't know, maybe they are both used.  [Here's](https://giphy.com/gifs/8Fc0PuI14vLXx40ai3/fullscreen) me pressing all of the icons in my System Tray.  They're all one left click to open.

That would be great, ty!

**Comment by nabakin** [comment]
Oh Giphy cut my video short actually.

**Comment by MathewSachin** [comment]
I'm adding the option for user to select what will happen on left click on tray icon.
It will be set by default to open main window.

**Comment by MathewSachin** [comment]
Please test dev build: https://ci.appveyor.com/api/buildjobs/kty9dy4umetfwwa5/artifacts/Captura-Portable.zip

Left click action is set to `Show Main Window`. Go to `Settings / Configure Tray Icon ...` if you want to customize.

**Comment by nabakin** [comment]
Works perfectly!  Thanks!
