### ISSUE TITLE
Direct3D Fullscreen Capture

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Captura#3]
Unable to Capture fullscreen windows like DirectX games

**Comment by MathewSachin** [comment]
A question has been put on stackoverflow: http://stackoverflow.com/questions/33690825/screenshot-directx-fullscreen-game?noredirect=1#comment55153892_33690825

**Comment by MathewSachin** [comment]
Working in a new repo on https://github.com/MathewSachin/Captura/Direct3DHook

**Comment by uGiFarukh** [comment]
Sachin for the beginning please refer to these issues :

https://github.com/spazzarama/Direct3DHook/issues/33
https://github.com/spazzarama/Direct3DHook/issues/30

The issue number 30 is the one which your facing with GIF image processing. It occurs both in Pixel Data processing and also GIF Image processing. And also it takes a lot of time to process all the gif images completely when you go for multiple captures.
