### ISSUE TITLE
[Suggestion] Image Editor feature improvements

### ISSUE THREAD

**Issue by nabakin** [MathewSachin/Captura#300]
Hey Matthew!  Great project, just found it and will definitely be using it for all my video recording/screenshot taking needs.

While messing around with Captura, I quickly found myself wanting a few features in the Image Editor:
- [x] **Color setting/persistence:** Right now the Image Editor has the default color in the Color Palette set to Black, but I'd like to customize that instead of having to change the color every time I open the Image Editor.  This could be done through a setting in the Screenshot tab or just remembering the color from a previous session.
- [x] **Upload to Imgur:** At the moment, you can't upload to Imgur from the Image Editor.  You have to save it to the disk, upload using the Recent tab, and then delete the file.  I'd like to just upload it to Imgur and save the url to my clipboard without having to save to the disk or having to open up the main Captura window.
- [x] **Arrow tool:** A lot of times when people take screenshots, we want to point an arrow at something.  We can do that at the moment with the drawing or line tool, but it takes a few seconds and doesn't always look good, so I think having a dedicated tool for arrows would be a great addition.
- [ ] **Crop tool:** I'd like to be able to crop from the Image Editor for the same reasons as above. "I'd like to just upload it to Imgur without having to save to the disk or having to open up the main Captura window."

If you could add those, that would be awesome!  Thanks for all your hard work!

**Comment by Godly75** [comment]
Good features I love this ! 
Also it would be handy you can choose when to add notations to a screenshot.
For example, when I take a screenshot of a single window, 
Maybe offer in the notifications to edit?
Or show a center popup with a message. 
Screenshot saved, edit? 
Or this function as option in the settings...?

**Comment by MathewSachin** [comment]
@Godly75 I've added a edit button to screenshot notification.

**Comment by MathewSachin** [comment]
Here's a build to test: https://ci.appveyor.com/api/buildjobs/owk08fw9f6a999rq/artifacts/Captura-Portable.zip

Cropping within image editor is not done yet. It's a bit complicated 😭

**Comment by MathewSachin** [comment]
I've dropped maintaining the inbuilt image editor. It took too much of my time which could be spent improving the recording features.
Now, the app opens images into MS Paint for editing by default. The program to use for editing can be configured by the user.
