### ISSUE TITLE
Images uploaded to imgur using the tool doesn't show up in recent tab

### ISSUE THREAD

**Issue by Nottt** [MathewSachin/Captura#305]
And I can't find how to delete it from imgur too :/ 

![image](https://user-images.githubusercontent.com/13532436/47835463-cf683480-dd82-11e8-81e2-c93d9b284ef1.png)

Am I doing something wrong or this is expected behavior?

Thanks!

**Comment by MathewSachin** [comment]
Changed it to show in recent tab.

Here's a build to test: https://ci.appveyor.com/api/buildjobs/twrqwbxjw8yw01cr/artifacts/Captura-Portable.zip
