### ISSUE TITLE
Windows screenshots sometimes give an extra border?

### ISSUE THREAD

**Issue by Godly75** [MathewSachin/Captura#306]
Hi Mathew,
The single window screenshot give a border mostly, as if the shadow is saved along?
https://i.imgur.com/Wes72Tr.jpg
https://i.imgur.com/AqCyDYo.jpg
https://i.imgur.com/d9icfjo.png
![20181102 - 11h41m09](https://user-images.githubusercontent.com/38914962/47910946-9e782480-de94-11e8-86cd-9a07ba069e1c.png)

etc
You can't always see as it's sometimes black on black... 
But check here in the overview:
https://i.imgur.com/YEZDlo6.png

Other thing: why are imgurs sometimes as jpg then as png saved?

**Comment by MathewSachin** [comment]
The border was intended for recording the window shadow.
The screenshots tend to look better with the shadow.
I've done some fixes and reduced the border size.

Imgur should now be saved as per selected format. If that problem still happens, please let me know.

Also, let me know if you want an option to take screenshot without shadow.

Please test dev build: https://ci.appveyor.com/api/buildjobs/qrt9bq50b81fsu6b/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
Thx!
To have a clean window just to the borders seems the best option to me

**Comment by MathewSachin** [comment]
I've added a new option: `Window ScreenShot Transparent` to ScreenShot Settings.
You can disable it to capture without shadow.

Here's the latest dev build: https://ci.appveyor.com/api/buildjobs/g07xlegiii298tsm/artifacts/Captura-Portable.zip
