### ISSUE TITLE
Can not record at all

### ISSUE THREAD

**Issue by jmferreirab** [MathewSachin/Captura#307]
![image](https://user-images.githubusercontent.com/29668777/47919361-31a56000-de7d-11e8-9cf4-a9170c79fee6.png)

I'm consistently getting this error whenever I try record video in any of the recording video modes (except screen duplicate).

I have audio/mic disabled. Codec settings are default. FFMPEG works with earlier versions.

It seems that Captura is simply not writing anything to disk.

Settings 
![image](https://user-images.githubusercontent.com/29668777/47919549-9d87c880-de7d-11e8-9d28-84999706ff08.png)

History (recorded files appear grayed out)
![image](https://user-images.githubusercontent.com/29668777/47919574-a9738a80-de7d-11e8-9faf-c8fd86eefdc2.png)

When trying to close Captura I get this: 

![image](https://user-images.githubusercontent.com/29668777/47919615-c4de9580-de7d-11e8-8bd6-ed78bae9c58a.png)

PC: 

Ryzen 5
8GB RAM
EVGA Geforce 1060
Windows 10

**Comment by MathewSachin** [comment]
Please provide FFmpeg log for a failing recording.
Can be opened from FFmpeg page.

**Comment by jmferreirab** [comment]
ffmpeg version N-67529-g2c0bf76 Copyright (c) 2000-2014 the FFmpeg developers
  built on Nov 11 2014 14:36:22 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      54. 11.100 / 54. 11.100
  libavcodec     56. 12.100 / 56. 12.100
  libavformat    56. 12.103 / 56. 12.103
  libavdevice    56.  2.100 / 56.  2.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'thread_queue_size'.
Error splitting the argument list: Option not found

**Comment by jmferreirab** [comment]
Update. Closed it and ran as administrator. Got this error. Was also getting it before running as admin. 

System.Exception: System can't keep up with the Recording. Frames are not being written. Retry again or try with a smaller region, lower Frame Rate or another Codec.
   at Screna.Recorder.<DoRecord>d__17.MoveNext()

**Comment by MathewSachin** [comment]
I think the FFmpeg version you have is a bit old. Please download latest FFmpeg

**Comment by MathewSachin** [comment]
You can use the inbuilt FFmpeg downloader for that.

**Comment by jmferreirab** [comment]
That solved it. This issue is a pretty narrow use case though. 
Someone having older ffmpeg versions instead of redownloading.

Suggestion: Add to readme (It is recommended to always download FFMPEG through Captura's API. Older versions of FFMPEG can cause unexpected behaviour.)

**Comment by MathewSachin** [comment]
Yup. Will add to ReadMe ASAP.
Will keep this issue open tiil then.

**Comment by MathewSachin** [comment]
Added to ReadMe

**Comment by BobWang2018** [comment]
> That solved it. This issue is a pretty narrow use case though.
> Someone having older ffmpeg versions instead of redownloading.
> 
> Suggestion: Add to readme (It is recommended to always download FFMPEG through Captura's API. Older versions of FFMPEG can cause unexpected behaviour.)

_The **SAME** **system exception** ccurred again，_even though I have updated the built-in ffmpeg.Does it really work by update the built-in ffmpeg.

System.Exception: System can't keep up with the Recording. Frames are not being written. Retry again or try with a smaller region, lower Frame Rate or another Codec.
   at Screna.Recorder.<DoRecord>d__17.MoveNext()

ffmpeg version N-95085-g525de95679 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20190918
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.100 / 58. 59.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 59.100 /  7. 59.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, rawvideo, from '\\.\pipe\captura-42925cf9-5c4c-4231-a694-a35e82cb9eeb':
  Duration: N/A, start: 0.000000, bitrate: 929354 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 2582x1406, 929354 kb/s, 8 tbr, 8 tbn, 8 tbc

![image](https://user-images.githubusercontent.com/38725460/65763884-e8c25e00-e156-11e9-91cd-9b8c18943c7d.png)

![image](https://user-images.githubusercontent.com/38725460/65763967-1a3b2980-e157-11e9-9106-fbe63759dc4c.png)

**Comment by BobWang2018** [comment]
![image](https://user-images.githubusercontent.com/38725460/65764386-1b208b00-e158-11e9-8cb4-1f0a1f3f24a3.png)

The system exception occurred everytime when Captura.exe works for 4 seconds.
