### ISSUE TITLE
Exception when start recording:

### ISSUE THREAD

**Issue by daybson** [MathewSachin/Captura#318]
ffmpeg version N-92429-g7992c2867e Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 23.101 / 56. 23.101
  libavcodec     58. 39.100 / 58. 39.100
  libavformat    58. 22.100 / 58. 22.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 43.100 /  7. 43.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-a7372a51-ccfa-462a-b1f1-b2c53dcf6731':
  Duration: N/A, start: 0.000000, bitrate: 1592524 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 1592524 kb/s, 24 tbr, 24 tbn, 24 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[h264_nvenc @ 000002d3132ed3c0] Cannot load cuDeviceGetUuid
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by MathewSachin** [comment]
It seems like you are using FFmpeg H.264 NVENC encoder. Do you have NVIDIA graphic card? If yes, let me know the model number.

**Comment by daybson** [comment]
Yes, I do. Is a GeForce GT 740, driver v. 388.13

**Comment by daybson** [comment]
Oh, I got it! I've changed to x264 and is working ok.
Well, thank you!
