### ISSUE TITLE
Couldnt record webcam video?

### ISSUE THREAD

**Issue by SaddamBInSyed** [MathewSachin/Captura#319]
I have downloaded the latest version and usign 2017 I builded the sln file and got the exe. when I ru nthe same i coludnt able to record any video from the webcam but audio only works fine.

There is no option to select my webcam but only audio.

![2018-11-13-16-55-05](https://user-images.githubusercontent.com/10062672/48414850-37485300-e765-11e8-9e96-3a837c603bfb.png)

the same issue persists for usign setup.exe too.

please help me to resolve this. I want to record the video in mp4 format and also the desktop full screen  video.

thanks in advance

**Comment by MathewSachin** [comment]
`Only Audio` mode does not have video. Select `Screen` recording mode for recording screen and webcam.

![2018-11-13-18-33-11](https://user-images.githubusercontent.com/10654537/48415206-bee88e80-e772-11e8-9908-4cdf7b9bcba3.png)

If webcam recording does not work, try updating its drivers from `Control Panel > Device Manager`.

**Comment by SaddamBInSyed** [comment]
I have did the same but no luck, please see the screenshot below.

i am using logitec c920 camera.

![2018-11-13-17-27-29](https://user-images.githubusercontent.com/10062672/48416425-9dcf7000-e769-11e8-8678-351ff2427749.png)

![image](https://user-images.githubusercontent.com/10062672/48416506-d2dbc280-e769-11e8-9ba8-3be89bb7c714.png)

also i have check the device manager. and its fine other app can able to record the video.


please advice

**Comment by MathewSachin** [comment]
After some googling, I think this might be a problem with your Windows 10 version.
Do you have Anniversary Update? Problems of black recording on it for Logitech cameras have been reported. See https://community.spiceworks.com/topic/1885798-logitech-c920-black-screens-at-1080p-windows-10-version-1607.
Try updating your windows version.

Otherwise, these steps were suggested on Logitech website:

- Try plugging your webcam directly into a USB 2.0 port on your computer.
- Try installing the Logitech Webcam Software/Logitech Gaming Software as an administrator while your computer is in Clean Boot mode (http://support.logitech.com/en_us/article/228).
- Try to update the UVC drivers on your computer into Logitech drivers (http://support.logitech.com/en_us/article/25904).
- Verify that there's no other software using your webcam when you're trying to use it with a specific one.
- If possible, try using your webcam on another computer to rule out possible hardware related issues.

**Comment by SaddamBInSyed** [comment]
S, You are right.

its working fine with another windows 10.

by the way I want to ask you the following,

1. Since I am recording the video 24hrs,  I have to save my recording video file locally, so How can reduce the file size. ( should be less with medium video quality.)


Please advise.

**Comment by MathewSachin** [comment]
You'll have to experiment with the options to find a trade-off between quality and size suitable to you.

**Comment by SaddamBInSyed** [comment]
As suggested, I have updated my windows 10 pc but still, it shows the black screen when opening the camera.

what else I need to try

**Comment by MathewSachin** [comment]
Did you try the other steps I mentioned in the above comment?

Since, the issue is not specific to Captura, I think the Logitech support team might be able to help you better.

**Comment by SaddamBInSyed** [comment]
Thanks for your response.

by the way, 

Is it possible to do the screen capture and webcam recording at same using your cmd line tool? 
can you please advise.

**Comment by MathewSachin** [comment]
Try `captura-cli start --webcam 0`

**Comment by SaddamBInSyed** [comment]
after trying several options, finally, the pbm related with logitec camera C920 model .

C922 model is working fine with this app.

Thanks, mathew.

**Comment by SaddamBInSyed** [comment]
I have tried the suggested command, " captura-cli start --webcam 0" . It works fine but It combining camera and screen record into single video. I need them as separate files.


Please give the cmd line arg for that.

thanks.

**Comment by MathewSachin** [comment]
Cmdline argument for separate video and webcam recording has not yet been implemented.

**Comment by SaddamBInSyed** [comment]
since I am getting  25mb video(avi ) / 5min , I have used NRecovideo converter lib to convert the 23mb AVI video format to Mp4 format.  then the output mp4 file is 5mb only.

I used the below filter setting.

" -filter_complex \"[0] yadif=0:-1:0,scale=iw*sar:ih,scale='if(gt(a,4/3),640,-2)':'if(gt(a,4/3),-2,480)'[scaled];[scaled] pad=640:480:(ow-iw)/2:(oh-ih)/2:black \" -c:v libx264 -c:a mp3 -ab 128k "

since you using ffmpeg lib , Is it possible to have suchconversion setting option in captura.

appreciate your advice.

**Comment by MathewSachin** [comment]
There is support for FFmpeg Mp4 codec. If you want more customisation, you can try Custom FFmpeg codecs from Settings / FFmpeg

**Comment by SaddamBInSyed** [comment]
as suggested, I have added the same  when I selected the start recording option then the 
below error occuring,

![image](https://user-images.githubusercontent.com/10062672/48485039-40065b00-e831-11e8-8dda-e93527a656bf.png)


my configuration
![image](https://user-images.githubusercontent.com/10062672/48485127-7512ad80-e831-11e8-9399-6cc332d158fe.png)

**Comment by MathewSachin** [comment]
Your Args seem to be wrong. You have to include the -vcodec parameter. For reference, see the default value when a new codec is added.
If it still doesn't work, check the FFmpeg log

**Comment by SaddamBInSyed** [comment]
FFmpeg log says

ffmpeg version N-92429-g7992c2867e Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 23.101 / 56. 23.101
  libavcodec     58. 39.100 / 58. 39.100
  libavformat    58. 22.100 / 58. 22.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 43.100 /  7. 43.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-ad02b573-8e17-4b3d-a797-441bd8082c3b':
  Duration: N/A, start: 0.000000, bitrate: 117964 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 640x480, 117964 kb/s, 12 tbr, 12 tbn, 12 tbc
[AVFilterGraph @ 000001edff63af80] No such filter: '"'
Error initializing complex filters.
Invalid argument

I am not much exp in ffmpeg, if you know where I am wrong, please let me know.
I want to send this below args to ffmpeg, 

![image](https://user-images.githubusercontent.com/10062672/48487825-c70b0180-e838-11e8-9424-766ef0f7cc0d.png)

**Comment by MathewSachin** [comment]
Use `-vcodec libx264 -crf 30 -pix_fmt yuv420p -preset ultrafast -filter_complex "[0] yadif=0:-1:0,scale=iw*sar:ih,scale='if(gt(a,4/3),640,-2)':'if(gt(a,4/3),-2,480)'[scaled];[scaled] pad=640:480:(ow-iw)/2:(oh-ih)/2:black "` for args.

**Comment by MathewSachin** [comment]
Uncheck the Custom Size option in FFmpeg Settings

**Comment by SaddamBInSyed** [comment]
yeah. now its fine,

**Comment by SaddamBInSyed** [comment]
> Cmdline argument for separate video and webcam recording has not yet been implemented.

Hi There,

Could you please advise the above-stated option is implemented if not could you advise the steps to do the same?
Also, advise about how to add custom codec args by default in the code?

Thanks.

**Comment by SaddamBInSyed** [comment]
Hi there, 
 I have downloaded and tested the captura-portable zip file and run the console app with the following args,

captura-cli.exe start --length 10 --cursor --mic=0 --file="C:\Users\\Documents\capturafile\test.mp4" --webcam 0

now it's created two  .mp4 files successfully.

but i want the following changes only,

1.  Audio should be with webcam video file NOT desktop capture.
2.  how to disable desktop capture recording.

please help to resolve this issue.

thanks in advance,

**Comment by MathewSachin** [comment]
- I've seen that you've successfully recorded webcam to separate file in another issue.
- For adding custom codec args, you'll have to do a custom build of Captura and add new item in `FFmpegItem.Items` array.
- Regarding the build error, try updating to latest version of Visual Studio 2017.

**Comment by SaddamBInSyed** [comment]
Could you please advise which version of vs2017 the app looking?

**Comment by MathewSachin** [comment]
v15.9

**Comment by SaddamBInSyed** [comment]
> Use for args:
> 
> ```
> -vcodec libx264 -crf 30 -pix_fmt yuv420p -preset ultrafast -filter_complex "[0] yadif=0:-1:0,scale=iw*sar:ih,scale='if(gt(a,4/3),640,-2)':'if(gt(a,4/3),-2,480)'[scaled];[scaled] pad=640:480:(ow-iw)/2:(oh-ih)/2:black "
> ```
> You might want to adjust the value of CRF for quality.
> 
> > The range of the CRF scale is 0–51, where 0 is lossless, 23 is the default, and 51 is worst quality possible.


Hi Mathew,

I have used the above ffmpeg command line for to reduce the video file size and its works fine.

but the converted AVI to MP4 video is working only in Chrome browser NOT in IE.

could you please advise about this?

Also advise me where to include this line in above ffmpeg cmd line

"-pix_fmt yuv420p"

Thanks.

**Comment by MathewSachin** [comment]
I'm sorry. I'm not aware of what formats IE supports. Try searching the internet or asking on the FFmpeg forums.
