### ISSUE TITLE
Fixed window size / Window position problem

### ISSUE THREAD

**Issue by twity1337** [MathewSachin/Captura#321]
Every time I open Captura, its window opens up in  the top corner **behind** my Windows 7 task bar. (Note: I moved my windows task bar to the top of the screen)
This is a problem, because you can't crab the window to move it to another position.

This problem doesn't appear on other applications, because Microsoft Windows automatically moves the top border of an window to an accessible area, when clicking to the side/"resize border" of that window. But in Captura, it's not possible to simply click the border of the window, because it doesn't allows it.

A possible fix could be, to open the window in the center of the screen.

See the screenshot below for more details.
![Screenshot](https://user-images.githubusercontent.com/21298992/48499074-e05f7e00-e837-11e8-8fa8-c716c3e1428b.JPG)

**Comment by MathewSachin** [comment]
You can right click on Captura thumbnail in taskbar and select move. Now, the window can be moved freely using arrow keys.

**Comment by MathewSachin** [comment]
Also, the last window position will be remembered from the next release.

**Comment by twity1337** [comment]
> You can right click on Captura thumbnail in taskbar and select move. Now, the window can be moved freely using arrow keys.

Thanks for the workaround. Didn't know that MS Windows has this feature.

**Comment by MathewSachin** [comment]
Have added the workaround to the troubleshooting page on the website.
