### ISSUE TITLE
Replace Bass with open source alternative

### ISSUE THREAD

**Issue by sleman** [MathewSachin/Captura#323]
Great work on Captura but not happy about using bass library for audio capture as it's a commercial library. I suggest replacing it with [cscore](https://github.com/filoe/cscore) or [naudio](https://github.com/naudio/NAudio) both are open source .net libraries.

**Comment by MathewSachin** [comment]
I had tried using NAudio before but had problem with mixing multiple audio streams which BASS does really well. I'll give it a try again and let you know.

**Comment by MathewSachin** [comment]
@sleman I've implemented NAudio support as a fallback when BASS is not present.

Here's the dev build to test: https://ci.appveyor.com/api/buildjobs/lji0qxlnat9gk69a/artifacts/Captura-Portable.zip

Removing `bass.dll` or `bassmix.dll` will cause NAudio to be used.

BASS will be kept as the default library till NAudio support is tried and tested.

When using NAudio, changing sources during recording is not supported.
Also, the audio device must support WASAPI Shared mode in 32-bit floating-point, 44100 Hz, Stereo format.

**Comment by sleman** [comment]
Tested dev build but it records static when I remove bass dll files and using Naudio.

[audio.zip](https://github.com/MathewSachin/Captura/files/2597007/audio.zip)

**Comment by MathewSachin** [comment]
Does audio-only recording work for you?
I'll try to resolve this ASAP.

**Comment by MathewSachin** [comment]
Also, try using the `Record into separate files` option and let me know if it works.

**Comment by sleman** [comment]
Sounds like it plays back much faster and much higher pitch.
[2018-11-20-09-41-32.0.wav.zip](https://github.com/MathewSachin/Captura/files/2600172/2018-11-20-09-41-32.0.wav.zip)

**Comment by sleman** [comment]
Tested with NAudio Sample project: NAudioWpfDemo with default settings and recording was fine:
![desktop 2018-11-20 09 50 51](https://user-images.githubusercontent.com/976380/48781306-c5629300-eca9-11e8-8a03-469d856e5314.png)

**Comment by MathewSachin** [comment]
Ok. It seems the problem is with differing Sample Rate. I suppose the supported sample rate for your device is 16k.
I had assumed 44.1k as a standard format for Shared mode recording.
I'll take a look at the sample.

**Comment by MathewSachin** [comment]
Added sample rate conversion.
Please test: https://ci.appveyor.com/api/buildjobs/2sa8qa7naj6rs0xo/artifacts/Captura-Portable.zip

**Comment by sleman** [comment]
Working well now :+1:
