### ISSUE TITLE
Can't record since update

### ISSUE THREAD

**Issue by Godly75** [MathewSachin/Captura#334]
As far as I see, all the settings are correct and like before, but recording doesn't work since latest update to v 0.0.2316

https://i.imgur.com/6ysTlPQ.png

System.Exception: System can't keep up with the Recording. Frames are not being written. Retry again or try with a smaller region, lower Frame Rate or another Codec.
   at Screna.Recorder.<DoRecord>d__17.MoveNext()

**Comment by MathewSachin** [comment]
v0.0.2316 is pretty old dev build.
Try with the latest dev build.

**Comment by Godly75** [comment]
link?

Op wo 28 nov. 2018 om 13:30 schreef Mathew Sachin <notifications@github.com

**Comment by MathewSachin** [comment]
https://ci.appveyor.com/api/buildjobs/nkle4dad15px2fwp/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
Thx I installed, but it already says update available? https://mathewsachin.github.io/Captura/download

**Comment by Godly75** [comment]
This version is already better, the selected window is perfectly captured now ! Thx

**Comment by MathewSachin** [comment]
> Thx I installed, but it already says update available? https://mathewsachin.github.io/Captura/download

The update check is intended for release builds.
Since, you're on a dev build, it is not relevant for you.
In future I'll try to implement update check for dev builds too.
