### ISSUE TITLE
Merging audio with webcam video file and disable desktop recording ?

### ISSUE THREAD

**Issue by SaddamBInSyed** [MathewSachin/Captura#344]
Hi there,
I have downloaded and tested the captura-portable zip file and run the console app with the following args,

captura-cli.exe start --length 10 --cursor --mic=0 --file="C:\Users\Documents\capturafile\test.mp4" --webcam 0

now it's created two .mp4 files successfully.

but i want the following changes only,

Audio should be with webcam video file NOT desktop capture.
how to disable desktop capture recording.
please help to resolve this issue.

thanks in advance,

**Comment by MathewSachin** [comment]
This is not currently possible with the way Captura is implemented.

**Comment by SaddamBInSyed** [comment]
Thanks for reply,
I am learnign the code flow, I came across the below line where, audioprovider is not passed, If i pass the IAudioProvider obj here, Will it record with audio?

 var webcamVideoWriter = GetVideoFileWriter(webcamImgProvider, null, webcamFileName);

please advise

**Comment by MathewSachin** [comment]
Try passing the audio provider to only for webcam.
Remove the audio provider being passed for desktop recording.

**Comment by SaddamBInSyed** [comment]
already tried the same. but no luck. same error occurring.

**Comment by MathewSachin** [comment]
Since, you don't want to record screen, try setting `_recorder` to webcam recorder instead of the multi dispose recorder.

**Comment by MathewSachin** [comment]
Try downloading the latest version of the code and try modifying it. I have removed the code throwing that exception. Maybe that would help.

**Comment by SaddamBInSyed** [comment]
Thanks for reply,  I already having VS 15.9 and now as suggested I am updating VS to 15.9.4.
lets see,

**Comment by MathewSachin** [comment]
@SaddamBInSyed I'm adding a webcam only recording mode to Captura.
See #371 for details.

**Comment by MathewSachin** [comment]
#371 has been merged into master branch.
Please test dev build: https://ci.appveyor.com/api/buildjobs/k166gmr3aeunxq06/artifacts/Captura-Portable.zip

```
captura-cli start --source webcam --webcam 0 --mic 0
```
