### ISSUE TITLE
HEVC Pipe is broken

### ISSUE THREAD

**Issue by ponmy** [MathewSachin/Captura#356]
How can I fix this so I can record with HEVC?

![snip_20190114142859](https://user-images.githubusercontent.com/43487371/51142305-c840b680-1808-11e9-93d8-0fa3e2f7dbeb.png)

Processor:  i7-8700k
Windows 10 1607

Captura log:
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Captura.Models.FFmpegWriter.WriteFrame(IBitmapFrame Frame)
   at Captura.Models.WithPreviewWriter.WriteFrame(IBitmapFrame Image)
   at Screna.Recorder.DoWrite()

FFmpeg log:
ffmpeg version N-92931-ge9564f7fea Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 25.100 / 56. 25.100
  libavcodec     58. 43.100 / 58. 43.100
  libavformat    58. 25.100 / 58. 25.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-d6a324fd-c58d-4eb4-a24a-b7358d5829f0':
  Duration: N/A, start: 0.000000, bitrate: 6635520 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 6400x1080, 6635520 kb/s, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
[hevc_qsv @ 0000020d423a0f40] Error initializing an internal MFX session: unsupported (-3)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by MathewSachin** [comment]
Please try recording a region smaller than 1920x1200

**Comment by ponmy** [comment]
Still no luck :(  Any advice would be appreciated.

Captura log:
System.Exception: System can't keep up with the Recording. Frames are not being written. Retry again or try with a smaller region, lower Frame Rate or another Codec.
   at Screna.Recorder.<DoRecord>d__17.MoveNext()

FFmpeg log:
ffmpeg version N-92931-ge9564f7fea Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 25.100 / 56. 25.100
  libavcodec     58. 43.100 / 58. 43.100
  libavformat    58. 25.100 / 58. 25.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-7f072d68-9ad3-44e6-b76f-1def9db7eb42':
  Duration: N/A, start: 0.000000, bitrate: 357868 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 654x570, 357868 kb/s, 30 tbr, 30 tbn, 30 tbc

**Comment by Kolobamanacas** [comment]
I have a similar issue. Recording works fine in all modes, except for the one I really needed (mp4 HEVC NNVENC | AAC). It also occurs in all recording modes: Fullscreen, Screen, Window and Region.

Here are specs of my laptop:
- Intel Core i7-7700HQ @ 2.80GHz, 4 Cores, 8 Logical Processors
- 16 GB DDR4-2400 (1200 MHz) SODIMM RAM (2x 8 GB Hyundai Electronics HMA81GS6AFR8N-UH)
- 512 GB NVMe M.2, PCI Express Toshiba THNSN5512GPUK NV SSD
- NVIDIA GeForce GTX 1050, 4 GB GDDR5 VRAM
- 15.6-inch, 1920x1080 Full HD IGZO IPS Display
- Intel Dual Band Wireless-AC 8265 Wi-Fi Adapter
- 97 Wh, 6-cell, Lithium Ion Battary
- Microsoft Windows 10 Pro x64 EN-US (1809, build 17763.292)

In this mode it falls with the following error:

System.IO.IOException

Message
Pipe is broken

Stack Trace
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Captura.Models.FFmpegWriter.WriteFrame(IBitmapFrame Frame)
   at Captura.Models.WithPreviewWriter.WriteFrame(IBitmapFrame Image)
   at Screna.Recorder.DoWrite()

Target Site
Void WinIOError(Int32)

Source
System.Core

HResult
-2147024664

---
And here is ffmpeg log.

ffmpeg version N-93069-g6dc06e979c Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 46.100 / 58. 46.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-41c39f62-ef9d-498b-9536-6bda42cad6e9':
  Duration: N/A, start: 0.000000, bitrate: 3981312 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 3981312 kb/s, 60 tbr, 60 tbn, 60 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_nvenc))
Press [q] to stop, [?] for help
[hevc_nvenc @ 000002c9f1660000] [Eval @ 000000cf34ffdde0] Undefined constant or missing '(' in 'high444p'
[hevc_nvenc @ 000002c9f1660000] Unable to parse option value "high444p"
[hevc_nvenc @ 000002c9f1660000] Error setting option profile to value high444p.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by Kolobamanacas** [comment]
> 
> 
> @Kolobamanacas, the NVENC encoders had not been tested since I don't have an NVIDIA GPU.
> Based on what I could figure out from the logs, I've done some changes.
> 
> Please test the build I'm attaching.
> [captura.zip](https://github.com/MathewSachin/Captura/files/2824652/captura.zip)

I confirm, the build you've attached works fine with NVENC. Thanks a lot for the fast reply.
