### ISSUE TITLE
Is it possible to publish screen with command-line?

### ISSUE THREAD

**Issue by code5381** [MathewSachin/Captura#361]
Hi MathewSachin.

First of all, Thank you for your amazing application.

I read [this](https://github.com/MathewSachin/Captura/issues/150) and it's possible to publish the screen using RTMP.

Is there any way to publish the screen with command-line?

Thanks in advanced.

Kevin.

**Comment by MathewSachin** [comment]
No, it hasn't been implemented for the command-line at the moment.

Also, streaming from the UI is not stable.
Twitch seems to work with a latency of 10s, but YouTube Live does not work.

**Comment by MathewSachin** [comment]
@code5381 I've done an implementation.

Please test dev build: https://ci.appveyor.com/api/buildjobs/fut7spsq0vd22sl2/artifacts/Captura-Portable.zip

Encoder is set as `stream:URL`

e.g. Twitch

```
captura-cli start --encoder stream:rtmp://live.twitch.tv/app/TWITCH_KEY
```

**Comment by MathewSachin** [comment]
Closing due to no reply. You may reopen if you wish to discuss further.

**Comment by lucosanta** [comment]
Hi,
I'm currently using Captura v8 version with captura-cli and I'm trying to start screen recording using stream with a Custom RTMP server. 
So, I typed:
`captura-cli start --encoder stream:rtmp://127.0.0.1:1935/live/<KEY>`

It works when I make it start using Captura GUI version while it doesn't work using CLI. 

Have you got any suggestion to let me do this?

**Comment by MathewSachin** [comment]
You'll have to use v9 beta for the command-line option.

**Comment by ericjang** [comment]
The GUI app has options for Custom stream but unlike the command-line option, there doesn't seem to be a way to pass in the rtmp address. Just wanted to confirm, this feature is not working yet for GUI, right?

**Comment by MathewSachin** [comment]
@ericjang You can set the custom streaming address on the FFmpeg settings page
