### ISSUE TITLE
Is it possible to change font used in text Overlay?

### ISSUE THREAD

**Issue by micbay** [MathewSachin/Captura#363]
Hi, is there a default font setting somewhere that can be used to change the overlay text font? If not, it'd be a nice feature add to be able to use different font text on different overlays or even just change the single font used by all for different applications. Depending on what is being annotated, the space to fit unobtrusively changes and being able to find a narrower or bolder type face would help in those instances.
Great application, though, thanks for sharing it.

**Comment by MathewSachin** [comment]
As of now there is no option for changing the font used.
Might try implementing this in the future.

#### ToDo
- List of fonts, font selection control
- Settings for Text, keystroke overlays
- Default font
- Support both `System.Drawing` and `DirectWrite`
