### ISSUE TITLE
Immunet false positive?

### ISSUE THREAD

**Issue by jstillings1** [MathewSachin/Captura#364]
Hey Mathew,
I run Immunet AV and it recently flagged these files as malicious
Have a look please
bass.dll has been detected as W32.81A0BF6F64-97.SBX.VIOC
is-KDM3N.tmp has been detected as W32.81A0BF6F64-97.SBX.VIOC

Perhaps your sound library your using has been modded as I have used this software for a very long time and love it with the same AV and zero issues.

**Comment by MathewSachin** [comment]
@jstillings1 Sorry for the late response.

I think it might be a false possitive. Try reporting it on Immunet AV website: http://www.immunet.com/false_positive

**Comment by jstillings1** [comment]
I found the root cause. Had an email marked Wells Fargo that used my email filter to land in my open me now folder. It installed Sality And efail and emotet . It was using GitHub auto update to distro to a ton of apps I use like visual studio light shot, anything that was auto updating it attached to. I installed webroot and it now says all ok

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
