### ISSUE TITLE
What happend?

### ISSUE THREAD

**Issue by happyZYM** [MathewSachin/Captura#367]
![](https://happyzym.gitee.io/pic/p/2019-02-17-19-17-05-120.png)

**Comment by happyZYM** [comment]
![](https://happyzym.gitee.io/pic/p/2019-02-17-19-17-05-120.png)

**Comment by MathewSachin** [comment]
As stated in the exception message, Captura is unable to capture consistently at current settings on your machine.

Try with a smaller region, lower FPS or lower quality.

**Comment by happyZYM** [comment]
@MathewSachin These are my settings ![](https://happyzym.gitee.io/pic/p/2019-02-17-19-28-59-559.png)
I was able to use this fps yesterday, and suddenly it was not work today. It will be useless after reinstallation.

**Comment by MathewSachin** [comment]
Please test this build: https://ci.appveyor.com/api/buildjobs/28o03r54p1qb162i/artifacts/Captura-Portable.zip

**Comment by MathewSachin** [comment]
Also, Captura is not fast enough for 60fps fullscreen capture.

**Comment by happyZYM** [comment]
@MathewSachin The problem is solved. Thank you!
