### ISSUE TITLE
Region Selector is off screen, and I can't get it back

### ISSUE THREAD

**Issue by SomethingsGoneWrong** [MathewSachin/Captura#368]
Is there any way to reset the position of the region selector?
Somehow it went off screen, and I see no way to get it back.

**Comment by MathewSachin** [comment]
For now, change to a different mode (e.g. Fullscreen) then exit Captura.
On starting Captura again and selecting Region mode, the selector should be within screen.

I've done some improvements on this which will be available in the next version.

**Comment by MathewSachin** [comment]
Closing due to no reply. You may reopen if you wish to discuss further.
