### ISSUE TITLE
Help on captura-cli.exe cmd line arguments.

### ISSUE THREAD

**Issue by SaddamBInSyed** [MathewSachin/Captura#369]
I want to record both audio, cameras and screen capture at a time with the time length of 30 minutes on Windows 7 PC.

could you please provide the captura-cli.exe cmd line arhguments for the same.

I am a bit confused.

please help.

**Comment by MathewSachin** [comment]
Try this: `captura-cli start --mic 0 --webcam 0 --length 10`

**Comment by MathewSachin** [comment]
Closing due to no reply. You may reopen if you wish to discuss further.
