### ISSUE TITLE
Twitch Streaming Lag

### ISSUE THREAD

**Issue by nabakin** [MathewSachin/Captura#374]
**Describe the bug**
It doesn't matter what the configuration is, any way that I stream to Twitch, I get massive amounts of stuttering.

**To Reproduce**
1. Start Captura
2. Enter a Twitch streaming key
3. Ensure the Pixel Format yuv420p is selected (yuv444p doesn't work on Twitch)
4. Select any Video Source that will display video
5. Switch the Video Encoder to "Streaming"
6. Start recording

**Expected behavior**
If you go to the corresponding Twitch Channel, the stream should be stuttering incredibly.

**Screenshots**
I might attach a video in a bit.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - RAM: 16GB
 - CPU: i7-4770k
 - Graphic Card: GTX 1070
 - Version: v8.0.0

**Additional context**
I've tried setting my FPS to both 30 and 60 (by removing the limit), I've messed around with custom codec settings, and have tried varying qualities using the quality selector, but it's still happening.

Should be noted that recording my desktop is no trouble at all.  There may be a _bit_ of stuttering, but nothing compared to what I get when streaming.

If this has been fixed in an earlier commit that has not been pushed to release, then sorry about this.  I couldn't find a commit or issue addressing this issue.

**Comment by MathewSachin** [comment]
I've noticed that it was a mistake from my side. The fps for streaming is not being set correctly by Captura. I'll try do a fix ASAP.

**Comment by MathewSachin** [comment]
I've done a fix. Here's a dev build to test: https://ci.appveyor.com/api/buildjobs/5ifdwkdfvdghh8oo/artifacts/Captura-Portable.zip

I'm unable to test it at the moment due to limitations with my institute network.
Please test it and let me know.

**Comment by nabakin** [comment]
Worked perfectly!  Thank you!
