### ISSUE TITLE
Mouse overlay rendering pixellated ?

### ISSUE THREAD

**Issue by ncoquelet** [MathewSachin/Captura#375]
Hi,

I'm discovering Captura and it's amazing.
The mouse overlay is very cool but the rendering is overly , pixellated

Is there any way to obtain a better rendering ?

![capture](https://i.ibb.co/vPPsbXw/Capture.png)

**Comment by MathewSachin** [comment]
This has already been fixed but not released yet.

Please check this dev build: https://ci.appveyor.com/api/buildjobs/m29qt216g8vf8g28/artifacts/Captura-Portable.zip

**Comment by ncoquelet** [comment]
Works like a charm.
Your software rocks
Congrat
