### ISSUE TITLE
Must Restart to Update Codec List

### ISSUE THREAD

**Issue by AntumDeluge** [MathewSachin/Captura#377]
When adding or removing custom codecs in *Configure -> FFmpeg -> Configure Codecs -> Custom*, the app must be restarted before the changes show up in FFmpeg Video Encoder list. Not a major bug at all. But I think it should update as soon as the new codec is created/deleted or the *Cofigure* dialog is closed.

- OS: Windows 10 64-bit

**Edit:** It can be updated by changing the type of encoding (e.g., "Gif", "SharpAvi", "Stream", etc.) & back to "FFmpeg". Still, might be a good idea to have it refresh automatically.

**Comment by MathewSachin** [comment]
You can click on the Refresh button to update the codecs in the list.

![home_li](https://user-images.githubusercontent.com/10654537/53691536-02a8e780-3da6-11e9-8beb-787a4a831221.jpg)

**Comment by AntumDeluge** [comment]
Ah, okay. Thank you. I still think it would be a good idea to automatically refresh the list when the dialog window is closed.
