### ISSUE TITLE
Records black screen, same result on more then 1 Windows 10 pc

### ISSUE THREAD

**Issue by jstillings1** [MathewSachin/Captura#381]
Mat, please check out this video of me leaving this post
![Screenshot_1](https://user-images.githubusercontent.com/29980804/54099426-417f0480-4387-11e9-8681-7230dbe0080e.png)
[2019-03-10-22-50-41.zip](https://github.com/MathewSachin/Captura/files/2950585/2019-03-10-22-50-41.zip)

**Comment by jstillings1** [comment]
I went back all the way to version 7 and same thing. I think it may be a .net framework change and because I have VS installed with .Net it is replacing whatever yours needs

**Comment by jstillings1** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/29980804/54099604-1cd75c80-4388-11e9-835c-a6586e59e650.png)
Added system specs

**Comment by MathewSachin** [comment]
Also, please provide the FFmpeg log. Available from Configure / FFmpeg

**Comment by jstillings1** [comment]
Sure can
ffmpeg version N-93252-gf948082e5f Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.102 / 58. 47.102
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-07e37293-a8f8-4993-93f8-8009e37d8502':
  Duration: N/A, start: 0.000000, bitrate: 663552 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 663552 kb/s, 10 tbr, 10 tbn, 10 tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, s16le, from '\\.\pipe\captura-3e7b4732-1d1b-464d-8754-7d28e32ff660':
  Duration: N/A, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 000002ea7d29d3c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000002ea7d29d3c0] profile Constrained Baseline, level 4.0, 4:2:0, 8-bit
[libx264 @ 000002ea7d29d3c0] 264 - core 157 r2935 545de2f - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=10 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=15.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'C:\Users\Jeremiah\Videos\New Captures\2019-03-10-23-03-10.mp4':
  Metadata:
    encoder         : Lavf58.26.101
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=-1--1, 10 fps, 10240 tbn, 10 tbc
    Metadata:
      encoder         : Lavc58.47.102 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 256 kb/s
    Metadata:
      encoder         : Lavc58.47.102 aac
frame=   18 fps=0.0 q=2.0 size=       0kB time=00:00:00.44 bitrate=   0.9kbits/s speed=0.878x    
frame=   23 fps= 23 q=1.0 size=       0kB time=00:00:00.92 bitrate=   0.4kbits/s speed=0.919x    
frame=   28 fps= 18 q=2.0 size=       0kB time=00:00:01.43 bitrate=   0.3kbits/s speed=0.947x    
frame=   33 fps= 16 q=2.0 size=       0kB time=00:00:01.92 bitrate=   0.2kbits/s speed=0.953x    
frame=   38 fps= 15 q=2.0 size=       0kB time=00:00:02.43 bitrate=   0.2kbits/s speed=0.966x    
frame=   43 fps= 14 q=2.0 size=       0kB time=00:00:02.92 bitrate=   0.1kbits/s speed=0.965x    
frame=   49 fps= 14 q=2.0 size=       0kB time=00:00:03.50 bitrate=   0.1kbits/s speed=0.989x    
frame=   54 fps= 13 q=1.0 size=       0kB time=00:00:04.00 bitrate=   0.1kbits/s speed=0.988x    
frame=   59 fps= 13 q=1.0 size=       0kB time=00:00:04.50 bitrate=   0.1kbits/s speed=0.989x    
frame=   64 fps= 13 q=1.0 size=       0kB time=00:00:05.00 bitrate=   0.1kbits/s speed=0.99x    
frame=   69 fps= 12 q=1.0 size=       0kB time=00:00:05.50 bitrate=   0.1kbits/s speed=0.989x    
frame=   72 fps= 12 q=-1.0 Lsize=     261kB time=00:00:07.10 bitrate= 301.6kbits/s speed=1.19x    
video:54kB audio:203kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.504310%
[libx264 @ 000002ea7d29d3c0] frame I:1     Avg QP:12.00  size:  7720
[libx264 @ 000002ea7d29d3c0] frame P:71    Avg QP: 1.52  size:   666
[libx264 @ 000002ea7d29d3c0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 000002ea7d29d3c0] mb P  I16..4:  0.1%  0.0%  0.0%  P16..4:  0.1%  0.0%  0.0%  0.0%  0.0%    skip:99.8%
[libx264 @ 000002ea7d29d3c0] coded y,uvDC,uvAC intra: 2.0% 2.9% 2.8% inter: 0.0% 0.1% 0.1%
[libx264 @ 000002ea7d29d3c0] i16 v,h,dc,p: 98%  1%  1%  0%
[libx264 @ 000002ea7d29d3c0] i8c dc,h,v,p: 98%  1%  1%  0%
[libx264 @ 000002ea7d29d3c0] kb/s:61.10
[aac @ 000002ea7d2a11c0] Qavg: 56100.910

**Comment by jstillings1** [comment]
BTW it worked fine until I installed Visual Studio and got the updates in it.

**Comment by MathewSachin** [comment]
@jstillings1 Does the latest beta release ([v9.0.0-beta3.1](https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta3.1/Captura-Portable.zip)) work?

**Comment by jstillings1** [comment]
Unable to test. I swapped to mint linux and do not own a windows machine anymore.



Sent via the Samsung Galaxy, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by MathewSachin** [comment]
Ok. Then I'm closing this issue. If anyone else experiences the same error, please reopen.
