### ISSUE TITLE
Application doesn't launch

### ISSUE THREAD

**Issue by alorwu** [MathewSachin/Captura#39]
I get the following error when i try to run the application 'System.ExecutionEngineException' was thrown. Reading about it online said it has got something to do with garbage collection. how do i go about this?

**Comment by MathewSachin** [comment]
Is the Screna packaged installed from NuGet? 
Also Let me know the OS you are using and the version of .Net Framework

**Comment by alorwu** [comment]
Yes I used NuGet. I'm running Windows 10 and my .Net framework is 4.5
And I use VS 2013

**Comment by MathewSachin** [comment]
Strange, this [MSDN page](https://msdn.microsoft.com/en-us/library/system.executionengineexception(v=vs.100).aspx) says System.ExecutionEngineException is **obsolete** from .Net 4.0.
Can you verify the exception and provide the `Exception.Message`

**Comment by alorwu** [comment]
Exception of type 'System.ExecutionEngineException' was thrown.

That's all it says. The code compiles but running it throws the above error. 
![screenshot 6](https://cloud.githubusercontent.com/assets/7726359/12817149/8ec7c5f2-cb61-11e5-954e-253118504b38.png)

**Comment by alorwu** [comment]
Thanks for the help Matthew, I decided to restart my machine and it works now. Thank you

**Comment by MathewSachin** [comment]
So it may be an issue with the OS
