### ISSUE TITLE
Allow user to square select the region instead of dragging and resizing the region

### ISSUE THREAD

**Issue by Priceincoding** [MathewSachin/Captura#394]
When users use multiple monitors and have messy applications open, it's kind of hard to drag and resize the square of region on the ultra thin border. I suggest adding a function for user to square select a region like what you do with a screen snipper when they want to increase convenience.

Thank you very much !

**Comment by MathewSachin** [comment]
I've added a button to Region selector for snapping to region.

Please test this dev build: https://ci.appveyor.com/api/buildjobs/6vmigwkgyjvaxcxl/artifacts/Captura-Portable.zip
