### ISSUE TITLE
Windows audio

### ISSUE THREAD

**Issue by Succ3s** [MathewSachin/Captura#399]
How do I record windows sound?

**Comment by MathewSachin** [comment]
1. Click on Microphone dropdown button
2. Enable audio checkbox
3. Enable your speaker device
4. Start Recording

![Screenshot (40)_LI](https://user-images.githubusercontent.com/10654537/56454321-58444e00-636c-11e9-9120-0b6b08bf1b88.jpg)

**Comment by Succ3s** [comment]
THX a lot!
