### ISSUE TITLE
Specific window capture

### ISSUE THREAD

**Issue by tanersenel** [MathewSachin/Captura#4]
Your work is very good. Thank you. But do not try to capture a specific window. When minimized, the window shrinks or open a new window on the full screen is still recording. When you will be able to fix this problem? Also How to add system sound except for the microphone sound ?

**Comment by MathewSachin** [comment]
Currently I have found no better solution

**Comment by tanersenel** [comment]
ok wait for you. thank you :)

**Comment by MathewSachin** [comment]
I had implemented the system sound capturing through wasapi loopback but it lacked synchronization

**Comment by MathewSachin** [comment]
I have implemented System Sound capture through Wasapi Loopback, though its not at all perfect
