### ISSUE TITLE
carshing when recording with region

### ISSUE THREAD

**Issue by nk932714** [MathewSachin/Captura#408]
**Describe the bug**
Two three times I am able to record but after that it start giving error

**To Reproduce**
1. Go to 'Region and define any region'
2. Click on 'Record button'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/29853208/57722269-a87caa80-76a3-11e9-9df9-ee891094df34.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - RAM: [e.g. 6GB]
 - CPU: [e.g. i5 2GHz]
 - Graphic Card: nVidia 525M
 - Version: [e.g. v62.0.0]

**Additional context**

**error log**
System.Exception: System can't keep up with the Recording. Frames are not being written. Retry again or try with a smaller region, lower Frame Rate or another Codec.
   at Screna.Recorder.<DoRecord>d__17.MoveNext()

**ffmpeg log**
```ffmpeg version N-93855-g21832b93d5 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 27.100 / 56. 27.100
  libavcodec     58. 52.101 / 58. 52.101
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 51.100 /  7. 51.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, rawvideo, from '\\.\pipe\captura-5fcc9803-7745-4eac-8183-44ca3d334ce6':
  Duration: N/A, start: 0.000000, bitrate: 62283 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 394x494, 62283 kb/s, 10 tbr, 10 tbn, 10 tbc
```

**Comment by MathewSachin** [comment]
Please try using the latest beta: [v9.0.0-beta3.1](https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta3.1/Captura-Portable.zip)

**Comment by nk932714** [comment]
oops! by mistake I wrote the graphic card version.
Ok I'll try the latest beta version. Hope this error is resolved in this version. 
Thanks for your comment

**Comment by nk932714** [comment]
Thanks newer version working flawlessly
