### ISSUE TITLE
Can't start the application

### ISSUE THREAD

**Issue by mertemin** [MathewSachin/Captura#41]
Solution builds fine. However, when you start it, the following exception is thrown:

> Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in ...\Captura-master\Captura-master\bin\Debug\Captura.vshost.exe'.
> 
> Additional information: The runtime has encountered a fatal error. The address of the error was at 0x4ed03c73, on thread 0xdf0. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

**Comment by MathewSachin** [comment]
This also happened with me a while ago.

**Comment by MathewSachin** [comment]
Try the release build
