### ISSUE TITLE
Negative-value window handles not supported

### ISSUE THREAD

**Issue by tobyr103** [MathewSachin/Captura#412]
**Describe the bug**
When using "win:" as source, the targeted application is not recorded if its handle is a negative number. In case anyone is wondering, yes, negative window handles are valid.

**To Reproduce**
Start a Windows GUI application and hope it has a negative winhandle. Then try initiating a recording with `captura-cli -s-ource win:${hWnd} `

**Expected behavior**
A recording should start, but it doesn't.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Looking at the code, looks like a small regex change will fix this. Replacing `^win:\d+$` with `^win:-?\d+$` should do the trick.

**Comment by MathewSachin** [comment]
Thank you for reporting the issue. A fix has been done.
