### ISSUE TITLE
Project doesn't run when compiled.

### ISSUE THREAD

**Issue by Pyroglyph** [MathewSachin/Captura#42]
You say that the LAME encoder is optional yet Screna throws an error when it can't load lameenc64.dll from the debug folder. I tried to fix it by getting lame_enc.dll (because there is no 64-bit version online anywhere) and putting it in the debug folder (named both lame_enc and lameenc64), but Screna still throws the same error.

Error information:
AudioViewModel.cs : Line 20
```
System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'Screna.Lame.Mp3EncoderLame' threw an exception.
  Source=Screna.SharpAvi
  TypeName=Screna.Lame.Mp3EncoderLame
  StackTrace:
       at Screna.Lame.Mp3EncoderLame.get_SupportedBitRates()
       at Captura.AudioViewModel..ctor() in Path-To-Captura\ViewModels\AudioViewModel.cs:line 49
       at Captura.MainViewModel..ctor() in Path-To-Captura\ViewModels\MainViewModel.cs:line 478
  InnerException: 
       HResult=-2146233052
       Message=Library 'Path-To-Captura\bin\Debug\lameenc64.dll' could not be loaded.
       Source=SharpAvi
       TypeName=""
       StackTrace:
            at SharpAvi.Codecs.Mp3AudioEncoderLame.SetLameDllLocation(String lameDllPath)
            at Screna.Lame.Mp3EncoderLame..cctor()
```

**Comment by MathewSachin** [comment]
Thank you pointing out the issue. It has been fixed. Both lameenc32.dll and lameenc64.dll are in the following Zip file in case you need them.

[lameenc.zip](https://github.com/MathewSachin/Captura/files/416500/lameenc.zip)
