### ISSUE TITLE
Region capture minimum

### ISSUE THREAD

**Issue by SupinePandora43** [MathewSachin/Captura#422]
region capture can't be samller than 300x300

**Comment by MathewSachin** [comment]
I've already done some work on this.
From the next release the minimum size will be 10x10.

**Comment by SupinePandora43** [comment]
in next prerelease?!

**Comment by MathewSachin** [comment]
Yes, also in the next pre-release

**Comment by SupinePandora43** [comment]
okay!
> ... in the next pre-release
