### ISSUE TITLE
Can I remove the overlays & is there a fps counter to see while I record?

### ISSUE THREAD

**Issue by Markhoss** [MathewSachin/Captura#431]
Ok so with the overlays I don't know if I activated them myself but I would really like to remove them for example right now I have the webcam & keystroke on from what I can see but there is no remove button. Also is there any way to see a fps counter which tells me when I am recording and when not? What would help is a colour which would indicate that as an example or even have the word recording/not recording so I can know for sure. Thanks for any answers and by the way this program seems great so thanks for making it free so much.:-)

**Comment by MathewSachin** [comment]
The keystrokes and webcam overlays are always shown in the overlay window but only included in the recording when they are enabled.
For keystrokes, there is a button on the main window.
Webcam shows only when you have selected a webcam from the dropdown on the main window.

I'm sorry there is no fps overlay and also overlays are not shown on the screen while recording but written into the video file.

If you just want a visual indication of whether a recording is in progress, the system tray icon changes to red while recording.

**Comment by Markhoss** [comment]
> The keystrokes and webcam overlays are always shown in the overlay window but only included in the recording when they are enabled.
> For keystrokes, there is a button on the main window.
> Webcam shows only when you have selected a webcam from the dropdown on the main window.
> 
> I'm sorry there is no fps overlay and also overlays are not shown on the screen while recording but written into the video file.
> 
> If you just want a visual indication of whether a recording is in progress, the system tray icon changes to red while recording.

Um so there is no way to disable the things I want to delete from the overlays?
A FPS overlay would be great it's a must have for people that don't want to minimize.

**Comment by MathewSachin** [comment]
FPS display has been implemented, will be available from next release, probably `v9.0.0-beta5`.
