### ISSUE TITLE
PLASE store the settings into app path on portable version

### ISSUE THREAD

**Issue by liesauer** [MathewSachin/Captura#438]
if i lost my settings when moving to another pc or just put it into my usb stick, it's not portable at all!

**Comment by liesauer** [comment]
now it stores into `%AppData%\Captura`.

**Comment by vatterspun** [comment]
For reference: #376

Ideally, fully portable tools write to the local app folder (usually to a subfolder like _\data_ or similar) and nowhere else.

**Comment by MathewSachin** [comment]
As you may see from #376, starting from the next release, Settings will be stored in the local app folder by default for portable builds.
Also, FFmpeg will be downloaded into the app folder too.

**Comment by megabugman** [comment]
downloaded the portable version, read all the bug reports, created a "Settings" folder where captura.exe resides, still settings files are created here:
C:\Users\%username%\AppData\Roaming\Captura

How to make this software truly portable by writing nothing outside the "Captura-Portable" folder?
