### ISSUE TITLE
Video plays back too fast after capture.

### ISSUE THREAD

**Issue by Pyroglyph** [MathewSachin/Captura#44]
See this video for sample (it was around 10 seconds long when I took it):
https://youtu.be/PtNPoYsXy-0

Edit: It only does this if the frame rate of the video exceeds 30fps.

**Comment by MathewSachin** [comment]
This should be happening because the screenshots are actually being captured at a frame rate less than specified.
It could happen that frames can't be captured that fast using the current methods on normal machines.

**Comment by Pyroglyph** [comment]
Okay, so now I'm wondering how other applications like Fraps, Dxtory, OBS, and NVidia Share achieve 60fps recordings.

**Comment by MathewSachin** [comment]
Most of them use complex things like copying from DirectX Back-Buffer

**Comment by Pyroglyph** [comment]
Sounds like a nightmare for someone of my coding expertise...
