### ISSUE TITLE
Taiwan is the territory of China

### ISSUE THREAD

**Issue by WaringHu** [MathewSachin/Captura#448]
# Taiwan is the territory of China

Dear developer, In the process of using your software, I found a serious error.

## A serious mistake

- Chinese (Simplified, PRC) (中文(中国))
- Chinese (Traditional, Taiwan) (中文(台灣))

As a Chinese, I think this is a very serious mistake, which may make many Chinese users who use the software sad. I hope that you can correct this error in the new version.

## My advice

- Chinese (Simplified) (中文简体)
- Chinese (Traditional) (中文繁体)

Thank you !

My English is a poor machine translation.

**Comment by XxxxxXq** [comment]
I support the revision, this problem makes me have to delete the traditional Chinese.
Thank you, dear author

**Comment by MathewSachin** [comment]
Thank you for reporting the issue. I'm sorry if I offended anyone, I'm not familiar with the Chinese language. I've made the correction as you suggested. Please see the attached image.

![Screenshot (61)](https://user-images.githubusercontent.com/10654537/70336782-c98b2f80-186f-11ea-8e46-b08638895fcf.png)

**Comment by WaringHu** [comment]
Extremely grateful to the author!!!

**Comment by vatterspun** [comment]
Just like English, all languages have wide divisions in usage and syntax.  There are areas of mainland China where you can speak your own dialect and no one will understand you.  The country is unified in some ways by it's reasonably consistent written language, but there are dramatic variations.  That's nothing to do with China or its people, that's just how language works.  Wikipedia gives some additional illustration between the different versions: https://en.wikipedia.org/wiki/Comparison_of_national_standards_of_Chinese

> Mandarin Chinese, branch of Chinese spoken in northern and southwestern China https://en.wikipedia.org/wiki/Mandarin_Chinese
> 
>     Standard Chinese or Modern Standard Mandarin, the official language of China https://en.wikipedia.org/wiki/Standard_Chinese
>     Taiwanese Mandarin, the official language in Taiwan, mostly mutually intelligible with Standard Chinese https://en.wikipedia.org/wiki/Taiwanese_Mandarin
