### ISSUE TITLE
EntryPointNotFoundException by GetAudioSource

### ISSUE THREAD

**Issue by Kiwibomber** [MathewSachin/Captura#45]
i'm using the encoding-dlls from http://www.rarewares.org/mp3-lame-bundle.php in the 64bit-version.

and always i get this exception:

![issue](https://cloud.githubusercontent.com/assets/18040502/18242686/c3079de4-7357-11e6-9d3e-3b78ff992e57.jpg)

Sorry for my bad english.

**Comment by MathewSachin** [comment]
Try the dll in this [zip file](https://github.com/MathewSachin/Captura/files/416500/lameenc.zip)

**Comment by Kiwibomber** [comment]
Thank you for the files but the sound now sounds like a jet engine during takeoff.

**Comment by MathewSachin** [comment]
Captura has abandoned support for lame and now uses FFMpeg for audio encoding which works fine now.
