### ISSUE TITLE
Screenshot capture to clipboard buffer

### ISSUE THREAD

**Issue by tantoinet** [MathewSachin/Captura#452]
**Is your feature request related to a problem? Please describe.**
Taking a screenshot then pasting it to an email or an Editor is super handy. The only way to acheive this using Captura is opening again the image in mspaint then copy/pasting it from there to a mail client (eg. Outlook)

**Describe the solution you'd like**
Copying the captured image to the clipboard buffer so we can paste it to an email client or any image editor (mspaint, gimp, ...).
This is possible using Gadwin PrintScreen.

**Additional context**
Captura was only tested on Win 10.0.18362 Build 18362 x64.

**Comment by MathewSachin** [comment]
This is already possible. There's a button to enable this.
Which version of Captura are you using?

**Comment by tantoinet** [comment]
I'm using v9.0.0 stable.
where can I enable this? From the UI, the only option I've found was "Copy Output file path to Clipboard" from the "Configure" menu.

**Comment by MathewSachin** [comment]
v9.0.0 is not stable yet. Please recheck the version you are using then I'll let know how to enable the option.

**Comment by MathewSachin** [comment]
I'm sorry it's my mistake that the pre-release builds are being displayed as stable.

I've highlighted the option for v9.0.0-beta3.1

![Inked2019-11-05-18-43-54_LI](https://user-images.githubusercontent.com/10654537/68210850-69993300-fffc-11e9-90f6-4e64df939557.jpg)

**Comment by tantoinet** [comment]
That's the same version I'm using :)
I've tried your advise and it works as expected, thank you!
