### ISSUE TITLE
Can't use date variable for folder creation

### ISSUE THREAD

**Issue by EthanPhoenix** [MathewSachin/Captura#458]
**Is your feature request related to a problem? Please describe.**
This might be a bug but I am uncertain so I opt to have it as a feature request.
When setting the filename format, it would be great if I can place `\` to indicate a folder. This way I can have a folder per date etc. As it currently stand, the `\` character is not allowed in the File Name Format.
It would be great if I can have a date folder and in it the files of that specific date created automatically.

**Describe the solution you'd like**
Just like with filename, the ability to have date variables as folder. In essence the permission to add a `\` in the filename.

**Describe alternatives you've considered**
None.

**Additional context**
None.

Thank you!

**Comment by MathewSachin** [comment]
This is a good suggestion.
I'm adding support for both `\` and `/`.

I've done an implementation of this. Here's a dev build to test: https://ci.appveyor.com/api/buildjobs/o76lxx8a5ew56fbg/artifacts/temp%2FCaptura-Portable.zip

As this is a testing build, there might be other problems. But, you can at least take a screenshot to see that this works.

**Comment by EthanPhoenix** [comment]
WOW! you are quick!
I just tested it and it works like a charm!
Thank you so much!
