### ISSUE TITLE
When "☑️ Playback audio recorded in real time" is ticked, my "start" sound effect plays repeatedly

### ISSUE THREAD

**Issue by hi2u** [MathewSachin/Captura#459]
**Describe the bug**

**To Reproduce**
1. In the `Configure` window, under the `Sounds` section, for `Start:`, set an audio file to be played when recording begins.
2. On the `Screen Recording` tab, under `Audio`, tick the box: `☑️ Playback audio recorded in real time`.
3. Start recording.
4. The chosen sound effect file is played repeatedly until recording is stopped.  

The repeating audio overlaps and layers up with a slight offset, i.e. it doesn't wait until the whole sound effect has ended to start a new loop.

**Expected behavior**

The starting sound effect file should only play once.

**Desktop:**
 - OS: Windows 10 Pro (64bit) 10.0.18363 N/A Build 18363
 - RAM: 32GB
 - CPU: [Intel® Core™ i7-7700 Processor](https://ark.intel.com/content/www/us/en/ark/products/97128/intel-core-i7-7700-processor-8m-cache-up-to-4-20-ghz.html)
 - 1st Graphics Card: Intel HD Graphics (iGPU built into the CPU)
 - 2nd Graphics Card: NVIDIA GeForce GTX 750
 - Captura Version: v8.0.0 - installed via https://chocolatey.org/packages/captura/8.0.0

Let me know if it would be more helpful to make a screen recording to demonstrate.

**Comment by MathewSachin** [comment]
I had already removed the `Playback audio recorded in real time` feature in v9 pre-release and do not plan to add it back.

It was removed for easier usage of open-source NAudio library which now replaces the proprietary BASS library used earlier.

**Comment by hi2u** [comment]
Ah fair enough.  

Thanks for your work on this program, it's really great!
