### ISSUE TITLE
can u help me?

### ISSUE THREAD

**Issue by zhenhechui** [MathewSachin/Captura#46]
now i want record both side audio in/out.
but now this project cant record both.
i hope u help me.

**Comment by MathewSachin** [comment]
I have not tried that currently.
BTW, you could look if it is possible with NAudio, since Captura uses NAudio.

**Comment by zhenhechui** [comment]
i tought it is possible.
but now i dont know way.
i hope u tell me the ways or try it.

**Comment by MathewSachin** [comment]
Hi

I have put up an experimental version on [mix-mic-loopback](https://github.com/MathewSachin/Captura/tree/mix-mic-loopback) branch.

It uses [ManagedBass](https://github.com/ManagedBass/ManagedBass) instead of [NAudio](https://github.com/naudio/naudio).

**Comment by MathewSachin** [comment]
@zhenhechui, this feature is now present in master branch
