### ISSUE TITLE
x64 version

### ISSUE THREAD

**Issue by SupinePandora43** [MathewSachin/Captura#461]
it will give more performance on x64 computers

**Comment by vatterspun** [comment]
Workaround note: that those who are serious about speed improvements can use low compression recordings and then go over them a second time with optimized, 64-bit encoding tools.

**Comment by ivysrono** [comment]
+1

**Comment by MathewSachin** [comment]
Now, that we don't depend on native libraries like `bass.dll`, doing this was pretty trivial.
This build should run as 32-bit on 32-bit systems and 64-bit on 64-bit systems.
Not much tested though, if this causes any unexpected problems.

Please note that this is a development build and is very different from the released versions.
https://ci.appveyor.com/api/buildjobs/pb3s8vlm9g27j4eq/artifacts/temp%2FCaptura-Portable.zip
