### ISSUE TITLE
Requesting a hotkey to directly open to "Region" capture mode and click + drag mouse to adjust region placement.

### ISSUE THREAD

**Issue by MostHated** [MathewSachin/Captura#466]
Hey there,
    I spend a lot of time doing game developemt and often times I want to try and record something specific rather quickly, so it would be great to be able to have one hotkey which directly brings up region capture (the main application does not have to be visible, it could stay on the task bar and only bring up the region) and then the first click of the mouse begins one corner of the region capture window and then you hold and drag to complete the sizing of the region, which would then allow for hitting a second hotkey to begin recording straight away. 

Thanks!
-MH

**Comment by MathewSachin** [comment]
I've implemented this as `Toggle Region Picker`. Reason being you might also want to hide the region picker after you are done recording.

**Comment by MostHated** [comment]
Great news. I will give it a try. :D

**Comment by MathewSachin** [comment]
Just so you know, it isn't released yet.
You can check it on the latest development build

**Comment by MostHated** [comment]
It's v9.0.0-beta4, yeah? I had just downloaded that was an it's installing now.

**Comment by MathewSachin** [comment]
No it's not in it. I started working on this after that release was done. Wait a second, I give you the link to a development build

**Comment by MathewSachin** [comment]
Here you go
https://ci.appveyor.com/api/buildjobs/9dh9gxowjx1ohnpw/artifacts/temp%2FCaptura-Portable.zip

**Comment by MostHated** [comment]
Awesome, that works quite well! I didn't realize I would, but I rather like the fact that the region remains until you hit the hotkey again, in case you want to continue recording or something. 

That being said, though, I see that the controls are no longer present around the frame. That really isn't much of a problem as oftentimes they would end up being off-screen or something anyways if I am doing a larger recording. Since they are gone, though, is there, or can there be a way to enable the ability that as soon as you release from dragging the region that it will begin recording straight away?  Then maybe, once you hit Esc or similar, it finishes the recording? 

Thanks for all your hard work on this application. It will definitely be my top choice for capture now. 👍

**Comment by MathewSachin** [comment]
Glad to you liked the changes.

> they would end up being off-screen or something anyways if I am doing a larger recording

Exact reason why many users asked them to be removed.

> enable the ability that as soon as you release from dragging the region that it will begin recording straight away? Then maybe, once you hit Esc or similar, it finishes the recording?

I can make the recording start immediately. But, I think it's better this way. You get time to confirm that you selected the correct region. Also, starting the recording is also as simple as pressing a hotkey.

**Comment by MostHated** [comment]
I can definitely see that way as a use case, but during testing and development of video games, I often have use cases in which being able to quickly begin capturing is more important than the region being perfectly positioned. If I am trying to produce input a specific way with the mouse and keyboard, being able to hit hotkey once to activate, drag the box, then go right back to my keys and mouse position without having to worry about another step in between is very helpful. 

If perhaps, there was just a checkbox or similar to enable or disable the automatic recording, I would imagine that should cover both use cases adequately?

**Comment by MathewSachin** [comment]
Hmm... The checkbox idea should work.
I'll try implementing this tomorrow morning.

**Comment by MathewSachin** [comment]
Oops. I had implemented this yesterday but forgot to give you a link to the build.
Check if this build is satisfactory: https://ci.appveyor.com/api/buildjobs/ukwe695jxddombm0/artifacts/temp%2FCaptura-Portable.zip

**Comment by MathewSachin** [comment]
@MostHated Should I finalize this feature?

**Comment by MostHated** [comment]
Sorry for the late reply. It seems to be working well. I did a few test records in which I was able to hit the hotkey, do a quick drag of an area, it began recording, I then hit stop and then clicked on my video from the notification and it looked just as expected. 

From what I can tell, I would say it is good. 👍

**Comment by MostHated** [comment]
I just wanted to give me feedback after having used this for a week or so. I must say that while the UI redesign looks nice, it seems to be a slight bit inconvenient to have to go into the settings each time I want to change the framerate or quality of the capture. It was rather nice to have it right there on the main window to change the slider quickly if I wanted to have a lower quality longer capture with a smaller file size, or if I wanted to max it out for a super high-quality clip.

What might be nice is to be able to save multiple different "capture profiles" that retain all the current recording settings that you could switch between, either on the main interface or via hotkey to quickly go from high quality to low quality.
