### ISSUE TITLE
If the output drive/location no longer exists, 5 separate error windows come up, and the application won't let you change the location.

### ISSUE THREAD

**Issue by MostHated** [MathewSachin/Captura#468]
**Describe the bug**
If the output drive/location no longer exists, 5 separate error windows come up, and the application won't let you change the location. I tried looking in the files for a config that I could maybe change manually but didn't see one. Click on "set output folder" simply doesn't do anything.

**To Reproduce**
You should be able to test it with a flash drive or external hard drive. I was using an external drive to store them which I then had to remove and I forgot to change the output folder. So set the output to a drive, close application, remove drive, start it back up. 

**Expected behavior**
I believe it should start normally, let you know that the destination is no longer valid, and either go back to the default, or force you to choose a new location.

**Screenshots**
https://i.imgur.com/AtH9gGx.png

**Comment by MathewSachin** [comment]
I've added a check to see if the output drive exists. If not, then fallback to default output directory.

Here's a build to test: https://ci.appveyor.com/api/buildjobs/9fydji5meag3n966/artifacts/temp%2FCaptura-Portable.zip.
Please note that this build is a dev build and the features in it are considerably different from those in releases.

If you want to change the config file, it is located at `%AppData%\Captura\Captura.json` for setup builds, and in `Settings` folder in the app directory for Portable builds.
There is an `OutPath` option in the file which you can change manually if needed.
