### ISSUE TITLE
Adding an overlay/animation when you scroll using mouse wheel

### ISSUE THREAD

**Issue by i-give-up** [MathewSachin/Captura#480]
Is it possible to add an overlay/animation when you scroll using mouse wheel?

Here's a video showing how Keypress OSD does it: https://streamable.com/ozw8m. Basically, a downward triangle is drawn around mouse cursor when you scroll down, and upward triangle when you scroll up.

**Comment by MathewSachin** [comment]
Give this build a try: https://ci.appveyor.com/api/buildjobs/toe7u8h5v5n1jt9a/artifacts/temp%2FCaptura-Portable.zip

I've added an option on `Settings/Overlays/Mouse` page called `Display Scroll`. This is on by default.
When you scroll, up/down arrows are displayed with the click overlay circle.
Size of the arrow is automatically determined according to the click radius setting.

Arrow color is currently set to click circle border color. I'll add a separate option for it too later.
Also, should we have a separate color for the scroll circle? Left, Right and Middle clicks can already be set to different colors.
