### ISSUE TITLE
Overlays transparency

### ISSUE THREAD

**Issue by Benito1111** [MathewSachin/Captura#488]
in Overlays; keystrokes; Back Color; when set to transparency (alpha 0) it don't works when recording(always back color with the font),
![CapturaRecording](https://user-images.githubusercontent.com/23515041/74399627-6a0a4c80-4de9-11ea-811b-40570b9b72bf.PNG)

 but work on the preview page(no color showed)
![CapturaPreview](https://user-images.githubusercontent.com/23515041/74399635-6e366a00-4de9-11ea-8b3c-7bc97a53c3b6.PNG)

**Comment by MathewSachin** [comment]
Thank you for reporting.
I've just now done a fix for this.
