### ISSUE TITLE
How to turn off desktop notifications

### ISSUE THREAD

**Issue by jabbo126** [MathewSachin/Captura#489]
Is there i way to disable screenshot desktop notificiations? In some apps it is always on top so it is visible on next screeenschot. I can't find solution.

![2020-02-12-14-39-51](https://user-images.githubusercontent.com/35731184/74456815-adb39380-4e87-11ea-86ba-3759af9503d7.jpg)

**Comment by MathewSachin** [comment]
Uncheck `Show system tray notifications`.
It should be a checkbox in settings.
Its location depends on the version of Captura you're using.

**Comment by jabbo126** [comment]
> Uncheck `Show system tray notifications`.
> It should be a checkbox in settings.
> Its location depends on the version of Captura you're using.

Captura v9.0.0 2020, stable up to date, really can't finde the setting

**Comment by MathewSachin** [comment]
Open settings window by clicking the button on the top-left corner, then go to Tray Icon page.
Please see the attached screenshots.

![Inked2020-02-13-23-03-05_LI](https://user-images.githubusercontent.com/10654537/74461979-617f4800-4eb5-11ea-92ef-b9693a9a7c7b.jpg)
![2020-02-13-23-03-23](https://user-images.githubusercontent.com/10654537/74461995-68a65600-4eb5-11ea-9d58-b5973f8e494c.png)

**Comment by jabbo126** [comment]
Ohh, i see now, problem is in translation in my language (Czech), the option says (in translation to EN):"Show **Icon** In System Tray" - it is wrong translation. So i had no idea that it do this. Thanks for your help!
