### ISSUE TITLE
error

### ISSUE THREAD

**Issue by YVRcanucks** [MathewSachin/Captura#498]
when I use "Captura", it show up this error.

System.Exception: System can't keep up with the Recording. Frames are not being written. Retry again or try with a smaller region, lower Frame Rate or another Codec.
   場所 Screna.Recorder.<DoRecord>d__17.MoveNext()

I have NO idea, where set up frame rate. 
I change file type "mp4" to another. but it still show up this error.
I don't know you already answer this error. I'm sorry if you answer it.

**Comment by MathewSachin** [comment]
Try using a newer version, specifically v9.0.0-beta4.

Heres the download link: https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta4/Captura-Portable.zip
