### ISSUE TITLE
How to convert Keymap

### ISSUE THREAD

**Issue by akcansoft** [MathewSachin/Captura#510]
I use Turkish keyboard.
Turkish characters like `ÜĞİŞÇÖ` look different in `Captura / Overlays / Keystrokes`.

I want to adapt the `en.json` file in the `Captura / Keymaps` folder to Turkish.
How can I do that.

**Comment by MathewSachin** [comment]
`Mappings` is an array containing multiple mapping objects which have 2 properties `On` and `Keys`.

A mapping is triggered if any of the item in its `On` array matches.
You can specify states for `CapsLock` (default = off) and `Shift`, `Control`, `Alt` (default = not pressed).
The values in the Keys are based on [System.Windows.Forms.Keys enum](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=netframework-4.8)

e.g. If Shift is On **OR** if CapsLock is On, we want letters to be capital
```
"On": [
    { "Shift": true },
    { "CapsLock": true }
]
```

e.g. If (neither shift nor capslock) is pressed or if both Shift and CapsLock are pressed we want small letters.
```
"On": [
    { },
    { "CapsLock": true, "Shift": true }
]
```

An easy way to make a keymap would be to, create a copy of mappings file `en.json` and then open Notepad and Captura side by side.
Start a recording with keystroke capture on. While you type, if the preview does not show the key as the same as you type in notepad, update the keymap file.

**Comment by akcansoft** [comment]
Thanks. I understand.
Now I am preparing the `tr.json` file(for Turkish-Q Keyboard) by making use of the en.json file.
I will send the file when the process is completed.

**Comment by akcansoft** [comment]
Turkish-Q keymap file is OK.
Pull Request: https://github.com/MathewSachin/Captura/pull/513
