### ISSUE TITLE
After recording, it shows 'Saving Videos', and the video isn't available

### ISSUE THREAD

**Issue by enor2017** [MathewSachin/Captura#512]
## Description
When I finished recording, it shows 'Saving Videos', which should quickly change into 'Video Saved' normally. I've waited for half an hour, but the video is still not unavailable. It has occured for several times, could you help me fix that?

##  Steps I took
1、Choose a specific window to record
2、Record (Contain Audio)
3、Finish recording

## Logs
```
ffmpeg version git-2020-02-06-343ccfc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 39.100 / 56. 39.100
  libavcodec     58. 68.100 / 58. 68.100
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 74.100 /  7. 74.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, rawvideo, from '\\.\pipe\captura-56165101-367b-4e18-9a8d-0d020b2cb8d1':
  Duration: N/A, start: 0.000000, bitrate: 449032 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1254x746, 449032 kb/s, 15 tbr, 15 tbn, 15 tbc
```

## Screenshots
I'm unable to find a screenshot of the notification which told me it was 'Saving Videos'. The screenshot below shows there're two videos (showed in gray fonts) unavailable, which is exactly 'Saving'.

![captura crashed](https://user-images.githubusercontent.com/36726166/78112162-6336a800-7430-11ea-8060-e2a43eb17060.png)

**Comment by MathewSachin** [comment]
From your FFmpeg log, I can see that FFmpeg didn't start writing frames.

Try the beta v9.0.0-beta4, I've added some checks so that this does not happen even if some frames need to be skipped.

You can download it from this link: https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta4/Captura-Portable.zip

**Comment by enor2017** [comment]
> 
> 
> From your FFmpeg log, I can see that FFmpeg didn't start writing frames.
> 
> Try the beta v9.0.0-beta4, I've added some checks so that this does not happen even if some frames need to be skipped.
> 
> You can download it from this link: https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta4/Captura-Portable.zip

Thanks, I'll try it. So it means that the crashed video can't be recovered?

**Comment by MathewSachin** [comment]
Sadly, no, from the FFmpeg log, I can see that FFmpeg didn't finish writing to disk.

**Comment by enor2017** [comment]
> 
> 
> Sadly, no, from the FFmpeg log, I can see that FFmpeg didn't finish writing to disk.

OK. Thanks a lot.
