### ISSUE TITLE
Can not start record with a wrong message

### ISSUE THREAD

**Issue by BasinChen** [MathewSachin/Captura#516]
**Describe the bug**
MESSAGE：HRESULT:[0x8899000C], Module: [SharpDX,Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget] 存在可以恢复的演示错误。调用方需要重新创建、重新渲染整个帧，并尝试重新显示

**Args**
ARGS:
-------------
-thread_queue_size 512 -framerate 30 -f rawvideo -pix_fmt rgb32 -video_size 1920x1080 -i \\.\pipe\captura-019b807f-720c-4cf9-9c6d-b2b133414006 -r 30 -vcodec libx264 -crf 0 -pix_fmt yuv420p -preset ultrafast "C:\Users\lyc99\Documents\Captura\2020-04-05-20-55-28.mp4"

**Output**
OUTPUT:
-------------
ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.100 / 56. 42.100
  libavcodec     58. 75.100 / 58. 75.100
  libavformat    58. 41.100 / 58. 41.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, rawvideo, from '\\.\pipe\captura-019b807f-720c-4cf9-9c6d-b2b133414006':
  Duration: N/A, start: 0.000000, bitrate: 1990656 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 1990656 kb/s, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0000019369c7c800] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000019369c7c800] profile High 4:4:4 Predictive, level 4.0, 4:2:0, 8-bit
[libx264 @ 0000019369c7c800] 64 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'C:\Users\lyc99\Documents\Captura\2020-04-05-20-55-28.mp4':
  Metadata:
    encoder         : Lavf58.41.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.75.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=0.0 Lsize=       8kB time=00:00:00.00 bitrate=977353.8kbits/s speed=0.0021x    
video:7kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.234066%
[libx264 @ 0000019369c7c800] frame I:1     Avg QP: 0.00  size:  6631
[libx264 @ 0000019369c7c800] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000019369c7c800] coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0%
[libx264 @ 0000019369c7c800] i16 v,h,dc,p: 99%  0%  1%  0%
[libx264 @ 0000019369c7c800] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0000019369c7c800] kb/s:1591.44

**Stack Trace**

   在 SharpDX.Result.CheckError()
   在 DesktopDuplication.Direct2DEditorSession.EndDraw()
   在 DesktopDuplication.Direct2DEditor.GenerateFrame()
   在 Screna.Recorder.<>c__DisplayClass14_0.<DoRecord>b__2()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Screna.Recorder.<DoRecord>d__14.MoveNext()

**Desktop (please complete the following information):**
 - OS: [ Windows 10 Home 18363.720]
 - RAM: [8GB]
 - CPU: [i5 8550U]
 - Graphic Card 1:  Intel(R) UHD Graphics 620 (version: 26.20.100.7262)
 - Graphic Card 2:  NVIDIA GeForce MX150 (version: 24.21.13.9836)
 - Captura Version: [v8.0.0]

**Comment by MathewSachin** [comment]
I still don't have a solution for this but I'm closing this since it is same as #492.
If you have anything to add, comment on that issue.
