### ISSUE TITLE
Who is this company : winuwp ? Install from the microsoft Store

### ISSUE THREAD

**Issue by nlebellier** [MathewSachin/Captura#521]
Hi,

i found your software via the Micro$oft  store as a free application made by a company named **winuwp**.

![image](https://user-images.githubusercontent.com/4880966/78760921-257ed580-7982-11ea-9d4a-d420d9fa3ab9.png)

Is it you ?

![image](https://user-images.githubusercontent.com/4880966/78760373-5b6f8a00-7981-11ea-9efc-c097e714da24.png)

your software is pretty good even if i met an issue about ffmpeg but i open another issue ticket for this.

Thanks for your answer.

**Comment by vatterspun** [comment]
Confirmed.  Thanks for posting about that.  Added a note to the illegal rebrand thread that you posted to.
