### ISSUE TITLE
Black screen while record excel window

### ISSUE THREAD

**Issue by darkcike** [MathewSachin/Captura#526]
When i try to record screen with an **excel file opened**, if i **maxium the excel window** and stop all operations with nouse or keyboard,  the video will be black screen and only the cousor will be 
 seen.when i **move the mouse**, it will be work as **normal** , when i **stoped**, the video gose **black** again.

**Desktop (please complete the following information):**
 - OS: WIN10 on macbook pro
 - RAM: 8GB
 - CPU: i5 8259u
 - Graphic Card:
 - Captura Version: v9.0.0-v9.0.0beta4 all version

**Additional context**
![17-27-58 00_00_00--00_00_03](https://user-images.githubusercontent.com/22463630/79211083-4e1e3800-7e78-11ea-9e11-20eae9fa7ec7.gif)

**Comment by darkcike** [comment]
Has the same problem with word. office version is 2010

**Comment by darkcike** [comment]
This disappeard when i check the use GDI instead of desktop duplication box. So, should i just close this issue?

**Comment by SupinePandora43** [comment]
https://www.youtube.com/channel/UCx562C3M3L6j44D1Y7CLTyg
