### ISSUE TITLE
Add the option to use default audio device.

### ISSUE THREAD

**Issue by klaytoncavalcante** [MathewSachin/Captura#528]
Currently, when recording you can select the audio source from a drop down that lists all options, but if you, for example, plug a headset, it will not change automatically to the headset to record voice.

It would be nice to have a option like "Input - Default device" and "Output - Default device" to record desktop sounds.

One more suggestion is to the options to record audio from input and output devices.

Thank you very much for this awesome application.
It works really well and is impressively good.

Cheers!

**Comment by campelo** [comment]
Hello @klaytoncavalcante! 

Which version are you using?

Because I've tried this at v9.0.0-beta4 version and works fine.
![image](https://user-images.githubusercontent.com/4963840/79690338-f55bf000-8227-11ea-8414-e06dbfda510e.png)

**Comment by klaytoncavalcante** [comment]
I was not in Beta. I was using the default version available in https://mathewsachin.github.io/Captura/download/ .
I will install the beta version then. Thank you very much and sorry for not checking the beta before talking about new features.

Have a nice day and thanks for this awesome tool!
