### ISSUE TITLE
How to set constant frame rate in captura

### ISSUE THREAD

**Issue by pmp55** [MathewSachin/Captura#530]
To address the out of sync problem, I'd like to know how to preset constant frame rate ( like 25 fps) for the video recording.  Any help is appreciated!

**Comment by MathewSachin** [comment]
Captura only supports constant frame rate (no variable frame rate support).
The frame rate (FPS) can be set on the Settings/Video screen.

**Comment by pmp55** [comment]
@MathewSachin  Thanks!
