### ISSUE TITLE
Can take screenshots, but cannot start recording

### ISSUE THREAD

**Issue by Gugu7798** [MathewSachin/Captura#541]
**Can't start recording video**

SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: 存在可以恢复的演示错误。调用方需要重新创建、重新渲染整个帧，并重新尝试显示。

   在 SharpDX.Result.CheckError()
   在 DesktopDuplication.Direct2DEditorSession.EndDraw()
   在 DesktopDuplication.Direct2DEditor.GenerateFrame()
   在 Screna.Recorder.<>c__DisplayClass14_0.<DoRecord>b__2()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Screna.Recorder.<DoRecord>d__14.MoveNext()

![1](https://user-images.githubusercontent.com/64693329/80866269-54a60f80-8cc0-11ea-98e3-612ba081cc8f.png)

Operating system: Windows10
Memory: 8GB
CPU: i5 2.30GHz
Graphics card:
Captura version: v9.0.0

**Comment by Gugu7798** [comment]
It was possible to record video when it was last used, probably last month

**Comment by Gugu7798** [comment]
I download the new version to see if I can solve this problem

**Comment by Gugu7798** [comment]
ARGS:
-------------
-thread_queue_size 512 -framerate 10 -f rawvideo -pix_fmt nv12 -video_size 1920x1080 -i \\.\pipe\captura-e598a9af-fda9-4c15-b165-aea5dfe4849d -r 10 -vcodec libx264 -crf 0 -pix_fmt yuv420p -preset ultrafast "D:\Ying Yong\零碎小应用\Captura  录制\Captura-Setup  录制\文件\2020-05-07-17-49-47.mp4"

OUTPUT:
-------------
ffmpeg version git-2020-05-04-5767a2e Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 43.100 / 56. 43.100
  libavcodec     58. 82.100 / 58. 82.100
  libavformat    58. 42.102 / 58. 42.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, rawvideo, from '\\.\pipe\captura-e598a9af-fda9-4c15-b165-aea5dfe4849d':
  Duration: N/A, start: 0.000000, bitrate: 248832 kb/s
    Stream #0:0: Video: rawvideo (NV12 / 0x3231564E), nv12, 1920x1080, 248832 kb/s, 10 tbr, 10 tbn, 10 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000001a1ded80440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000001a1ded80440] profile High 4:4:4 Predictive, level 4.0, 4:2:0, 8-bit
[libx264 @ 000001a1ded80440] 64 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=10 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'D:\Ying Yong\闆剁灏忓簲鐢╘Captura  褰曞埗\Captura-Setup  褰曞埗\鏂囦欢\2020-05-07-17-49-47.mp4':
  Metadata:
    encoder         : Lavf58.42.102
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1920x1080, q=-1--1, 10 fps, 10240 tbn, 10 tbc
    Metadata:
      encoder         : Lavc58.82.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=    4 fps=0.0 q=-1.0 Lsize=      34kB time=00:00:00.30 bitrate= 936.8kbits/s speed=1.26x    
video:33kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.445993%
[libx264 @ 000001a1ded80440] frame I:1     Avg QP: 0.00  size:  6631
[libx264 @ 000001a1ded80440] frame P:3     Avg QP: 0.00  size:  9054
[libx264 @ 000001a1ded80440] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 000001a1ded80440] mb P  I16..4: 98.5%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip: 1.5%
[libx264 @ 000001a1ded80440] coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0% inter: 0.0% 0.0% 0.0%
[libx264 @ 000001a1ded80440] i16 v,h,dc,p: 100%  0%  0%  0%
[libx264 @ 000001a1ded80440] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 000001a1ded80440] kb/s:675.86

**Comment by Gugu7798** [comment]
I don't know how to deal with it ...

**Comment by MathewSachin** [comment]
I still don't have a solution for this but I'm closing this since it is same as #492.
If you have anything to add, comment on that issue.
