### ISSUE TITLE
Is the UWP app part of your project?

### ISSUE THREAD

**Issue by HoranZuo** [MathewSachin/Captura#547]
Is this UWP app in Microsoft Store part of your project? Or it may be a pirated software
![image](https://user-images.githubusercontent.com/35492958/81708177-a4948b80-94a3-11ea-9bc4-76c16bd645c9.png)
![image](https://user-images.githubusercontent.com/35492958/81708294-b24a1100-94a3-11ea-88f8-0c50a57580fb.png)

**Comment by MathewSachin** [comment]
No, it's not. See #405 for details.
