### ISSUE TITLE
Remember last used Codec and Video Window/Screen

### ISSUE THREAD

**Issue by TheNetStriker** [MathewSachin/Captura#55]
Would it be possible to also save the last used video codec and window so I don't have to set them again after every restart?

**Comment by MathewSachin** [comment]
Yes it can be done, but proper validation needs to be done.

remembering Codec would be fine.
Windows are actually represented by `IntPtr` which changes every time it is opened. Will remembering the window title and using it to find the window be enough?

**Comment by TheNetStriker** [comment]
Thats ok for me. I'm using the "Screen" video option most of the time.

**Comment by MathewSachin** [comment]
I have implemented something for the Window and Screen part.
See #56.
Please test and let me know how it works.

I would implemented persistence for Codecs ASAP.

**Comment by TheNetStriker** [comment]
I currently only got Visual Studio 2015, so I cannot compile the project. Or do you have a command line build command that works on any machine?

**Comment by MathewSachin** [comment]
Dev builds are available from AppVeyor: https://ci.appveyor.com/project/MathewSachin/captura

Here's the download link for the built app: https://ci.appveyor.com/api/buildjobs/f4jt7gphnsu4uns8/artifacts/Output%2FCaptura-Debug.zip

**Comment by TheNetStriker** [comment]
Thanks for the links. The video source is restoring correctly, but the video codec is always set to ffmpeg. Could you please take another look why this isn't saved or loaded?

**Comment by MathewSachin** [comment]
I haven't implemented that for Video source. Would do it ASAP.

**Comment by MathewSachin** [comment]
Implemented Video Source 🎉: https://ci.appveyor.com/api/buildjobs/ivo3nbtdb9pwas7g/artifacts/Output%2FCaptura-Debug.zip

**Comment by TheNetStriker** [comment]
Video codec settings are looking good. But I just noticed that only Video Window and Screen settings are saved. Would it be possible to also save the other selections? (No Video, Region and WebCam)

**Comment by MathewSachin** [comment]
WebCam support has not been implemented in Captura.

I would try implementing for `No Video` and `Region`.

BTW, I'm planning to do this with a lot more options. Please See #56.

**Comment by MathewSachin** [comment]
Done for `No Video` and `Region`. 🎉 🎉 🎉
