### ISSUE TITLE
Video capture with audio does not work.

### ISSUE THREAD

**Issue by TheNetStriker** [MathewSachin/Captura#64]
I think I just found a bug. If I select a microphone or speaker audio source, no video file is generated. Without any audio source capturing works. Can you please take a look at this?

**Comment by MathewSachin** [comment]
Please try with the latest release. It's working on my system.

If still not working. Please tell me the Video Encoder you are using: FFMpeg, SharpAvi and file format.

**Comment by TheNetStriker** [comment]
Thanks for the quick reply. I've tested this with 3.2.0 and 3.3.0. Recording with audio works with 3.2, but 3.3 crashes immediately on start. What could be the cause of this crash?

**Comment by MathewSachin** [comment]
Thank you for the logs. I will see what it contains.

**Comment by MathewSachin** [comment]
I'm inspecting the logs. In the meantime please test with latest dev build: https://ci.appveyor.com/api/buildjobs/92po0ajhqqne2at9/artifacts/Output%2FCaptura-Debug.zip

**Comment by TheNetStriker** [comment]
I just tried the debug version and there is no crash. Maybe the problem is already fixed.

**Comment by MathewSachin** [comment]
So, time for a new version. Also, will add about that issue in v3.3.0.

**Comment by MathewSachin** [comment]
The issue is happening only with Release builds.

Would try to fix this soon.

**Comment by MathewSachin** [comment]
@TheNetStriker Fixed It. 🎉 

Please test Release Dev Build: https://ci.appveyor.com/api/buildjobs/71whdvmoixamw4l6/artifacts/Output%2FCaptura-Release.zip

Once you confirm, would release a new version.

Thank you for saving Captura from this disaster. 👍

**Comment by Hersh10** [comment]
Hello. Just downloadwed captura, audio not recording
