### ISSUE TITLE
Captura doesn't recognize DPI scaling

### ISSUE THREAD

**Issue by AlexAlabyev** [MathewSachin/Captura#69]
I have 1080p screen, and in my case windows 10 automatically changes DPI to 125%, so when you try to record a region with Captura it offsets the recording area by 25%.

Since Windows 10 changes DPI automatically for screens larger than 1080p, it will affect a lot of users.

**Comment by MathewSachin** [comment]
Thank you for notifying.
I had missed the issue because I was using at `100%` scaling.

I am unaware of the thing and would need to research a bit.
If you are aware, feel free to send a pull request.

**Comment by MathewSachin** [comment]
After testing the app a few times, I noticed that after re-login (as recommended by Windows 10), these DPI related problems did not happen.

**Resolution:** 1920x1080
**OS:** Windows 10 Creators Update

**Comment by MathewSachin** [comment]
Another thing to note: WPF uses device-independent pixels, but WinApi uses pixels.

This causes a problem with the `Region Selector`.
Everything else seems fine on my computer.
Please notify if you have found errors in other areas.

**Comment by AlexAlabyev** [comment]
@MathewSachin hmm.. for me it doesn't work after system reboot either. Well, it has been always set to 125%, so, the reboot shouldn't have fix anything for me., regardless.

Another thing is, it's not always offsetting it by 25% to the left. It depends on where on the screen the recording region is located. So here's a few gifs that I made after the system restart

## Screenshot of what it should've recorded (the whole area inside the frame):
![1](https://user-images.githubusercontent.com/13764106/27254291-42932936-538e-11e7-9f2e-9057fed4ca0e.PNG)

## Here's what it actually recorded:
### Region roughly in the **center** of the screen:
![2_center](https://user-images.githubusercontent.com/13764106/27254300-632fc9ce-538e-11e7-82fb-449d8d0a1372.gif)

### Region in the **bottom left corner** of the screen:
![4_bottom_left](https://user-images.githubusercontent.com/13764106/27254317-b3c4e20c-538e-11e7-9cca-d08a89292095.gif)

### Region in the **bottom right corner** of the screen:
![3_bottom_right](https://user-images.githubusercontent.com/13764106/27254319-b832ffea-538e-11e7-877c-469422fa328d.gif)

You can even see the recording preview frame itself.

**Comment by AlexAlabyev** [comment]
@MathewSachin I'm not really familiar with C# and WPF I'm not . Have you tried to

**Comment by AlexAlabyev** [comment]
@MathewSachin sorry, I accidentally closed the issue.
Have you ever tried creating an app using UWP instead of WPF? I'm not really familiar with Windows developer tools and APIs, but UWP is a modern developer tool, maybe it could fix the DPI problem and the high memory usage?

**Comment by MathewSachin** [comment]
Got it!
Fixing the DPI bug is in progress.

And, UWP is very limited in terms if the available APIs. So, I think it would not be possible to use that anyway.

Regarding high memory usage, are you using the Gif encoder?

**Comment by AlexAlabyev** [comment]
@MathewSachin Oh nice, good job!

Well, I once caught it using 3,5 GB of RAM but, I can't remember which encoder did that. Now I'm using ffmpeg for gif recording (constant 30fps) and it's never above 100mb

**Comment by MathewSachin** [comment]
That high memory usage should have happened with a previous version, it was recently fixed.

**Comment by MathewSachin** [comment]
@AlexAlabyev, I opened Pull Request: #70.

Please test. Here's the Dev Build from AppVeyor: https://ci.appveyor.com/api/buildjobs/fhfsm54v2ae8malr/artifacts/Output%2FCaptura-Release.zip

**Comment by AlexAlabyev** [comment]
@MathewSachin I just tested it and it works fine, no offset now!

**Comment by MathewSachin** [comment]
Would merge ASAP

**Comment by AlexAlabyev** [comment]
@MathewSachin Nice! 
If you'll keep improving functionality of the Captura at this rate and add things like vp9 and HEVC video recording, at some point in the future Captura might even replace commercial Bandicam!

**Comment by MathewSachin** [comment]
Oh! Thank you for the compliment.
Just keep reporting any bugs you encounter.
Thats the best way you are supporting Captura.

**Comment by MathewSachin** [comment]
I tried implementing x265 HEVC.

Please test Dev build: https://ci.appveyor.com/api/buildjobs/l7ota2i24jucop0t/artifacts/Output%2FCaptura-Release.zip

Vp9 would require more work.

**Comment by AlexAlabyev** [comment]
@MathewSachin Oh wow, that was quick! I just tested it and found a few issues:

### **Very high CPU usage at 30fps | tested at 75% - 100% quality:**
**CPU Usage by the processes:** ffmpeg process 37% | Captura process 25%

**Tested on these CPUs (both have high CPU usage):**  
1. i7 7700hq ( HEVC hardware encoding - IntelQuickSync)
2. i7 3630qm (supports only h264 hardware encoding - IntelQuickSync) 

(For reference) Bandicam CPU usage at 60fps is about 4% using HEVC intel Quick Sync (i7 7700hq).
So, I'm not sure if Captura using HEVC hardware encoding on my i7 7700hq.

**Possible causes:**
- Maybe it's because Captura isn't using hardware encoder? (Well, I don't know about this one, it's HEVC it should NOT use so much power even without hardware encoding, right?)
- Maybe ffmpeg using some flags causing it to do this (but I think it's NOT the lossless flag that's causing high CPU usage, because the size of the video file is comparable to that from the Bandicam, and if it would record lossless the file would be a few GB in size, but it was just 50mb for 23 sec.)
- Maybe it's just because it doesn't use "Enhanced Capture method" and that's why Bandicam using so much less power? (Screenshot from Bandicam settings:)
![3](https://user-images.githubusercontent.com/13764106/27285856-bef6fe16-5506-11e7-9b36-4347d2a99d2b.PNG)
### Problem with recording
- I noticed that the video plays at 133% speed. So, a video ends at 66% and just shows the last frame till the end of the video. I don't know why Captura/ffmpeg encodes it in this way.
### Some other issues:
- There's no option to record at 60fps (which is really needed, most people are now recording in 60fps, myself included)
- There's an option now to choose encoder named "folder" I suppose that's just a placeholder or something?
- There's no option to just record the **whole screen** without specifying a window (even though it records the whole screen anyway when you choose a window). Maybe just add another option besides Region | Window | no video? I think it would be nice to be able just to choose **Full Screen** or specify the size:(example from Bandicam settings:)
![2](https://user-images.githubusercontent.com/13764106/27287595-e1a1df20-550c-11e7-950b-1069173e0d66.PNG)

P.S.
I'm not sure if there is a way to implement Intel Quick Sync or Nvidia NVENC hardware encoders for HEVC in ffmpeg, or if it even will fix the high CPU usage (as I mentioned above it's probably not the cause of the problem). 
(By the way, not all CPUs support IntelQuickSync HEVC encoding, if you're going to try testing it on your CPU)

**Comment by MathewSachin** [comment]
@AlexAlabyev Thank you for your detailed response,

## High CPU usage
Regarding the high CPU usage, Captura does not currently use hardware acceleration or any other very advanced stuff. All it does is mainly through software. We are looking forward to improve this. This will take time to implement though.
For the encoding purpose FFMpeg is used which might be working slow for our case. But, I can't think of a better free tool.

## IntelQuickSync
I'm sorry. I'm unaware of how this could be done using ffmpeg. Time to Research!

## 133% speed
Regarding the 133% speed, does it happen with other codecs? If only with HVEC, then it might be an issue with FFMpeg.
Also, since Captura is slow (I won't hide the truth as declared in the FAQ), try lowering the frame rate.

## 60 fps
My system was a humble one when I started using Captura, so I didn't think that the algorithm used in Captura might even hit 30 fps.
I don't think that raising the limit to 60 fps would currently be of use as the method won't work that fast.
We would try to improve the capture algorithm and once it would be possible to we would allow choosing frame rates over 30 fps.

## Folder
The folder encoder is a new one, we are just experimenting with post-capture encoding. It saves all the images to a folder in the output directory.
Later you can currently manually encode them into a video.
We would try to automate that in the future.

## Full Screen Recording
Currently for full screen recording, select **[Desktop]** from the **Window** list.

## Specifying size while recording
Here, we are planning to extend Region Selector to include boxes to specify height and width.

**Comment by AlexAlabyev** [comment]
@MathewSachin yeah, no problem

### 133% problem
I tried both **ffmpeg x264** and **SharpAvi x264vfw** and they are encoding video properly
So, the problem occurs only with **ffmpeg HEVC** (doesn't matter what quality I choose), but what strange is that if I choose 25fps it will encode video to play at roughly ~110% speed and freeze the last frame at 90% of the video (instead of 133% and 66% at 30fps), so the lower the frame rate the closer it gets to 100% playback speed (normal speed). 

Also, what about that "Enhanced Capture method", do you think that is what causing the high CPU usage by Captura? Or it's turned on and Captura is using this method?

**Comment by MathewSachin** [comment]
So it must be that FFMpeg is slow in encoding HVEC. That's the cause of 133% problem.

And, sorry I am not currently aware of the **Enchanced Capture Method**, so don't know if that would help.

**Comment by AlexAlabyev** [comment]
@MathewSachin Well the **Enchanced Capture Method** is a Microsoft's API presented in Windows 8, it improves screen recording performance.

Also, you can find some information about ffmpeg **intel QSV** and **nvidia HVENC** hardware acceleration here [https://trac.ffmpeg.org/wiki/HWAccelIntro](https://trac.ffmpeg.org/wiki/HWAccelIntro
)
Here's an **intel QSV** example from that page:

> 
> Support for decoding and encoding is integrated in FFmpeg through several codecs identified by the _qsv suffix. In particular, it currently supports MPEG2 video, VC1 (decoding only), H.264 and H.265.

For example to encode to H.264 using h264_qsv, you can use the command:
 `ffmpeg -i INPUT -c:v h264_qsv -preset:v faster out.qsv.mp4` If you have a Kaby Lake CPU, you can encode with HEVC using hevc_qsv:
 `ffmpeg -i INPUT -c:v hevc_qsv -load_plugin hevc_hw -preset:v faster out.qsv.mp4`

**Comment by MathewSachin** [comment]
Thank you 👍  for all the info. Would try to come up with something soon.

**Comment by AlexAlabyev** [comment]
@MathewSachin by the way, if you'll need any tips about implementing hardware encoders [QuickSync, NVENC or AMD VCE] or other video/audio recording related things, you can find some ideas and code implementations here in the OBS github project: [https://github.com/jp9000/obs-studio](https://github.com/jp9000/obs-studio) I found that it's using just 4% of CPU while recording at 60fps(1080p) with QuickSync and these settings (settings-->output-->advanced view-->recording):

![image](https://user-images.githubusercontent.com/13764106/27614636-95290db2-5bab-11e7-82d6-aff32a778107.png)

![1](https://user-images.githubusercontent.com/13764106/27614516-ff464aee-5baa-11e7-87b2-3f2304fea20f.PNG)

ffmpeg-mux64.exe process was using just 0.1% during encoding.
Anyway. It might be useful to you if you decide to implement it yourself, because 60fps@1080p sure does work like a charm in OBS
