### ISSUE TITLE
Exception on "Snap to Window"

### ISSUE THREAD

**Issue by gustav21** [MathewSachin/Captura#77]
If I select "Region" and then click on "Snap to Window" (press and release immediately) in Region Selector, I get an Exception.

Example is attached.
[2017-07-04-10-43-46.zip](https://github.com/MathewSachin/Captura/files/1121288/2017-07-04-10-43-46.zip)

**Comment by MathewSachin** [comment]
Thank You for reporting this bug.
Clicking on it now snaps to the window below.
