### ISSUE TITLE
Create installer package 

### ISSUE THREAD

**Issue by pedrogarcia** [MathewSachin/Captura#81]
It would be nice if there was an installer packages, that would create shortcuts in start menu and desktop, put files in appropriate places, detect ffmpeg binaries, and so on.

**Comment by MathewSachin** [comment]
I'm not familiar with any Installer maker software. Would need to look for a good one and get familiar. So, I will make an installer, but it might take time.

BTW, there is a Chocolatey package. It does not do much, just makes it easier to install/update.
```
choco install captura -y
```

Also, you are free to contribute if you wish.

**Comment by xxczaki** [comment]
@MathewSachin I recommend [Advanced Installer](http://www.advancedinstaller.com/) for Visual Studio Projects ;)

**Comment by MathewSachin** [comment]
Thank you @xxczaki, I will look into it. 👍

**Comment by pedrogarcia** [comment]
[This](https://github.com/Squirrel/Squirrel.Windows) seems to be a very interesting project that might fit captura.

**Comment by MathewSachin** [comment]
Squirrel.Windows seems really amazing 👍. I just need to figure out how to keep the chocolatey package in sync with automatic updating.

**Comment by MathewSachin** [comment]
Squirrel installer in master branch. 🎉
