### ISSUE TITLE
Captura.Console ProcessExit

### ISSUE THREAD

**Issue by avpirogov** [MathewSachin/Captura#85]
When I run console app like "captura start" and then just close console window the output video file is broken.

It would be nice to stop video recording when user terminate process, like this:
```
AppDomain.CurrentDomain.ProcessExit +=
    new EventHandler(CurrentDomain_ProcessExit);
```

**Comment by MathewSachin** [comment]
`ProcessExit` is triggered only when App exits normally.
`Console.CancelKeyPress` can be used for `Ctrl + C`.
I'm not sure what can be used for the Console Window closing.

**Comment by avpirogov** [comment]
See [solution here](https://github.com/MathewSachin/Captura/issues/86)

**Comment by MathewSachin** [comment]
I think you mean to say that using `CreateNoWindow` solved your problem. Is it?
