### ISSUE TITLE
Inno Setup

### ISSUE THREAD

**Issue by Jhovany200** [MathewSachin/Captura#95]
Why not create a custom installer with inno setup?
With the languages ​​already found in the Captura and also please add my language that you send.
It would be good.

**Comment by MathewSachin** [comment]
We already have an installer created using Squirrel.Windows which was preferred due to being fast and the ease of automatic updating.

Sorry, I'm not sure how the translation you sent for Spanish is different from that already present in the master branch.

**Comment by Jhovany200** [comment]
I myself cut several parts of the texts and improved the translation
Can you merge my translation
