### ISSUE TITLE
Let the user make mouse click circle smaller and more transparent

### ISSUE THREAD

**Issue by bsto** [MathewSachin/Captura#99]
When I enable mouse click monitoring a fat yellow circle is drawn around the mouse click.

I found no option 
- to change the color
- make it partially transparent (e.g.30%)
- define a smaller size of the circle (e.g. only 20 pixels)

Could you add these options

**Comment by MathewSachin** [comment]
The options are already there.
There's an ellipsis (three dots) to the right of the mouse clicks and keystrokes toggle buttons.

You can customize various aspects of them there.

**Comment by bsto** [comment]
Ok, I found it :-)

Rather unusual, hidden place to put preferences.
I suggest to replace the label "..." by "mouse click setup" or similar

**Comment by MathewSachin** [comment]
Would it be OK if I move that to the Configure tab?
